# Simplified Chinese translations for modules: report, playback
MAP_ZH_4A = {
  "report.playback.open": "交互式回放",
  "report.att.ABSENT": "缺勤",
  "report.att.EXCUSED": "请假",
  "report.att.LATE": "迟到",
  "report.att.NONE": "—",
  "report.att.PRESENT": "出勤",
  "report.att.absent": "缺勤：{value, number}",
  "report.att.excused": "请假：{value, number}",
  "report.att.finalized": "已定稿",
  "report.att.late": "迟到：{value, number}",
  "report.att.present": "出勤：{value, number}",
  "report.att.provisional": "临时",
  "report.att.total": "总计：{value, number}",
  "report.att.unrecorded": "未记录",
  "report.attendance.noRoster": "此课时无可用的选课名单。",
  "report.attendance.noSection": "本次课时未关联至特定班级/组；正式考勤仅对分班课时记录。实际参与者名单见下方。",
  "report.attendance.title": "考勤",
  "report.back": "返回课时中心",
  "report.captions.lines": "字幕行数",
  "report.captions.linesValue": "{value, number} 行",
  "report.captions.recording": "录像",
  "report.captions.soniox": "已存储的实时翻译",
  "report.captions.title": "字幕与录像",
  "report.chat.download": "下载逐字稿",
  "report.chat.empty": "本节课的公共聊天中未记录任何消息。",
  "report.chat.exportHead": "课时聊天日志：{title}",
  "report.chat.showAll": "显示全部 {value, number} 条消息",
  "report.chat.showLess": "显示较少",
  "report.chat.title": "已保存的聊天",
  "report.chat.truncated": "正在显示前 {shown, number} 条消息，共 {total, number} 条（显示限制）。",
  "report.conn.direct": "直接连接",
  "report.conn.nat": "通过 NAT",
  "report.conn.relay": "通过中继",
  "report.conn.unknown": "未知",
  "report.counselor.adviseesTitle": "我的受指导学生",
  "report.counselor.eyebrow": "直播课堂 · 课时综合报告",
  "report.counselor.helpBody": "顾问视图：课时考勤汇总统计（不含姓名），以及已与您排定指导的学生考勤状态。课堂聊天和逐字稿在此视图中被排除。",
  "report.counselor.helpTitle": "顾问报告指南",
  "report.counselor.kpiAdvisees": "受指导学生",
  "report.counselor.kpiTotal": "学生总数",
  "report.counselor.noAdvisees": "您的受指导学生均未选修此课程。",
  "report.counselor.privacyNotice": "作为顾问，您仅可访问受指导学生的考勤记录。",
  "report.counselor.title": "顾问考勤报告",
  "report.csv.attendance": "考勤状态",
  "report.csv.duration": "在课时长（分钟）",
  "report.csv.email": "电子邮件",
  "report.csv.name": "姓名",
  "report.csv.role": "角色",
  "report.csv.status": "状态",
  "report.downloadCsv": "下载 CSV",
  "report.downloadPdf": "下载 PDF",
  "report.duration": "课时时长：{duration}",
  "report.endedAt": "结束于 {date} {time}",
  "report.engagement.avgScore": "平均参与度评分",
  "report.engagement.chatCount": "聊天消息数",
  "report.engagement.handCount": "举手次数",
  "report.engagement.pollCount": "投票回应数",
  "report.engagement.title": "互动参与度概览",
  "report.instructor": "授课教师：{name}",
  "report.kpi.absent": "缺勤人数",
  "report.kpi.attendanceRate": "出勤率",
  "report.kpi.avgAttention": "平均专注度",
  "report.kpi.enrolled": "选课人数",
  "report.kpi.excused": "请假人数",
  "report.kpi.late": "迟到人数",
  "report.kpi.peak": "最高在线峰值",
  "report.kpi.present": "出勤人数",
  "report.kpi.totalAttendees": "实际到课总人数",
  "report.liveAnalysis.confidence": "置信度水平：{value, number, ::percent}",
  "report.liveAnalysis.keyPoints": "涵盖的核心要点",
  "report.liveAnalysis.questions": "课上提出的问题",
  "report.liveAnalysis.summary": "AI 生成的课时摘要",
  "report.liveAnalysis.title": "课时智能分析",
  "report.participants.colAttendance": "考勤状态",
  "report.participants.colDuration": "在课时长",
  "report.participants.colEmail": "邮箱",
  "report.participants.colJoinTime": "进入时间",
  "report.participants.colLeaveTime": "离开时间",
  "report.participants.colName": "姓名",
  "report.participants.colRole": "角色",
  "report.participants.empty": "暂无参与者记录。",
  "report.participants.searchPlaceholder": "搜索参与者…",
  "report.participants.title": "参与者详细名单",
  "report.poll.empty": "本节课未进行任何投票。",
  "report.poll.results": "投票结果",
  "report.poll.title": "已进行的投票",
  "report.poll.totalVotes": "总投票数：{count, number}",
  "report.recording.duration": "录像时长：{duration}",
  "report.recording.empty": "本节课无可用录像。",
  "report.recording.processing": "正在处理录像…",
  "report.recording.ready": "录像已就绪可供观看",
  "report.recording.size": "文件大小：{size}",
  "report.recording.title": "课堂录像",
  "report.recording.watch": "观看录像",
  "report.startedAt": "开始于 {date} {time}",
  "report.title": "直播课时报告",
  "playback.back": "返回课时报告",
  "playback.chatTitle": "回放公开聊天",
  "playback.archivedChatTitle": "已归档的直播聊天（只读）",
  "playback.replayChatTitle": "回放新聊天",
  "playback.replayChatMessageLabel": "回放新消息",
  "playback.sendReplayChat": "在当前时间点发送消息",
  "playback.replayChatHidden": "此消息已被对他人隐藏",
  "playback.replayChatHide": "隐藏消息",
  "playback.replayChatUnhide": "取消隐藏消息",
  "playback.replayChatReportReason": "举报消息理由",
  "playback.replayChatReport": "举报消息",
  "playback.replayChatUnavailable": "回放聊天不可用或操作不被允许。",
  "playback.loadMoreChat": "加载更早的消息",
  "playback.makeupTitle": "回放补课考勤认定",
  "playback.makeupSeparateNotice": "此学分在教师审核后记录，不会直接修改历史考勤或成绩。",
  "playback.makeupSessionLabel": "补课课时 ID",
  "playback.makeupThresholdLabel": "最低验证观看时长（百分比）",
  "playback.makeupEnable": "启用补课认定",
  "playback.makeupDisable": "停用补课认定",
  "playback.makeupThreshold": "要求的最低观看时长：{percent}%",
  "playback.makeupOpenSession": "前往补课课时回放",
  "playback.makeupWatched": "服务器记录的观看时长：{percent}%",
  "playback.makeupReasonLabel": "补课申请理由",
  "playback.makeupClaim": "提交补课审核申请",
  "playback.makeupCreditStatus": "认定状态：{status}",
  "playback.makeupStudentLabel": "学生",
  "playback.makeupDecisionReasonLabel": "教师裁定理由",
  "playback.makeupConfirm": "确认补课认定",
  "playback.makeupReverse": "手动撤销已确认的认定",
  "playback.makeupUnavailable": "补课考勤操作不被允许或信息不可用。",
  "playback.makeupStatus.pending": "等待审批",
  "playback.makeupStatus.confirmed": "已确认",
  "playback.makeupStatus.cancelled": "已取消",
  "playback.makeupStatus.reversed": "已撤销",
  "playback.artifactsTitle": "课后共享的持久化文件",
  "playback.artifactsAudienceNotice": "这些文件仅对当前具有本课程及录像访问权限的用户可见；屏幕共享内容不予存储。",
  "playback.downloadArtifact": "下载文件",
  "playback.speed": "播放速度",
  "playback.quality": "视频画质",
  "playback.fullscreen": "全屏",
  "playback.play": "播放",
  "playback.pause": "暂停",
  "playback.mute": "静音",
  "playback.unmute": "取消静音",
  "playback.jumpBack": "快退 10 秒",
  "playback.jumpForward": "快进 10 秒",
  "playback.currentTime": "当前时间",
  "playback.duration": "总时长",
  "playback.transcriptTitle": "交互式逐字稿",
  "playback.searchTranscript": "在逐字稿中搜索…",
  "playback.noTranscript": "此录像无可用的逐字稿。"
}
