# Spanish translations for remaining 364 keys
MAP_ES_MISSING = {
  "breakout.end": "Finalizar",
  "breakout.manualLabel": "Asignación manual",
  "breakout.maxRooms": "Máximo {count, number} salas",
  "breakout.mode.auto": "Automático",
  "breakout.mode.manual": "Manual",
  "breakout.mode.random": "Aleatorio",
  "breakout.modeLabel": "Método de asignación",
  "breakout.moved": "Has sido movido a esta sala",
  "breakout.noParticipants": "Aún no hay participantes en clase. Podrás asignarlos cuando otros se unan.",
  "breakout.noneOpen": "No hay salas de grupo activas. Cuando el anfitrión abra salas, aparecerá la tuya.",
  "breakout.open": "Abrir salas",
  "breakout.phaseNote": "En esta etapa, la asignación de participantes y el chat/notas por sala están activos.",
  "breakout.preview": "{people, number} participantes se distribuirán en {rooms, number} salas (aprox. {per, number} personas por sala).",
  "breakout.roomCountLabel": "Número de salas",
  "breakout.roomFor": "Sala para {name}",
  "breakout.you": "Tú",
  "classes.group.live": "En vivo ahora",
  "classes.group.liveEmpty": "No hay sesiones en vivo actualmente.",
  "classes.group.past": "Pasadas",
  "classes.group.pastEmpty": "No hay sesiones pasadas registradas.",
  "classes.group.upcoming": "Próximas",
  "classes.group.upcomingEmpty": "No hay sesiones programadas próximamente.",
  "classes.help.body": "En esta página puedes ver las clases divididas en \"En vivo ahora\", \"Próximas\" y \"Pasadas\". Pulsa \"Entrar a la sala de espera\" para probar cámara y micrófono; si una sesión está en curso, pulsa \"Entrada directa\".",
  "classes.help.title": "Guía de clases en vivo",
  "classes.kpi.live": "En vivo ahora",
  "classes.kpi.past": "Pasadas",
  "classes.kpi.scheduled": "Programadas",
  "classes.kpi.total": "Total de sesiones",
  "classes.kpi.upcoming": "Próximas",
  "classes.searchAria": "Buscar sesiones en vivo",
  "classes.searchClear": "Limpiar búsqueda",
  "classes.searchPlaceholder": "Buscar por título de sesión o nombre de curso…",
  "classes.sectionAll": "Todo el curso",
  "classes.sectionFilter": "Filtrar por grupo",
  "classes.sectionFilterAll": "Todos los grupos",
  "classes.sectionGroup": "Grupo {group, number}",
  "classes.sort.dateAsc": "Fecha (más antigua primero)",
  "classes.sort.dateDesc": "Fecha (más reciente primero)",
  "classes.sort.title": "Título",
  "classes.sortAria": "Ordenar sesiones",
  "guide.classes.chain.enter": "Haz clic en \"Entrar a la sala de espera\" para probar dispositivos, o \"Entrada directa\" si la clase ya ha comenzado.",
  "guide.classes.chain.find": "Encuentra tu clase deseada en \"En vivo ahora\" o \"Próximas\".",
  "guide.classes.chain.recordings": "Tras finalizar la clase, accede a la grabación o informe desde \"Pasadas\".",
  "guide.classes.chain.schedule": "Como docente, pulsa \"Nueva sesión\" para programar una clase.",
  "guide.classes.ifEmpty": "Si no hay sesiones programadas, el docente aún no ha creado ninguna clase en vivo para tus cursos.",
  "guide.classes.intro": "Este es el centro de todas las sesiones de clase en vivo de tus cursos inscritos.",
  "guide.classes.roles.admin.does": "Supervisa todas las sesiones en vivo y gestiona la capacidad del sistema.",
  "guide.classes.roles.admin.label": "Administrador",
  "guide.classes.roles.host.does": "Programa nuevas sesiones, define grupos e inicia la clase.",
  "guide.classes.roles.host.label": "Profesor / Anfitrión",
  "guide.classes.roles.student.does": "Ve las sesiones programadas, entra a la sala de espera y se une a la clase.",
  "guide.classes.roles.student.label": "Tú (Estudiante)",
  "guide.classes.title": "Guía de sesiones de clase",
  "guide.classes.youCan.direct": "Entra directamente a una clase que ya esté en curso.",
  "guide.classes.youCan.filter": "Filtra sesiones por estado o busca por nombre de curso.",
  "guide.classes.youCan.lobby": "Comprueba tu audio y video en la sala de espera antes de entrar.",
  "guide.classes.youCan.schedule": "Programa una nueva clase si tienes permisos de docente.",
  "guide.lobby.chain.camera": "Verifica tu cámara y micrófono en la vista previa.",
  "guide.lobby.chain.enter": "Cuando todo esté listo, pulsa \"Entrar a clase\".",
  "guide.lobby.chain.perm": "Concede permisos de navegador para cámara y micrófono.",
  "guide.lobby.chain.settings": "Ajusta tus dispositivos o activa silenciado si lo prefieres.",
  "guide.lobby.ifEmpty": "Si los dispositivos no aparecen, comprueba la conexión de tu cámara y micrófono.",
  "guide.lobby.intro": "Esta sala de espera te permite comprobar tu equipo y conexión antes de entrar a la clase.",
  "guide.lobby.roles.host.does": "Gestiona los ajustes de la sala y espera a que los alumnos ingresen.",
  "guide.lobby.roles.host.label": "Profesor / Anfitrión",
  "guide.lobby.roles.student.does": "Prueba cámara/micrófono, comprueba la preparación y entra a clase.",
  "guide.lobby.roles.student.label": "Tú (Estudiante)",
  "guide.lobby.roles.support.does": "Proporciona asistencia técnica si los dispositivos fallan repetidamente.",
  "guide.lobby.roles.support.label": "Soporte técnico",
  "guide.lobby.youCan.camera": "Visualiza la vista previa de la cámara y actívala o desactívala.",
  "guide.lobby.youCan.join": "Cuando todo esté listo, únete usando el botón Entrar a clase.",
  "guide.lobby.youCan.mic": "Activa o desactiva tu micrófono con el botón de micrófono.",
  "guide.lobby.youCan.name": "Edita tu nombre visible antes de entrar a clase.",
  "guide.sections.chain": "Recorrido completo, de principio a fin",
  "guide.sections.ifEmpty": "Si la página está vacía",
  "guide.sections.roles": "Quién hace qué",
  "guide.sections.youCan": "¿Qué puedes hacer aquí?",
  "guide.session.chain.participate": "Durante la clase participas por micrófono/cámara/chat; el docente modera el flujo.",
  "guide.session.chain.record": "Si el profesor graba la clase, estará disponible tras finalizar.",
  "guide.session.chain.review": "Vuelve desde Grabaciones para repasar una clase perdida.",
  "guide.session.chain.start": "El profesor inicia la clase en vivo; tú te unes a la sala.",
  "guide.session.ifEmpty": "Si la clase aún no ha comenzado, espera al docente.",
  "guide.session.intro": "Esta es tu aula virtual en vivo con micrófono, cámara, pizarra, chat y preguntas.",
  "guide.session.roles.host.does": "Inicia y modera la clase, y graba si es necesario.",
  "guide.session.roles.host.label": "Profesor / Anfitrión",
  "guide.session.roles.student.does": "Se une a la clase, participa y consulta grabaciones.",
  "guide.session.roles.student.label": "Tú (Estudiante)",
  "guide.session.title": "Guía de la clase en vivo",
  "guide.session.youCan.chat": "Envía mensajes o preguntas escritas en el Chat.",
  "guide.session.youCan.media": "Enciende o apaga tu micrófono y cámara desde la barra inferior.",
  "guide.session.youCan.recordings": "Tras finalizar la clase, mira la grabación si fue registrada.",
  "guide.session.youCan.share": "Comparte tu pantalla si el docente lo permite.",
  "playback.acceptHandover": "Aceptar transferencia de control",
  "playback.addNote": "Añadir nota en este momento",
  "playback.answerLabel": "Respuesta oficial",
  "playback.answerQuestion": "Enviar respuesta",
  "playback.artifactApprove": "Aprobar publicación",
  "playback.artifactCreate": "Guardar elemento compartido",
  "playback.artifactDocumentLabel": "ID del documento del curso",
  "playback.artifactHide": "Ocultar",
  "playback.artifactKind.file_pin": "Archivo fijado",
  "playback.artifactKind.pdf": "PDF",
  "playback.artifactKind.whiteboard": "Pizarra",
  "playback.artifactKindLabel": "Tipo de contenido",
  "playback.artifactStatus.hidden": "Oculto",
  "playback.artifactStatus.pending": "Esperando aprobación del docente",
  "playback.artifactStatus.published": "Publicado",
  "playback.artifactTitleLabel": "Título",
  "playback.artifactUnavailable": "No se permite gestionar este elemento.",
  "playback.artifactWhiteboardLabel": "Captura textual de la pizarra",
  "playback.artifactsDisableLearners": "Deshabilitar aportes de estudiantes",
  "playback.artifactsEnableLearners": "Habilitar aportes de estudiantes",
  "playback.askQuestion": "Enviar pregunta",
  "playback.captionsLabel": "Subtítulos de la sesión",
  "playback.closeRoom": "Cerrar sala",
  "playback.createRoom": "Crear sala privada",
  "playback.deleteNote": "Eliminar",
  "playback.downloadTranscript": "Descargar transcripción",
  "playback.editNote": "Editar",
  "playback.eyebrow": "Reproducción interactiva",
  "playback.hideCaptions": "Ocultar subtítulos",
  "playback.inviteRoom": "Invitar",
  "playback.joinRoom": "Unirse a la sala",
  "playback.jump": "Saltar a este evento",
  "playback.jumpToPoll": "Saltar a la encuesta {question}",
  "playback.jumpToTableStart": "Saltar al inicio de actividad en mesas",
  "playback.jumpToTranscript": "Saltar a este momento de la transcripción",
  "playback.loadMoreResults": "Mostrar más resultados",
  "playback.loading": "Preparando reproducción…",
  "playback.me": "Yo",
  "playback.noMatches": "No se encontró texto que coincida con tu búsqueda.",
  "playback.noRecording": "No hay grabación disponible para esta sesión.",
  "playback.notAttendanceCredit": "Este valor por sí solo no otorga crédito de asistencia.",
  "playback.noteLabel": "Texto de la nota",
  "playback.notesTitle": "Mis notas con marca de tiempo",
  "playback.offerHandover": "Ofrecer transferencia de control",
  "playback.open": "Reproducción interactiva",
  "playback.pollAnswerFailed": "No se pudo registrar la respuesta; inténtalo de nuevo.",
  "playback.pollNotReached": "Para responder, avanza primero hasta la marca de tiempo de la encuesta.",
  "playback.pollsTitle": "Encuestas registradas",
  "playback.questionApprove": "Aprobar publicación",
  "playback.questionHidden": "Oculta para la clase",
  "playback.questionHide": "Ocultar pregunta",
  "playback.questionLabel": "Pregunta con marca de tiempo",
  "playback.questionOptIn": "Autorizar publicación",
  "playback.questionOptOut": "Retirar autorización",
  "playback.questionPublished": "Publicada para la clase",
  "playback.questionReport": "Reportar pregunta",
  "playback.questionReportReason": "Motivo del reporte",
  "playback.questionUnavailable": "Acción no permitida o la pregunta ya no está disponible.",
  "playback.questionUnhide": "Mostrar pregunta",
  "playback.questionUnpublish": "Despublicar",
  "playback.questionsTitle": "Preguntas en la reproducción",
  "playback.removeMember": "Eliminar de la sala",
  "playback.roomIdLabel": "ID de la sala",
  "playback.roomPause": "Pausar para todos",
  "playback.roomPlay": "Reproducir para todos",
  "playback.roomSeek": "Avanzar reproducción grupal al tiempo elegido",
  "playback.roomTitle": "Sala de visualización grupal",
  "playback.roomUnavailable": "La sala no está disponible o careces de permisos.",
  "playback.roomUserLabel": "ID de usuario",
  "playback.roomWaiting": "Esperando conexión con la sala…",
  "playback.saveNote": "Guardar cambios",
  "playback.searchLabel": "Buscar en transcripción",
  "playback.searchLoading": "Buscando en la transcripción…",
  "playback.searchPlaceholder": "Buscar en el audio de la sesión…",
  "playback.searchUnavailable": "Búsqueda en transcripción no disponible.",
  "playback.seekNote": "Ir a la marca de tiempo de la nota",
  "playback.serverWatchEvidence": "Progreso registrado por el servidor: {percent}%.",
  "playback.showCaptions": "Mostrar subtítulos",
  "playback.speedLabel": "Velocidad de reproducción",
  "playback.table": "Mesa {id}",
  "playback.timelineLabel": "Línea de tiempo de eventos",
  "playback.transcriptDownloadUnavailable": "Descarga de transcripción no disponible.",
  "playback.unavailable": "La reproducción para esta sesión no está disponible.",
  "playback.watchedProgress": "Reproducción vista en este dispositivo: {percent}%",
  "report.counselor.statsTitle": "Estadísticas de asistencia a la sesión",
  "report.engagement.hands": "Manos levantadas:",
  "report.engagement.handsTitle": "Manos levantadas",
  "report.engagement.notCaptured": "No se registraron interacciones interactivas en esta sesión.",
  "report.engagement.polls": "Encuestas:",
  "report.engagement.reactions": "Reacciones:",
  "report.engagement.timelineTitle": "Línea de tiempo",
  "report.errLoad": "Error al cargar el informe de la sesión.",
  "report.full.eyebrow": "Clase en vivo · Informe de sesión",
  "report.full.helpBody": "Este informe muestra todos los datos persistentes de una sesión de clase en un solo lugar: horarios, asistencia, participantes, chat, transcripción, encuestas y grabaciones.",
  "report.full.helpTitle": "Guía del informe de sesión",
  "report.hostSuffix": " (Anfitrión)",
  "report.kpi.actualMinutes": "Duración real de la sesión",
  "report.kpi.chatCount": "Mensajes en el chat",
  "report.kpi.joins": "Total de conexiones",
  "report.kpi.myMinutes": "Mi tiempo de asistencia",
  "report.kpi.myStatus": "Mi estado de asistencia",
  "report.kpi.participants": "Participantes",
  "report.kpi.presentIncLate": "Presentes (incluyendo tardanzas)",
  "report.kpi.scheduledMinutes": "Duración programada",
  "report.kpi.totalMinutes": "Minutos totales de asistencia",
  "report.loading": "Cargando informe de sesión…",
  "report.minutes": "{value, number} min",
  "report.neverOpened": "Esta sesión no se celebró (no se registró ingreso del anfitrión).",
  "report.noCourse": "Sin curso asociado",
  "report.noParticipants": "No hay participantes registrados.",
  "report.notCapturedNotice": "No se registraron datos interactivos.",
  "report.participantCount": "{count, number} personas",
  "report.polls.empty": "No hay encuestas en esta sesión.",
  "report.polls.title": "Encuestas realizadas",
  "report.provisionalNote": "La asistencia es provisional hasta que la sesión sea cerrada formalmente.",
  "report.reactions.empty": "No se registraron reacciones.",
  "report.reactions.title": "Reacciones en clase",
  "report.recording.audioOnly": "Solo audio",
  "report.recording.download": "Descargar grabación",
  "report.recording.notFound": "No se encontró grabación.",
  "report.reload": "Recargar",
  "report.rosterAttendance": "Asistencia formal de la lista",
  "report.sectionAll": "Todo el curso",
  "report.sectionBadge": "Grupo {group, number}",
  "report.sessionCancelled": "Esta sesión ha sido cancelada.",
  "report.summaryTitle": "Resumen ejecutivo",
  "report.tabs.attendance": "Asistencia",
  "report.tabs.chat": "Chat",
  "report.tabs.engagement": "Participación",
  "report.tabs.overview": "Resumen",
  "report.tabs.recording": "Grabación",
  "report.tabs.transcript": "Transcripción",
  "report.timeRange": "{start} – {end}",
  "report.unnamedParticipant": "Participante sin nombre",
  "review.reviewerPending": "Pendiente de asignación de revisor académico",
  "session.archive.recordCount": "{count, number} registros guardados",
  "session.archive.searchPlaceholder": "Buscar en el archivo…",
  "session.capset.close": "Cerrar ajustes",
  "session.captions.badge": "Subtítulos",
  "session.captions.lang": "Idioma: {lang}",
  "session.captions.off": "Desactivados",
  "session.captions.on": "Activados",
  "session.captions.status": "Estado de subtítulos",
  "session.conn.iceFailed": "Error de conexión ICE.",
  "session.conn.reconnected": "Conexión restablecida.",
  "session.conn.retry": "Reintentar conexión",
  "session.diag.audioBitrate": "Audio: {value} kbps",
  "session.diag.videoBitrate": "Video: {value} kbps",
  "session.download.audio": "Descargar audio",
  "session.download.captions": "Descargar subtítulos (.vtt)",
  "session.end.endedNotice": "La sesión ha finalizado.",
  "session.kick.confirm": "¿Expulsar a {name} de la clase?",
  "session.kick.kickBtn": "Expulsar",
  "session.media.camBlocked": "La cámara está bloqueada por el navegador.",
  "session.media.micBlocked": "El micrófono está bloqueado por el navegador.",
  "session.panel.expand": "Expandir panel",
  "session.panel.minimize": "Minimizar panel",
  "session.rec.diskFull": "Disco lleno. Grabación detenida.",
  "session.rec.starting": "Iniciando grabación…",
  "session.soniox.disconnected": "Motor de transcripción desconectado.",
  "session.soniox.init": "Inicializando transcripción…",
  "session.soniox.tokenExpired": "Sesión de transcripción expirada.",
  "session.stage.full": "Escenario completo",
  "session.stage.grid": "Vista en mosaico",
  "session.toast.copilot": "Asistente inteligente listo",
  "session.toast.hand": "Mano levantada",
  "session.toast.pollNew": "Nueva encuesta disponible",
  "session.toolbar.fullscreen": "Pantalla completa",
  "session.toolbar.grid": "Mosaico",
  "session.toolbar.pip": "Imagen en imagen",
  "session.topbar.room": "Sala: {name}",
  "session.view.speaker": "Vista de orador",
  "tables.clear": "Limpiar mesas",
  "tables.history": "Historial de mesas",
  "tables.lock": "Bloquear mesas",
  "tables.locked": "Mesas bloqueadas",
  "tables.move": "Mover a mesa",
  "tables.noHistory": "Sin historial",
  "tables.open": "Abrir mesas",
  "tables.randomize": "Reasignar aleatoriamente",
  "tables.shuffle": "Mezclar participantes",
  "tables.status.active": "Activas",
  "tables.status.closed": "Cerradas",
  "tables.status.pending": "Pendientes",
  "tables.switch": "Cambiar de mesa",
  "tables.unlocked": "Mesas desbloqueadas",
  "tables.undo": "Deshacer cambio de mesa",
  "atoms.transcript.seed.r2.time": "14:21"
}
