# Spanish translations for module: session (239 keys)
MAP_ES_4B = {
  "session.absence.instructorDisconnected": "El profesor se ha desconectado. La clase continúa hasta su regreso.",
  "session.absence.takeOver": "Asumir la gestión temporal de mesas y turno de palabra",
  "session.archive.btn": "Archivo de transcripciones",
  "session.archive.download": "Descargar archivo",
  "session.archive.empty": "Aún no hay voz almacenada en el archivo.",
  "session.archive.error": "Error al recuperar el archivo.",
  "session.archive.loading": "Cargando archivo…",
  "session.archive.reload": "Recargar",
  "session.archive.retry": "Reintentar",
  "session.archive.short": "Archivo",
  "session.archive.title": "Archivo de transcripciones (guardadas)",
  "session.browserUnknown": "Desconocido",
  "session.capset.btn": "Ajustes de subtítulos",
  "session.capset.fontSize": "Tamaño de fuente",
  "session.capset.lg": "Grande",
  "session.capset.maxLines": "Líneas máximas",
  "session.capset.md": "Mediano",
  "session.capset.sm": "Pequeño",
  "session.capset.title": "Configuración de subtítulos",
  "session.capset.xl": "Muy grande",
  "session.capset.xs": "Muy pequeño",
  "session.captions.cpuSlow": "Rendimiento lento de CPU; los subtítulos pueden retrasarse.",
  "session.captions.deviceUnsupported": "Dispositivo no compatible con reconocimiento de voz.",
  "session.captions.engineStuck": "El motor de subtítulos no responde. Reiniciando…",
  "session.captions.fallbackServer": "Cambiando a subtítulos del servidor…",
  "session.captions.micDenied": "Micrófono denegado para subtítulos.",
  "session.captions.micNotFound": "Micrófono no encontrado.",
  "session.captions.networkError": "Error de red en subtítulos.",
  "session.captions.permissionDenied": "Permiso denegado.",
  "session.captions.restarting": "Reiniciando subtítulos…",
  "session.captions.serverError": "Error del servidor de subtítulos.",
  "session.captions.unsupported": "Subtítulos no compatibles en este navegador.",
  "session.close": "Cerrar",
  "session.collabLoading": "Cargando herramientas colaborativas…",
  "session.conn.fair": "Regular",
  "session.conn.good": "Buena",
  "session.conn.poor": "Deficiente",
  "session.conn.unknown": "Desconocida",
  "session.connFoot": "La calidad de conexión afecta la fluidez de audio y video.",
  "session.diag.bitrate": "Tasa de bits: {value} kbps",
  "session.diag.close": "Cerrar diagnóstico",
  "session.diag.codecs": "Códecs: {audio} / {video}",
  "session.diag.connType": "Tipo de conexión: {type}",
  "session.diag.copy": "Copiar datos de diagnóstico",
  "session.diag.copyDone": "Copiado ✓",
  "session.diag.fps": "Fotogramas por segundo: {value, number}",
  "session.diag.jitter": "Jitter: {value, number} ms",
  "session.diag.latency": "Latencia: {value} ms",
  "session.diag.packetLoss": "Pérdida de paquetes: {value}%",
  "session.diag.resolution": "Resolución: {width, number}×{height, number}",
  "session.diag.roundTrip": "Ida y vuelta (RTT): {value, number} ms",
  "session.diag.server": "Servidor de medios: {server}",
  "session.diag.title": "Diagnóstico de red de la sesión",
  "session.diag.unknown": "Desconocido",
  "session.diag.uplink": "Subida: {value} kbps",
  "session.diag.downlink": "Bajada: {value} kbps",
  "session.diag.transport": "Protocolo: {proto}",
  "session.diag.webrtcState": "Estado WebRTC: {state}",
  "session.download.chat": "Descargar chat",
  "session.download.csv": "Descargar CSV",
  "session.download.json": "Descargar JSON",
  "session.download.notes": "Descargar notas",
  "session.download.pdf": "Descargar PDF",
  "session.download.transcript": "Descargar transcripción",
  "session.download.whiteboard": "Descargar pizarra",
  "session.duplicate.continued": "La sesión continuó en otra ventana.",
  "session.duplicate.continueHere": "Continuar aquí",
  "session.duplicate.replaced": "Has abierto esta sesión en otra ventana o pestaña.",
  "session.end.action": "Finalizar sesión para todos",
  "session.end.cancel": "Cancelar",
  "session.end.confirm": "Sí, finalizar sesión",
  "session.end.confirmShort": "¿Finalizar?",
  "session.end.desc": "¿Estás seguro de que deseas finalizar la sesión para todos los participantes? Se guardarán la asistencia y los registros.",
  "session.end.ending": "Finalizando clase…",
  "session.end.failed": "Error al finalizar la sesión.",
  "session.end.title": "Finalizar clase",
  "session.end.warning": "Esta acción expulsará a todos los participantes.",
  "session.ended.body": "La sesión en vivo ha concluido. Puedes revisar la grabación o el informe cuando estén listos.",
  "session.ended.cta": "Volver al aula del curso",
  "session.ended.title": "Sesión finalizada",
  "session.film.aria": "Tira de participantes",
  "session.film.hide": "Ocultar tira de participantes",
  "session.film.show": "Mostrar tira de participantes",
  "session.fs.enter": "Pantalla completa",
  "session.fs.exit": "Salir de pantalla completa",
  "session.fs.toggle": "Alternar pantalla completa",
  "session.guest": "Invitado",
  "session.jitsi.connecting": "Conectando al servidor multimedia…",
  "session.jitsi.error": "Error al conectar con la llamada en vivo.",
  "session.kick.failed": "No se pudo expulsar al participante.",
  "session.kick.manage": "Gestionar expulsiones",
  "session.kick.restore": "Permitir reingreso",
  "session.kick.restoreFailed": "No se pudo restaurar el acceso.",
  "session.lang.faShort": "FA",
  "session.langMenu.help": "Selecciona tu idioma preferido para subtítulos y traducción.",
  "session.langMenu.my": "Mi idioma",
  "session.langMenu.notFound": "Idioma no encontrado",
  "session.langMenu.searchLabel": "Buscar idioma",
  "session.langMenu.searchPlaceholder": "Buscar idioma…",
  "session.layout.custom": "Personalizado",
  "session.layout.focusPresentation": "Foco en presentación",
  "session.layout.focusVideo": "Foco en video",
  "session.layout.smart": "Diseño inteligente",
  "session.leave": "Salir de la clase",
  "session.leaveShort": "Salir",
  "session.media.audioOnly": "Solo audio activado",
  "session.media.denied": "Acceso a medios denegado",
  "session.media.errSuffix": "(Error de dispositivo)",
  "session.media.generic": "Error de medios",
  "session.media.inUse": "La cámara o el micrófono están en uso por otra aplicación.",
  "session.media.notFound": "Dispositivo de medios no encontrado.",
  "session.media.permission": "Por favor, autoriza el acceso a la cámara y al micrófono.",
  "session.media.unsupported": "Formato de medios no compatible.",
  "session.panel.chatTranslated": "Chat traducido",
  "session.panel.empty": "No hay contenido disponible en este panel.",
  "session.panel.regionLabel": "Panel lateral de herramientas",
  "session.panel.title": "Panel lateral",
  "session.participant.role.assistant": "Asistente docente",
  "session.rec.active": "Grabando clase…",
  "session.rec.armed": "Grabación lista para iniciar",
  "session.rec.cancel": "Cancelar grabación",
  "session.rec.netFailed": "Error de red al grabar",
  "session.rec.paused": "Grabación pausada",
  "session.rec.start": "Iniciar grabación",
  "session.rec.stop": "Detener grabación",
  "session.rec.saving": "Guardando grabación…",
  "session.rec.saved": "Grabación guardada correctamente.",
  "session.rec.error": "Error durante la grabación.",
  "session.rec.resumed": "Grabación reanudada.",
  "session.rec.confirmStop": "¿Detener la grabación de la sesión?",
  "session.rec.confirmCancel": "¿Cancelar y descartar la grabación?",
  "session.rec.spaceLow": "Poco espacio en disco para la grabación.",
  "session.rec.timeLimit": "Límite de tiempo de grabación cercano.",
  "session.rec.timeRemaining": "Tiempo restante de grabación: {time}",
  "session.rec.format": "Formato: MP4",
  "session.rec.cloudSync": "Sincronizando con la nube…",
  "session.rec.cloudReady": "Disponible en la nube.",
  "session.rec.permissionDenied": "No tienes permiso para grabar.",
  "session.reconnecting": "Reconectando… Por favor, espera.",
  "session.selfName": "Tú",
  "session.share.failed": "No se pudo compartir la pantalla.",
  "session.share.unsupported": "Compartir pantalla no es compatible en este navegador.",
  "session.someone": "Alguien",
  "session.soniox.captionFailed": "Error al procesar subtítulos en tiempo real.",
  "session.soniox.connecting": "Conectando motor de transcripción…",
  "session.soniox.detectedLabel": "Idioma detectado",
  "session.soniox.detectedTitle": "Detección automática de idioma",
  "session.soniox.error": "Error del motor de transcripción.",
  "session.soniox.idle": "Motor en espera.",
  "session.soniox.listening": "Escuchando audio…",
  "session.soniox.liveTag": "En directo",
  "session.soniox.noAudio": "Sin señal de audio.",
  "session.soniox.offline": "Modo sin conexión.",
  "session.soniox.paused": "Transcripción en pausa.",
  "session.soniox.quality": "Calidad de reconocimiento",
  "session.soniox.rate": "Tasa de transcripción: {rate}",
  "session.soniox.ready": "Motor listo.",
  "session.soniox.reconnect": "Reconectando motor…",
  "session.soniox.reloading": "Recargando modelo de voz…",
  "session.soniox.resuming": "Reanudando transcripción…",
  "session.soniox.server": "Servidor de transcripción conectado.",
  "session.soniox.status": "Estado: {status}",
  "session.soniox.streamError": "Error en flujo de audio.",
  "session.soniox.unsupportedLang": "Idioma no admitido para transcripción.",
  "session.soniox.words": "Palabras reconocidas: {count, number}",
  "session.stage.captionFeed": "Canal de subtítulos en vivo",
  "session.stage.modeLabel": "Modo de escenario",
  "session.stage.noShare": "Nadie está compartiendo pantalla.",
  "session.stage.noShareHint": "Cuando el profesor o un participante comparta pantalla, aparecerá aquí.",
  "session.stage.share": "Pantalla compartida",
  "session.stage.presenter": "Presentador: {name}",
  "session.supervision.offer": "Ofrecer supervisión",
  "session.supervision.offerPending": "Oferta de supervisión pendiente",
  "session.supervision.paused": "Supervisión en pausa",
  "session.supervision.recordingDenied": "Permiso de grabación de supervisión denegado",
  "session.supervision.waiting": "Esperando supervisión pedagógica…",
  "session.supervision.accepted": "Supervisión aceptada.",
  "session.supervision.declined": "Supervisión rechazada.",
  "session.supervision.ended": "Supervisión concluida.",
  "session.supervision.active": "Supervisión activa.",
  "session.tile.handRaised": "Mano levantada",
  "session.tile.pin": "Fijar video",
  "session.tile.quality": "Calidad: {quality}",
  "session.tile.unpin": "Desfijar video",
  "session.tile.muted": "Micrófono apagado",
  "session.tile.videoOff": "Cámara apagada",
  "session.tile.screenSharing": "Compartiendo pantalla",
  "session.titleFallback": "Clase virtual en vivo",
  "session.toast.captionsOn": "Subtítulos activados",
  "session.toast.chatLocked": "El chat ha sido bloqueado por el anfitrión",
  "session.toast.chatUnlocked": "El chat ha sido desbloqueado por el anfitrión",
  "session.toast.joined": "Te has unido a la clase",
  "session.toast.kicked": "Has sido expulsado de la clase",
  "session.toast.handLowered": "Tu mano fue bajada por el anfitrión",
  "session.toast.micMuted": "Tu micrófono fue silenciado por el anfitrión",
  "session.toast.recordingStarted": "La grabación de la clase ha comenzado",
  "session.toolbar.cam": "Cámara",
  "session.toolbar.captionsGroup": "Subtítulos y traducción",
  "session.toolbar.ccOff": "Desactivar subtítulos",
  "session.toolbar.ccOn": "Activar subtítulos",
  "session.toolbar.ccStarting": "Iniciando subtítulos…",
  "session.toolbar.mic": "Micrófono",
  "session.toolbar.more": "Más opciones",
  "session.toolbar.settings": "Ajustes",
  "session.toolbar.share": "Compartir pantalla",
  "session.toolbar.hand": "Levantar mano",
  "session.toolbar.handDown": "Bajar mano",
  "session.toolbar.reactions": "Reacciones",
  "session.toolbar.chat": "Chat",
  "session.toolbar.participants": "Participantes",
  "session.toolbar.whiteboard": "Pizarra",
  "session.toolbar.notes": "Notas",
  "session.toolbar.leave": "Salir",
  "session.toolbar.end": "Finalizar clase",
  "session.toolbar.record": "Grabar",
  "session.toolbar.layout": "Diseño de vista",
  "session.topbar.elapsedLabel": "Tiempo transcurrido",
  "session.topbar.hostPrefix": "Profesor:",
  "session.topbar.loadingTitle": "Cargando clase…",
  "session.topbar.recOffTitle": "Grabación apagada",
  "session.topbar.recOnTitle": "Grabación activa",
  "session.topbar.sessionTitle": "Título de la clase",
  "session.topbar.attendeeCount": "{count, number} participantes",
  "session.unpin": "Desfijar",
  "session.unpinLabel": "Desfijar video del escenario",
  "session.view.gallery": "Vista en cuadrícula",
  "session.view.modeLabel": "Modo de visualización",
  "session.view.podium": "Vista de podio / orador principal",
  "session.you": "Tú",
  "session.cohost.denied": "Permiso de coanfitrión denegado",
  "session.cohost.grant": "Designar coanfitrión",
  "session.cohost.granted": "Rol de coanfitrión otorgado",
  "session.cohost.instructorPresent": "Profesor titular presente",
  "session.cohost.manage": "Gestionar coanfitriones",
  "session.cohost.revoke": "Revocar coanfitrión",
  "session.cohost.revoked": "Rol de coanfitrión revocado"
}
