# Spanish translations for modules: signals, reactions, pulse, hands, notes, sessionAnalysis, chat, assistant, wb, panel
MAP_ES_1 = {
  "signals.aria.confused": "Indicar que el concepto no está claro",
  "signals.aria.slower": "Pedir al profesor que vaya más despacio",
  "signals.confused": "No entendí",
  "signals.sent": "Registrado",
  "signals.slower": "Más despacio",
  "reactions.throttled": "Ve más despacio — tus reacciones están temporalmente limitadas.",
  "pulse.confused": "{count, plural, one {# persona no entiende} other {# personas no entienden}}",
  "pulse.slower": "{count, plural, one {# persona pide ir más despacio} other {# personas piden ir más despacio}}",
  "pulse.title": "Pulso de la clase",
  "pulse.window": "En el último minuto",
  "hands.count": "{count, plural, one {# mano levantada} other {# manos levantadas}}",
  "hands.lower": "Bajar mano",
  "hands.lowerAll": "Bajar todas las manos",
  "hands.ordinal": "{count, number}",
  "hands.overflow": "{count, plural, one {# persona más está esperando} other {# personas más están esperando}}",
  "hands.position": "{count, plural, one {Tu turno: #} other {Tu turno: #}}",
  "hands.title": "Turno de palabra",
  "notes.ariaLabel": "Notas compartidas de la clase",
  "notes.charCount": "{count, number} caracteres",
  "notes.empty": "Aún no se ha escrito nada",
  "notes.exportLabel": "Exportar texto",
  "notes.exportTitle": "Guardar como archivo de texto (.txt)",
  "notes.placeholder": "Escribe aquí… Lo que escribas será visible para todos en tiempo real.",
  "notes.synced": "Sincronizado",
  "notes.syncing": "Los cambios se sincronizan en tiempo real",
  "notes.title": "Notas compartidas",
  "sessionAnalysis.confidence": "Confianza estimada: {value, number, ::percent}",
  "sessionAnalysis.failed": "No se pudo completar el análisis de la sesión",
  "sessionAnalysis.loading": "Analizando…",
  "sessionAnalysis.quiz": "Preguntas sugeridas ({count, number})",
  "sessionAnalysis.reviewRequired": "Este resultado es un borrador y requiere revisión del docente.",
  "sessionAnalysis.sources": "Extractos de referencia de la transcripción ({count, number})",
  "sessionAnalysis.suggestedAnswer": "Respuesta sugerida: {answer}",
  "sessionAnalysis.title": "Análisis de la sesión",
  "sessionAnalysis.truncated": "Este análisis cubre solo parte de la transcripción; el texto supera el límite de procesamiento.",
  "sessionAnalysis.unavailable": "El análisis en vivo no está disponible. No se generaron resúmenes ni preguntas.",
  "chat.anonymousAuthor": "Usuario",
  "chat.channels.class": "Clase",
  "chat.channels.staff": "Personal docente",
  "chat.channels.table": "Mesa",
  "chat.empty": "Aún no se han enviado mensajes.",
  "chat.note.class": "Los mensajes se comparten en directo con toda la clase a través del canal de la clase.",
  "chat.note.locked": "El chat ha sido bloqueado por el anfitrión. Solo el anfitrión puede enviar mensajes.",
  "chat.note.staff": "Este canal solo es visible para el docente y los asistentes; los estudiantes no pueden verlo.",
  "chat.note.table": "Esta conversación solo es visible para los integrantes de la mesa y el docente.",
  "chat.placeholder": "Escribe un mensaje…",
  "chat.placeholderLocked": "El chat está bloqueado…",
  "chat.rejected.channel": "Este canal no está disponible para ti — tu mensaje no fue enviado.",
  "chat.rejected.locked": "El chat está bloqueado — tu mensaje no fue enviado.",
  "chat.send": "Enviar mensaje",
  "chat.tableTarget": "Enviar a la mesa",
  "chat.unread": "{count, plural, one {#} other {#}}",
  "assistant.chip.example": "Dar un ejemplo",
  "assistant.chip.practice": "Crear pregunta de práctica",
  "assistant.chip.quiz": "Diseñar un cuestionario breve con respuestas",
  "assistant.chip.summarize": "Resumir este tema",
  "assistant.error.createSession": "No se pudo crear la conversación con el asistente.",
  "assistant.hostMode": "Modo profesor — Diseño de preguntas y ejercicios",
  "assistant.inputLabel": "Preguntar al asistente inteligente",
  "assistant.intro": "Pregunta sobre el tema de clase — las respuestas provienen del material del curso (RAG).",
  "assistant.introHost": " Como profesor, también puedes generar ejercicios y cuestionarios.",
  "assistant.label": "Asistente inteligente",
  "assistant.noAnswer": "No se recibió respuesta. Por favor, pregunta de nuevo.",
  "assistant.placeholder": "Escribe tu pregunta…",
  "assistant.questionCount": "{count, number} preguntas",
  "assistant.send": "Enviar pregunta",
  "assistant.sendShort": "Enviar",
  "assistant.sessionTitle": "Clase en vivo — {name}",
  "assistant.source": "Fuente",
  "assistant.sources": "Fuentes ({count, number})",
  "assistant.title": "Asistente inteligente de clase",
  "assistant.typing": "Escribiendo respuesta…",
  "wb.canvasLabel": "Lienzo de pizarra compartida",
  "wb.clearAll": "Borrar todo",
  "wb.clearAllTitle": "Borrar todo (Anfitrión)",
  "wb.clearConfirm": "Confirmar borrado total",
  "wb.clearConfirmShort": "¿Confirmar?",
  "wb.clearConfirmTitle": "Haz clic de nuevo para confirmar",
  "wb.colorGroup": "Color",
  "wb.colorSwatch": "Color {color}",
  "wb.exportPng": "Exportar PNG",
  "wb.exportPngTitle": "Guardar como imagen PNG",
  "wb.hintEmpty": "La pizarra está vacía. Selecciona una herramienta y dibuja en el lienzo.",
  "wb.hintText": "Escribe texto y pulsa Enter para colocarlo en la pizarra.",
  "wb.itemCount": "{count, plural, one {# elemento en la pizarra} other {# elementos en la pizarra}}",
  "wb.lock": "Bloquear pizarra",
  "wb.lockTitle": "Bloquear pizarra para otros participantes",
  "wb.lockedNotice": "La pizarra ha sido bloqueada por el anfitrión; solo lectura en este momento.",
  "wb.lockedTitle": "La pizarra está bloqueada — haz clic para desbloquear",
  "wb.redo": "Rehacer",
  "wb.textLabel": "Texto en la pizarra",
  "wb.textPlaceholder": "Texto… (Enter para colocar, Esc para cancelar)",
  "wb.toolbarLabel": "Herramientas de pizarra",
  "wb.tools.arrow": "Flecha",
  "wb.tools.circle": "Círculo",
  "wb.tools.eraser": "Borrador",
  "wb.tools.line": "Línea",
  "wb.tools.pen": "Lápiz",
  "wb.tools.rect": "Rectángulo",
  "wb.tools.select": "Seleccionar",
  "wb.tools.text": "Texto",
  "wb.undo": "Deshacer",
  "wb.undoTitle": "Deshacer (tu último trazo)",
  "wb.unlock": "Desbloquear pizarra",
  "wb.widthGroup": "Grosor del trazo",
  "wb.widthOption": "Grosor {width, number}",
  "panel.close": "Cerrar",
  "panel.host.actionsFor": "Acciones de anfitrión para {name}",
  "panel.host.kick": "Expulsar",
  "panel.host.lockChat": "Bloquear chat",
  "panel.host.lowerHand": "Bajar mano",
  "panel.host.makePresenter": "Hacer presentador",
  "panel.host.mute": "Silenciar",
  "panel.host.muteAll": "Silenciar a todos",
  "panel.host.unlockChat": "Desbloquear chat",
  "panel.people.note": "La lista de participantes se actualiza en tiempo real. Los videos aparecerán cuando se conecte el motor multimedia.",
  "panel.tabCount": " ({count, number})",
  "panel.tabs.analytics": "Análisis",
  "panel.tabs.assistant": "Asistente",
  "panel.tabs.breakout": "Salas de grupo",
  "panel.tabs.chat": "Chat",
  "panel.tabs.notes": "Notas",
  "panel.tabs.people": "Participantes",
  "panel.tabs.polls": "Encuestas",
  "panel.tabs.tables": "Mesas",
  "panel.transcript.captionTag": " (Voz)",
  "panel.transcript.download": "Descargar transcripción completa ⬇",
  "panel.transcript.fileHeader": "Transcripción de clase",
  "panel.transcript.fileSuffix": "-transcripcion.txt",
  "panel.transcript.preparing": "Preparando…",
  "panel.transcript.privateTag": " (Privado)",
  "panel.transcript.regionLabel": "Transcripción de voz en vivo"
}
