# Simplified Chinese translations for modules: atoms, classes, tables
MAP_ZH_3 = {
  "atoms.captions.etaTradeoff": "如果 η 过大，损失函数将发散；如果过小，收敛速度会变慢。",
  "atoms.captions.fasterNoisier": "这使得更新速度更快，但振荡幅度更大。",
  "atoms.captions.lrAnswer": "好问题。我们通常将其与学习率调度器（Learning Rate Scheduler）或 Adam 结合使用。",
  "atoms.captions.lrQuestion": "教授，如何为 SGD 选择最佳学习率？",
  "atoms.captions.sgdStep": "随机梯度下降在每一步仅使用单个样本来计算梯度。",
  "atoms.chat.seed.answer": "当然。假设 θ = 0.8，梯度 = 2.4，η = 0.1。那么：",
  "atoms.chat.seed.answerTime": "14:25",
  "atoms.chat.seed.ask": "您能提供一个 SGD 中权重更新的数值示例吗？",
  "atoms.chat.seed.askTime": "14:25",
  "atoms.chat.seed.greeting": "你好 👋 我是本节课的智能助教。我可以提供实时摘要、简化概念或推荐额外的练习题。",
  "atoms.chat.seed.greetingTime": "14:23",
  "atoms.people.ali.init": "A",
  "atoms.people.ali.name": "Ali R.",
  "atoms.people.arman.init": "A",
  "atoms.people.arman.name": "Arman B.",
  "atoms.people.azimi.init": "DA",
  "atoms.people.azimi.name": "阿齐米博士",
  "atoms.people.hanieh.init": "H",
  "atoms.people.hanieh.name": "Hanieh F.",
  "atoms.people.mohsen.init": "M",
  "atoms.people.mohsen.name": "Mohsen H.",
  "atoms.people.neda.init": "N",
  "atoms.people.neda.name": "Neda Kazemi",
  "atoms.people.nima.init": "N",
  "atoms.people.nima.name": "Nima J.",
  "atoms.people.sara.init": "S",
  "atoms.people.sara.name": "Sara M.",
  "atoms.people.zahra.init": "Z",
  "atoms.people.zahra.name": "Zahra K.",
  "atoms.poll.options.adamWeighted": "带类别加权的 Adam",
  "atoms.poll.options.rmspropWarmup": "带预热（Warm-up）的 RMSprop",
  "atoms.poll.options.sgdMomentum": "带动量的标准 SGD",
  "atoms.poll.question": "哪种优化方法最适合在不平衡数据集上训练深度神经网络？",
  "atoms.qa.q1.text": "如果损失函数是非凸的，SGD 是否能收敛到全局最小值？",
  "atoms.qa.q1.time": "2 分钟前",
  "atoms.qa.q2.text": "在实践中，Momentum 和 Adam 有什么核心区别？",
  "atoms.qa.q2.time": "5 分钟前",
  "atoms.qa.q3.text": "对于 ResNet-50，推荐使用多大的小批量（mini-batch）？",
  "atoms.qa.q3.time": "8 分钟前",
  "atoms.qa.q4.text": "在不平衡数据集上，应该对 SGD 应用哪些设置？",
  "atoms.qa.q4.time": "12 分钟前",
  "atoms.qa.tags.adaptive": "自适应",
  "atoms.qa.tags.highlight": "高光",
  "atoms.qa.tags.practical": "实践",
  "atoms.slides.compare.body": "小批量在全批量（Batch）稳定性和 SGD 速度之间取得平衡。典型大小：32 到 256。",
  "atoms.slides.noise.body": "随机波动使算法能够跳出局部极小值，在非凸曲面上表现更佳。",
  "atoms.slides.noise.title": "为什么噪声是有用的",
  "atoms.slides.sgd.body": "每一步仅使用单个随机数据样本更新权重。比全批量更快，但在收敛路径上伴随更多振荡。",
  "atoms.slides.sgd.title": "随机梯度下降 (SGD)",
  "atoms.suggestions.exercise": "生成同类练习题",
  "atoms.suggestions.resources": "补充参考资料",
  "atoms.suggestions.simpler": "用更浅显的语言解释",
  "atoms.suggestions.summary": "过去 2 分钟内容摘要",
  "atoms.tabs.assistant": "助教",
  "atoms.tabs.captions": "字幕",
  "atoms.tabs.poll": "投票",
  "atoms.tabs.questions": "提问",
  "atoms.timeline.r1.label": "上节课内容回顾",
  "atoms.timeline.r1.time": "14:02",
  "atoms.timeline.r2.label": "梯度下降核心概念",
  "atoms.timeline.r2.time": "14:08",
  "atoms.timeline.r3.label": "全批量版本",
  "atoms.timeline.r3.time": "14:16",
  "atoms.timeline.r4.label": "随机梯度下降 (SGD)",
  "atoms.timeline.r4.time": "14:22",
  "atoms.timeline.r5.label": "Momentum 与 Adam",
  "atoms.timeline.r5.time": "14:35",
  "atoms.timeline.r6.label": "互动练习与答疑",
  "atoms.timeline.r6.time": "14:45",
  "atoms.transcript.live.momentum": "如果我们在更新时考虑之前的数值，这就叫做动量（Momentum）。",
  "atoms.transcript.live.nesterovAnswer": "Nesterov 首先预测下一步的位置并在该处计算梯度。",
  "atoms.transcript.live.nesterovQuestion": "这与 Nesterov 算法有何不同？",
  "atoms.transcript.live.pytorchQuestion": "这个思路可以在 PyTorch 中实现吗？",
  "atoms.transcript.seed.r1.text": "在随机梯度下降中，每一步仅使用单个样本来计算梯度。",
  "atoms.transcript.seed.r1.time": "14:20",
  "atoms.transcript.seed.r2.text": "这提升了计算速度并显著降低了内存占用。",
  "atoms.transcript.seed.r3.highlight": "最佳学习率",
  "atoms.transcript.seed.r3.text": "教授，如何选择最佳学习率？",
  "atoms.transcript.seed.r3.time": "14:22",
  "atoms.transcript.seed.r4.text": "通常我们会结合学习率调度器或像 Adam 这样的自适应优化器。",
  "atoms.transcript.seed.r4.time": "14:22",
  "atoms.transcript.seed.r5.text": "SGD 与小批量（Mini-batch）之间的确切区别是什么？",
  "atoms.transcript.seed.r5.time": "14:23",
  "atoms.transcript.seed.r6.text": "批量大小。在小批量中我们取 32 到 256 个样本，以便在稳定性与速度之间取得更佳平衡。",
  "atoms.transcript.seed.r6.time": "14:23",
  "classes.card.attendees": "{value, number} 名参与者",
  "classes.card.cancelled": "本节课已取消。",
  "classes.card.joinDirect": "直接进入",
  "classes.card.joinLobby": "进入等候室",
  "classes.card.newTab": "在新标签页中打开",
  "classes.card.report": "课时报告",
  "classes.card.reportTitle": "本节课的完整报告",
  "classes.emptyAll": "没有符合您搜索条件的课时。",
  "classes.emptyHint": "授课教师排课后将在此处显示。",
  "classes.emptySearch": "未找到匹配此搜索或筛选条件的课时。",
  "classes.errLoad": "加载课时失败",
  "classes.eyebrow": "直播课堂 · 课时中心",
  "classes.filter.all": "全部",
  "classes.filter.ended": "已结束",
  "classes.filter.live": "正在直播",
  "classes.filter.scheduled": "已排定",
  "classes.filterAria": "筛选直播课时",
  "classes.form.applySlot": "应用此时间段",
  "classes.form.cancel": "取消",
  "classes.form.close": "关闭",
  "classes.form.course": "关联课程",
  "classes.form.coursePick": "— 选择课程 —",
  "classes.form.courseSearch": "搜索课程（代码或名称）…",
  "classes.form.courseSearchAria": "搜索课程",
  "classes.form.coursesError": "课程列表不可用；请稍后重试。",
  "classes.form.coursesLoading": "正在加载课程…",
  "classes.form.date": "日期",
  "classes.form.dateAria": "课时日期",
  "classes.form.datePlaceholder": "选择课时日期",
  "classes.form.desc": "描述（可选）",
  "classes.form.descPlaceholder": "本节课的主题或重点提示…",
  "classes.form.end": "结束时间",
  "classes.form.errCourse": "请选择一门关联课程。",
  "classes.form.errCreate": "创建新课时失败。请重试。",
  "classes.form.errDate": "请选择课时日期。",
  "classes.form.errTime": "请输入有效的起止时间。",
  "classes.form.errTitle": "请输入课时名称。",
  "classes.form.policy": "准入规则",
  "classes.form.section": "班级/分组（可选）",
  "classes.form.sectionAll": "— 全体课程（不限班级）—",
  "classes.form.sectionOption": "第 {group, number} 班",
  "classes.form.start": "开始时间",
  "classes.form.submit": "排定课时",
  "classes.form.submitting": "正在排定…",
  "classes.form.title": "排定直播课时",
  "classes.form.titleLabel": "课时名称",
  "classes.form.titlePlaceholder": "例如：第 4 讲：优化算法",
  "classes.heading": "直播课堂课时",
  "classes.hostOnly": "仅教师或管理员可以排定课时。",
  "classes.myStatus.absent": "缺勤",
  "classes.myStatus.enrolled": "已选课",
  "classes.myStatus.excused": "请假",
  "classes.myStatus.present": "出勤",
  "classes.newSession": "新建课时",
  "classes.reload": "重新加载",
  "classes.status.cancelled": "已取消",
  "classes.status.ended": "已结束",
  "classes.status.live": "正在直播",
  "classes.status.scheduled": "已排定",
  "tables.assign.balanced": "自动（均衡分配）",
  "tables.assign.noStudents": "课堂中暂无学生。",
  "tables.assign.pickFor": "为 {name} 安排讨论桌",
  "tables.assign.random": "随机分配",
  "tables.assign.title": "安排座位",
  "tables.assign.unassigned": "未分配",
  "tables.cancel": "取消",
  "tables.capacity": "{used, number} / {total, number} 人",
  "tables.capacityLabel": "每桌容量",
  "tables.confirm": "是",
  "tables.countLabel": "新建桌数",
  "tables.create": "创建讨论桌",
  "tables.defaultName": "第 {index, number} 桌",
  "tables.dissolve": "解散讨论桌",
  "tables.dissolveConfirm": "解散“{name}”？其成员将返回主课堂。",
  "tables.duration.label": "分组工作时长",
  "tables.duration.option": "{count, number} 分钟",
  "tables.empty": "尚未创建讨论桌。",
  "tables.extend": "延长 {count, number} 分钟",
  "tables.limit": "最多 {count, number} 张桌",
  "tables.mediaNote": "在讨论桌工作期间，仅同桌成员可以听到和看到您。",
  "tables.memberCount": "{count, number} 人",
  "tables.members": "同桌成员",
  "tables.nameLabel": "讨论桌名称",
  "tables.peekNotice": "教师正在巡视讨论桌",
  "tables.rejected.empty": "没有任何桌子包含成员。",
  "tables.rejected.error": "发生错误；请重试。",
  "tables.rejected.forbidden": "您没有权限执行此操作。",
  "tables.rejected.full": "此讨论桌已满员。",
  "tables.rejected.invalid": "无效请求。",
  "tables.rejected.limit": "已达到最大讨论桌数量上限。",
  "tables.rejected.noRound": "分组讨论尚未开始。",
  "tables.rejected.notFound": "该讨论桌已不存在。",
  "tables.rejected.roundActive": "分组工作进行期间无法执行此操作。",
  "tables.rejected.selectionLocked": "选桌功能已被教师锁定。",
  "tables.remaining": "剩余时间：{time}",
  "tables.rename": "重命名",
  "tables.returnAll": "全员返回",
  "tables.returnAllConfirm": "让所有人返回主课堂？",
  "tables.returned": "所有人已返回主课堂。",
  "tables.running": "分组讨论进行中",
  "tables.save": "保存",
  "tables.select.action": "选择讨论桌",
  "tables.select.full": "已满",
  "tables.select.hint": "选择一张空闲讨论桌；只要讨论桌开放，您就可以更换。",
  "tables.start": "开始分组讨论",
  "tables.stop": "结束分组讨论",
  "tables.title": "协作讨论桌"
}
