# Spanish translations for modules: report, playback
MAP_ES_4A = {
  "report.playback.open": "Reproducción interactiva",
  "report.att.ABSENT": "Ausente",
  "report.att.EXCUSED": "Justificado",
  "report.att.LATE": "Tarde",
  "report.att.NONE": "—",
  "report.att.PRESENT": "Presente",
  "report.att.absent": "Ausentes: {value, number}",
  "report.att.excused": "Justificados: {value, number}",
  "report.att.finalized": "Finalizado",
  "report.att.late": "Tarde: {value, number}",
  "report.att.present": "Presentes: {value, number}",
  "report.att.provisional": "Provisional",
  "report.att.total": "Total: {value, number}",
  "report.att.unrecorded": "Sin registrar",
  "report.attendance.noRoster": "No hay lista de inscritos disponible para esta sesión.",
  "report.attendance.noSection": "Esta sesión no está vinculada a un grupo específico; la asistencia formal solo se registra para sesiones de grupo. La lista real de participantes aparece abajo.",
  "report.attendance.title": "Asistencia",
  "report.back": "Volver al centro de sesiones",
  "report.captions.lines": "Líneas de subtítulos",
  "report.captions.linesValue": "{value, number} líneas",
  "report.captions.recording": "Grabación",
  "report.captions.soniox": "Traducción en vivo guardada",
  "report.captions.title": "Subtítulos y grabación",
  "report.chat.download": "Descargar transcripción",
  "report.chat.empty": "No se registraron mensajes en el chat público para esta sesión.",
  "report.chat.exportHead": "Registro de chat de la sesión: {title}",
  "report.chat.showAll": "Mostrar los {value, number} mensajes",
  "report.chat.showLess": "Mostrar menos",
  "report.chat.title": "Chat guardado",
  "report.chat.truncated": "Mostrando los primeros {shown, number} mensajes de {total, number} en total (límite de visualización).",
  "report.conn.direct": "Directa",
  "report.conn.nat": "Vía NAT",
  "report.conn.relay": "Vía Relay",
  "report.conn.unknown": "Desconocida",
  "report.counselor.adviseesTitle": "Mis estudiantes asesorados",
  "report.counselor.eyebrow": "Clase en vivo · Informe consolidado de la sesión",
  "report.counselor.helpBody": "Vista de asesor: estadísticas agregadas de asistencia a la sesión (sin nombres) más el estado de asistencia para estudiantes con tutoría programada contigo. El chat y las transcripciones de la clase están excluidos de esta vista.",
  "report.counselor.helpTitle": "Guía del informe para asesores",
  "report.counselor.kpiAdvisees": "Estudiantes asesorados",
  "report.counselor.kpiTotal": "Total de estudiantes",
  "report.counselor.noAdvisees": "Ninguno de tus estudiantes asesorados está inscrito en esta clase.",
  "report.counselor.privacyNotice": "Como asesor, solo tienes acceso a los registros de tus asesorados.",
  "report.counselor.title": "Informe de asistencia para asesores",
  "report.csv.attendance": "Asistencia",
  "report.csv.duration": "Duración (minutos)",
  "report.csv.email": "Correo electrónico",
  "report.csv.name": "Nombre completo",
  "report.csv.role": "Rol",
  "report.csv.status": "Estado",
  "report.downloadCsv": "Descargar CSV",
  "report.downloadPdf": "Descargar PDF",
  "report.duration": "Duración de la sesión: {duration}",
  "report.endedAt": "Finalizada el {date} a las {time}",
  "report.engagement.avgScore": "Puntuación de participación promedio",
  "report.engagement.chatCount": "Mensajes en el chat",
  "report.engagement.handCount": "Manos levantadas",
  "report.engagement.pollCount": "Respuestas a encuestas",
  "report.engagement.title": "Resumen de participación",
  "report.instructor": "Profesor: {name}",
  "report.kpi.absent": "Ausentes",
  "report.kpi.attendanceRate": "Tasa de asistencia",
  "report.kpi.avgAttention": "Atención promedio",
  "report.kpi.enrolled": "Inscritos",
  "report.kpi.excused": "Justificados",
  "report.kpi.late": "Tardanzas",
  "report.kpi.peak": "Pico de asistencia",
  "report.kpi.present": "Presentes",
  "report.kpi.totalAttendees": "Asistentes totales",
  "report.liveAnalysis.confidence": "Nivel de confianza: {value, number, ::percent}",
  "report.liveAnalysis.keyPoints": "Puntos clave tratados",
  "report.liveAnalysis.questions": "Preguntas formuladas en clase",
  "report.liveAnalysis.summary": "Resumen de la sesión generado por IA",
  "report.liveAnalysis.title": "Análisis inteligente de la sesión",
  "report.participants.colAttendance": "Estado",
  "report.participants.colDuration": "Tiempo en clase",
  "report.participants.colEmail": "Correo",
  "report.participants.colJoinTime": "Hora de ingreso",
  "report.participants.colLeaveTime": "Hora de salida",
  "report.participants.colName": "Nombre",
  "report.participants.colRole": "Rol",
  "report.participants.empty": "No hay participantes registrados.",
  "report.participants.searchPlaceholder": "Buscar participante…",
  "report.participants.title": "Lista detallada de participantes",
  "report.poll.empty": "No se realizaron encuestas en esta sesión.",
  "report.poll.results": "Resultados de la encuesta",
  "report.poll.title": "Encuestas realizadas",
  "report.poll.totalVotes": "Votos totales: {count, number}",
  "report.recording.duration": "Duración del video: {duration}",
  "report.recording.empty": "No hay grabaciones disponibles para esta sesión.",
  "report.recording.processing": "Procesando grabación…",
  "report.recording.ready": "Grabación disponible para ver",
  "report.recording.size": "Tamaño: {size}",
  "report.recording.title": "Grabación de la clase",
  "report.recording.watch": "Ver grabación",
  "report.startedAt": "Iniciada el {date} a las {time}",
  "report.title": "Informe de la sesión en vivo",
  "playback.back": "Volver al informe de sesión",
  "playback.chatTitle": "Chat de la reproducción",
  "playback.archivedChatTitle": "Chat archivado de la clase (Solo lectura)",
  "playback.replayChatTitle": "Nuevo chat de reproducción",
  "playback.replayChatMessageLabel": "Nuevo mensaje en reproducción",
  "playback.sendReplayChat": "Publicar mensaje en la marca de tiempo actual",
  "playback.replayChatHidden": "Este mensaje ha sido ocultado para otros",
  "playback.replayChatHide": "Ocultar mensaje",
  "playback.replayChatUnhide": "Mostrar mensaje",
  "playback.replayChatReportReason": "Motivo del reporte del mensaje",
  "playback.replayChatReport": "Reportar mensaje",
  "playback.replayChatUnavailable": "El chat de reproducción no está disponible o la acción no está permitida.",
  "playback.loadMoreChat": "Cargar mensajes anteriores",
  "playback.makeupTitle": "Crédito de asistencia por reproducción de recuperación",
  "playback.makeupSeparateNotice": "Este crédito se registra tras la revisión del profesor y no altera las calificaciones ni la asistencia histórica.",
  "playback.makeupSessionLabel": "ID de sesión de recuperación",
  "playback.makeupThresholdLabel": "Tiempo mínimo verificado de visualización (porcentaje)",
  "playback.makeupEnable": "Habilitar recuperación",
  "playback.makeupDisable": "Deshabilitar recuperación",
  "playback.makeupThreshold": "Tiempo mínimo requerido de visualización: {percent}%",
  "playback.makeupOpenSession": "Ir a la reproducción de la sesión de recuperación",
  "playback.makeupWatched": "Tiempo de visualización registrado por el servidor: {percent}%",
  "playback.makeupReasonLabel": "Motivo de la solicitud de recuperación",
  "playback.makeupClaim": "Enviar solicitud de revisión de recuperación",
  "playback.makeupCreditStatus": "Estado del crédito: {status}",
  "playback.makeupStudentLabel": "Estudiante",
  "playback.makeupDecisionReasonLabel": "Motivo de la decisión del docente",
  "playback.makeupConfirm": "Confirmar crédito de recuperación",
  "playback.makeupReverse": "Revertir manualmente el crédito confirmado",
  "playback.makeupUnavailable": "La acción de asistencia de recuperación no está permitida o la información no está disponible.",
  "playback.makeupStatus.pending": "Pendiente de aprobación",
  "playback.makeupStatus.confirmed": "Confirmado",
  "playback.makeupStatus.cancelled": "Cancelado",
  "playback.makeupStatus.reversed": "Revertido",
  "playback.artifactsTitle": "Archivos compartidos persistentes tras la clase",
  "playback.artifactsAudienceNotice": "Estos elementos solo son visibles para usuarios con acceso actual a este curso y grabación; las pantallas compartidas no se almacenan.",
  "playback.downloadArtifact": "Descargar archivo",
  "playback.speed": "Velocidad de reproducción",
  "playback.quality": "Calidad de video",
  "playback.fullscreen": "Pantalla completa",
  "playback.play": "Reproducir",
  "playback.pause": "Pausar",
  "playback.mute": "Silenciar",
  "playback.unmute": "Activar sonido",
  "playback.jumpBack": "Retroceder 10 segundos",
  "playback.jumpForward": "Avanzar 10 segundos",
  "playback.currentTime": "Tiempo actual",
  "playback.duration": "Duración total",
  "playback.transcriptTitle": "Transcripción interactiva",
  "playback.searchTranscript": "Buscar en la transcripción…",
  "playback.noTranscript": "No hay transcripción disponible para esta grabación."
}
