# Spanish translations for modules: analytics, breakout, guide, lobby, poll, preflight, review
MAP_ES_2 = {
  "analytics.anonymous": "Usuario",
  "analytics.attendance.absentChip": "✗ Ausente {count, number}",
  "analytics.attendance.absentLabel": "Ausente",
  "analytics.attendance.avatarFallback": "?",
  "analytics.attendance.duration": "Duración: {value}",
  "analytics.attendance.empty": "Aún no se ha registrado asistencia. Aparecerán aquí según se unan los participantes.",
  "analytics.attendance.excusedChip": "Justificado {count, number}",
  "analytics.attendance.excusedLabel": "Justificado",
  "analytics.attendance.finalized": "Finalizado",
  "analytics.attendance.inClass": "En clase",
  "analytics.attendance.joinedAt": "Entrada: {time}",
  "analytics.attendance.lateChip": "⏰ Tarde {count, number}",
  "analytics.attendance.lateLabel": "Tarde",
  "analytics.attendance.left": "Salió",
  "analytics.attendance.loading": "Cargando asistencia…",
  "analytics.attendance.neverOpened": "Esta sesión no se celebró (no hay asistencia registrada).",
  "analytics.attendance.presentChip": "✓ Presente {count, number}",
  "analytics.attendance.presentLabel": "Presente",
  "analytics.attendance.provisional": "Provisional (hasta el fin de la clase)",
  "analytics.attendance.refreshNote": "{count, number} personas · Actualización cada {seconds, number} s",
  "analytics.attendance.stillPresent": " (Actualmente en clase)",
  "analytics.attendance.title": "Lista de asistencia",
  "analytics.duration.hours": "{count, number} horas",
  "analytics.duration.hoursMinutes": "{hours, number} horas y {minutes, number} minutos",
  "analytics.duration.lessThanMinute": "Menos de 1 minuto",
  "analytics.duration.minutes": "{count, number} minutos",
  "analytics.error.attendance": "No se pudo obtener la lista de asistencia. Esta sección solo está disponible para el anfitrión.",
  "analytics.participation.aria": "Micrófonos abiertos {on, number} de {total, number}",
  "analytics.participation.empty": "Aún no hay nadie en clase.",
  "analytics.participation.muted": "Silenciados: {count, number}",
  "analytics.participation.on": "Abiertos: {count, number} ({pct, number}%)",
  "analytics.participation.title": "Participación por voz",
  "analytics.poll.active": "Hay una encuesta activa actualmente",
  "analytics.poll.idle": "No hay encuestas activas",
  "analytics.stat.chat": "Mensajes en el chat",
  "analytics.stat.hands": "Manos levantadas",
  "analytics.stat.micOn": "Micrófonos abiertos",
  "analytics.stat.present": "Presentes ahora",
  "breakout.anonymous": "Usuario",
  "breakout.decrease": "Reducir salas",
  "breakout.duration": "Duración de salas",
  "breakout.durationLabel": "Duración ({minutes, number} min)",
  "breakout.empty": "No hay participantes en la clase.",
  "breakout.endConfirm": "¿Cerrar todas las salas y devolver a todos a la clase principal?",
  "breakout.endConfirmShort": "¿Cerrar salas?",
  "breakout.ended": "Salas de grupo finalizadas.",
  "breakout.extend": "{count, number} min más",
  "breakout.increase": "Aumentar salas",
  "breakout.join": "Unirse a la sala",
  "breakout.leave": "Volver a la sala principal",
  "breakout.leaveConfirm": "¿Volver a la sala principal?",
  "breakout.memberCount": "{count, number} personas",
  "breakout.members": "Integrantes de la sala",
  "breakout.noRooms": "Aún no se han creado salas.",
  "breakout.notStarted": "El trabajo en salas no ha comenzado.",
  "breakout.remaining": "Tiempo restante: {time}",
  "breakout.roomName": "Sala {number, number}",
  "breakout.roomsActive": "{count, plural, one {# sala activa} other {# salas activas}}",
  "breakout.running": "Salas de grupo en progreso",
  "breakout.start": "Iniciar salas",
  "breakout.stop": "Cerrar salas",
  "breakout.title": "Salas para grupos pequeños",
  "breakout.unassigned": "Sin asignar ({count, number})",
  "breakout.unassignedAria": "Participantes sin asignar",
  "guide.button": "Guía de clase",
  "guide.lobby.step1": "Comprueba el micrófono y la cámara antes de entrar.",
  "guide.lobby.step2": "Revisa la calidad de tu conexión en el indicador.",
  "guide.lobby.step3": "Elige tus dispositivos en Ajustes si es necesario.",
  "guide.lobby.step4": "Pulsa \"Entrar a clase\" cuando estés listo.",
  "guide.lobby.title": "Pasos para entrar a clase",
  "guide.roles.assistant": "El asistente docente ayuda a moderar el chat y las preguntas.",
  "guide.roles.host": "El anfitrión (docente) controla las salas, encuestas y permisos.",
  "guide.roles.student": "Los estudiantes participan, levantan la mano y responden encuestas.",
  "guide.roles.title": "Roles en el aula virtual",
  "guide.title": "Guía rápida de la clase",
  "guide.welcome": "Bienvenido al aula virtual",
  "guide.youCan.chat": "Envía mensajes o dudas por escrito en la pestaña \"Chat\".",
  "guide.youCan.media": "Activa o desactiva tu cámara y micrófono desde la barra inferior.",
  "guide.youCan.recordings": "Tras finalizar la clase, podrás ver la grabación si fue registrada.",
  "guide.youCan.share": "Comparte tu pantalla si el docente te otorga permiso.",
  "guide.youCan.title": "Qué puedes hacer en clase",
  "lobby.back": "Volver al espacio de trabajo",
  "lobby.cam.off": "Apagar cámara",
  "lobby.cam.on": "Encender cámara",
  "lobby.cam.stateOff": "Cámara apagada",
  "lobby.cam.stateOn": "Cámara encendida",
  "lobby.camOffOverlay": "La cámara está apagada",
  "lobby.conn.fair": "Regular",
  "lobby.conn.good": "Buena",
  "lobby.conn.poor": "Deficiente",
  "lobby.conn.title": "Calidad de conexión",
  "lobby.conn.unknown": "Desconocida",
  "lobby.cta.blocked": "Para ingresar a la clase, debes resolver los requisitos críticos indicados arriba.",
  "lobby.cta.blockedTitle": "No puedes ingresar hasta resolver los requisitos críticos",
  "lobby.cta.enter": "Entrar a clase",
  "lobby.cta.ready": "Verifica tu video y audio antes de ingresar.",
  "lobby.cta.waiting": "El profesor aún no ha entrado; puedes ingresar y esperar.",
  "lobby.device.camera": "Cámara",
  "lobby.device.cameraNone": "No se encontró cámara",
  "lobby.device.fallback": "{device} {index, number}",
  "lobby.device.mic": "Micrófono",
  "lobby.device.micNone": "No se encontró micrófono",
  "lobby.device.speaker": "Altavoz",
  "lobby.device.speakerDefault": "Altavoz predeterminado del sistema",
  "lobby.fallbackTitle": "Clase en vivo",
  "lobby.guest": "Invitado",
  "lobby.help.body": "Antes de entrar a la clase en vivo, prueba aquí tu cámara, micrófono y altavoces. Usa los botones bajo la vista previa para activar/desactivar y selecciona tus dispositivos en la columna de ajustes. Cuando todo esté listo, pulsa \"Entrar a clase\".",
  "lobby.help.title": "Guía de acceso a clase",
  "lobby.joinMuted": "Entrar con micrófono silenciado",
  "lobby.loading": "Cargando detalles de la sesión…",
  "lobby.media.denied": "No se concedió acceso a la cámara o al micrófono.",
  "lobby.media.deniedTitle": "Acceso denegado a cámara/micrófono",
  "lobby.media.notFound": "No se encontró dispositivo de cámara o micrófono.",
  "lobby.meta.host": "Profesor: {name}",
  "lobby.meta.time": "Hora: {time}",
  "lobby.meter.label": "Nivel del micrófono",
  "lobby.meter.micOff": "El micrófono está silenciado — activa para probar.",
  "lobby.mic.off": "Silenciar micrófono",
  "lobby.mic.on": "Activar micrófono",
  "lobby.mic.stateOff": "Micrófono silenciado",
  "lobby.mic.stateOn": "Micrófono activo",
  "lobby.perm.retry": "Reintentar solicitud de permiso",
  "lobby.perm.step1": "Haz clic en el icono del candado junto a la barra de direcciones del navegador.",
  "lobby.perm.step2": "Configura los permisos de \"Cámara\" y \"Micrófono\" en \"Permitir\".",
  "lobby.perm.step3": "Luego haz clic en el botón de abajo para reintentar.",
  "lobby.perm.without": "También puedes ingresar a la clase sin cámara ni micrófono.",
  "lobby.removedByHost": "Has sido expulsado de esta clase. Solo podrás volver a ingresar con autorización del docente.",
  "lobby.removedServiceDesk": "Enviar solicitud al servicio de soporte",
  "lobby.settings.name": "Tu nombre visible en clase",
  "lobby.settings.title": "Ajustes de audio y video",
  "lobby.speaker.playing": "Reproduciendo…",
  "lobby.speaker.test": "Probar",
  "lobby.status.ended": "Esta sesión ha finalizado",
  "lobby.status.live": "En curso",
  "lobby.status.prefix": "Estado: {status}",
  "lobby.status.waiting": "El docente aún no ha ingresado",
  "poll.addOption": "Añadir opción",
  "poll.cancel": "Cancelar",
  "poll.changeHint": "Para cambiar tu voto, selecciona otra opción.",
  "poll.emptyGuest": "Actualmente no hay encuestas activas. Cuando el profesor inicie una, aparecerá aquí.",
  "poll.emptyHost": "No hay encuestas activas. Haz clic en \"Nueva encuesta\" para crear una.",
  "poll.end": "Finalizar encuesta",
  "poll.endedBadge": "Finalizada",
  "poll.finalTotal": "Resultados finales · Total {count, plural, one {# voto} other {# votos}}",
  "poll.minOptions": "Se requieren al menos {min, number} opciones no vacías para iniciar.",
  "poll.multi": "Opción múltiple",
  "poll.multiLabel": "Permitir seleccionar varias opciones (Opción múltiple)",
  "poll.new": "Nueva encuesta",
  "poll.optionN": "Opción {n, number}",
  "poll.optionTally": "{pct, number}% · {count, number}",
  "poll.optionsLabel": "Opciones ({used, number} de {max, number})",
  "poll.questionAria": "Texto de la pregunta",
  "poll.questionLabel": "Pregunta",
  "poll.questionPlaceholder": "ej., ¿Qué tema prefieres repasar?",
  "poll.removeOption": "Eliminar opción",
  "poll.single": "Opción única",
  "poll.start": "Iniciar encuesta",
  "poll.status.ended": "La encuesta ha finalizado — resultados finales.",
  "poll.status.endingWait": "Esperando confirmación de cierre de encuesta…",
  "poll.status.startFailed": "El servidor no confirmó el inicio de la encuesta. Comprueba la conexión y permisos.",
  "poll.status.started": "Encuesta iniciada — esperando respuestas…",
  "poll.status.starting": "Iniciando encuesta…",
  "poll.status.voteFailed": "No se confirmó el envío del voto; por favor inténtalo de nuevo.",
  "poll.status.voteSent": "Tu voto ha sido registrado ✓",
  "poll.status.voting": "Enviando voto…",
  "poll.status.waitingAnswers": "Esperando respuestas…",
  "poll.submitVote": "Emitir voto",
  "poll.title": "Encuesta",
  "poll.updateVote": "Cambiar voto",
  "poll.voteCount": "{count, plural, one {# voto} other {# votos}}",
  "preflight.bandwidth.detail": "Tu conexión se detectó como lenta; el video de la cámara se enviará en menor calidad para evitar cortes.",
  "preflight.bandwidth.good": "Buena",
  "preflight.bandwidth.label": "Calidad de conexión a internet",
  "preflight.bandwidth.unknown": "Desconocida",
  "preflight.bandwidth.weak": "Débil",
  "preflight.captions.available": "Disponible",
  "preflight.captions.detail": "Los subtítulos y traducción en vivo basados en voz solo funcionan en Chrome/Edge. Las demás funciones de la clase están disponibles.",
  "preflight.captions.label": "Subtítulos en vivo (opcional)",
  "preflight.captions.limited": "Limitado",
  "preflight.device.absentDetail": "No se encontró {device} activo. Revisa la conexión; aún puedes entrar a la clase sin {device}.",
  "preflight.device.absentStatus": "No encontrado",
  "preflight.device.camera": "Cámara",
  "preflight.device.deniedDetail": "Se denegó el acceso a {device}. Haz clic en el candado junto a la barra de direcciones y selecciona \"Permitir\".",
  "preflight.device.deniedStatus": "Acceso denegado",
  "preflight.device.microphone": "Micrófono",
  "preflight.device.promptDetail": "Aún no se ha otorgado permiso para {device}. Elige Permitir cuando el navegador lo solicite.",
  "preflight.device.promptStatus": "Esperando permiso",
  "preflight.device.readyStatus": "Listo",
  "preflight.panel.blocked": "No puedes ingresar a la clase hasta corregir los elementos en rojo arriba. Tras corregirlos, pulsa \"Revisar de nuevo\".",
  "preflight.panel.checking": "Comprobando…",
  "preflight.panel.regionLabel": "Comprobación de preparación de dispositivos antes de entrar",
  "preflight.panel.retry": "Revisar de nuevo",
  "preflight.panel.severity.fail": "Problema",
  "preflight.panel.severity.pass": "Listo",
  "preflight.panel.severity.warn": "Aviso",
  "preflight.panel.title": "Comprobación de dispositivos",
  "preflight.screen.detail": "Tu navegador no permite compartir pantalla. Para presentar, usa Chrome, Edge o Firefox de escritorio.",
  "preflight.screen.label": "Compartir pantalla",
  "preflight.secure.bad": "No segura",
  "preflight.secure.detail": "Esta página no está abierta bajo una conexión segura (HTTPS); los navegadores solo conceden acceso a cámara y micrófono con HTTPS.",
  "preflight.secure.label": "Conexión segura (HTTPS)",
  "preflight.secure.ok": "Segura",
  "preflight.supported": "Compatible",
  "preflight.unsupported": "No compatible",
  "preflight.webrtc.detail": "Tu navegador no soporta llamadas en tiempo real (WebRTC). Usa una versión actualizada de Chrome, Edge o Firefox.",
  "preflight.webrtc.label": "Soporte de videollamadas (WebRTC)",
  "review.actionFailed": "No se pudo realizar esta acción; por favor inténtalo de nuevo.",
  "review.approveMakeup": "Aprobar horario de recuperación",
  "review.confirmNotHeld": "Confirmar clase no celebrada",
  "review.end": "Fin propuesto",
  "review.fileReport": "Enviar informe",
  "review.makeup.approved": "Solicitud de recuperación aprobada",
  "review.makeup.rejected": "Solicitud de recuperación rechazada",
  "review.makeupRequested": "Horario de recuperación solicitado",
  "review.makeupScheduled": "La clase de recuperación ha sido programada; su realización aún no está confirmada.",
  "review.notHeld.confirmed": "Confirmado: clase no celebrada",
  "review.notHeld.rejected": "Informe de clase no celebrada rechazado",
  "review.pendingDecision": "La justificación de ausencia ha sido registrada y el caso está pendiente de resolución.",
  "review.reason": "Descripción y motivo (al menos 10 caracteres)",
  "review.rejectMakeup": "Rechazar solicitud de recuperación",
  "review.rejectNotHeld": "Rechazar informe de no celebración",
  "review.reportReceived": "Informe recibido",
  "review.reviewerMissing": "No hay responsable académico asignado a la facultad; el expediente permanece abierto.",
  "review.separateDecision": "La recepción del informe no confirma que la clase no se haya celebrado. La decisión corresponde a la dirección académica de la facultad.",
  "review.start": "Inicio propuesto",
  "review.submitMakeup": "Enviar solicitud de recuperación",
  "review.title": "Expediente de revisión académica"
}
