# Spanish translations for final 193 keys
MAP_ES_FINAL = {
  "classes.lead": "Consulta las sesiones en vivo, próximas y pasadas; entra a la sala de espera para probar cámara y micrófono o únete directamente si la sesión está en curso.",
  "classes.loading": "Cargando sesiones…",
  "classes.new": "Nueva sesión",
  "classes.noCourse": "Sin curso asociado",
  "classes.policy.enrolled": "Solo estudiantes inscritos",
  "classes.policy.invite": "Solo por invitación",
  "classes.policy.public": "Abierta a todos (Pública)",
  "classes.schedule.at": "{date} · {clock}",
  "classes.schedule.unknown": "Horario no especificado",
  "classes.title": "Clases en vivo",
  "guide.lobby.chain.check": "Aquí pruebas tu nombre, cámara y micrófono y completas la lista de preparación.",
  "guide.lobby.chain.join": "Al entrar a la clase, se te transfiere a la sala en vivo; la guía continúa allí.",
  "guide.lobby.chain.schedule": "La clase en vivo se programa en el plan de estudios y aparece en \"Mis clases\".",
  "report.noName": "Sin título",
  "report.parent.childrenTitle": "Asistencia de hijos",
  "report.parent.eyebrow": "Clase en vivo · Informe de asistencia de hijos",
  "report.parent.helpBody": "Según la matriz de acceso, el informe solo muestra el resumen de asistencia de tus hijos; el chat y las transcripciones no son visibles para los padres.",
  "report.parent.helpTitle": "Guía del informe para padres",
  "report.parent.kpiChildren": "Hijo vinculado a esta sesión",
  "report.parent.noChildren": "Ninguno de tus hijos está asociado con esta sesión.",
  "report.poll.ended": "Finalizada",
  "report.poll.multi": " · Opción múltiple",
  "report.poll.open": "Abierta",
  "report.poll.total": "Votos totales: {value, number}",
  "report.recording.none": "No disponible",
  "report.recording.play": "Reproducir grabación",
  "report.self.attendanceTitle": "Mi asistencia",
  "report.self.eyebrow": "Clase en vivo · Tu informe de esta sesión",
  "report.self.firstJoin": "Primer ingreso:",
  "report.self.helpBody": "Este es tu informe personal de la sesión: tu propia asistencia, chat público, intervenciones registradas y contenido público (encuestas y reacciones).",
  "report.self.helpTitle": "Guía de tu informe personal",
  "report.self.joinsLabel": "Conexiones a clase:",
  "report.self.minutesLabel": "Tu permanencia:",
  "report.self.myTranscript": "Mis intervenciones de voz",
  "report.self.myTranscriptEmpty": "No se registraron intervenciones de voz tuyas.",
  "report.self.reactionsTitle": "Tus reacciones",
  "report.self.reactionsTotal": "Reacciones enviadas: {value, number}",
  "report.self.recordingTitle": "Grabación de la sesión",
  "report.table.conn": "Conexión",
  "report.table.firstJoin": "Primer ingreso",
  "report.table.joins": "Conexiones",
  "report.table.minutes": "Duración (min)",
  "report.table.name": "Nombre",
  "report.table.status": "Estado",
  "report.timeline.breakoutClose": "Salas cerradas",
  "report.timeline.breakoutOpen": "Salas abiertas",
  "report.timeline.hand": "Mano levantada",
  "report.timeline.pollEnd": "Encuesta finalizada",
  "report.timeline.pollStart": "Encuesta iniciada",
  "report.timing.actual": "Real: {value}",
  "report.timing.late": "Tardanza: {value}",
  "report.timing.notHeld": "No celebrada",
  "report.timing.onTime": "Puntual",
  "report.timing.range": "{start} a {end}",
  "report.timing.scheduled": "Programado: {value}",
  "report.timing.title": "Horario y duración",
  "report.transcript.empty": "No hay transcripciones disponibles para esta sesión.",
  "report.transcript.title": "Transcripción de voz atribuida",
  "report.transcript.truncatedAll": "Transcripción truncada por límite de visualización.",
  "report.transcript.truncatedSpeaker": "Intervenciones adicionales no mostradas.",
  "report.transcript.utterances": "{count, number} intervenciones",
  "report.unavailable": "Informe no disponible",
  "review.requestMakeup": "Solicitar clase de recuperación",
  "session.captions.micRequired": "Se requiere micrófono para transcribir voz.",
  "session.captions.needMic": "Activa tu micrófono para utilizar subtítulos.",
  "session.captions.noNativeNoServer": "No hay reconocimiento nativo ni del servidor disponible.",
  "session.captions.recordFailed": "Error al registrar subtítulos.",
  "session.captions.unavailableHere": "Subtítulos no disponibles en este contexto.",
  "session.capset.off": "Desactivados",
  "session.capset.on": "Activados",
  "session.capset.showNames": "Mostrar nombres de hablantes",
  "session.diag.available": "Disponible",
  "session.diag.browser": "Navegador: {name}",
  "session.diag.engine": "Motor de audio/video: {engine}",
  "session.diag.engineNative": "Motor nativo WebRTC",
  "session.diag.engineNone": "Ninguno",
  "session.diag.engineServer": "Motor del servidor",
  "session.diag.hint": "Información técnica para resolución de problemas.",
  "session.diag.lastError": "Último error: {err}",
  "session.diag.level": "Nivel de audio: {value}",
  "session.diag.listening": "Escuchando señal…",
  "session.diag.mic": "Micrófono: {name}",
  "session.diag.micOff": "Micrófono apagado",
  "session.diag.micOn": "Micrófono encendido",
  "session.diag.off": "Apagado",
  "session.diag.restarts": "Reintentos: {count, number}",
  "session.diag.speech": "Voz detectada: {status}",
  "session.diag.starting": "Iniciando diagnóstico…",
  "session.diag.status": "Estado: {status}",
  "session.diag.unavailable": "Diagnóstico no disponible.",
  "session.download.formatMenu": "Elegir formato de descarga",
  "session.download.label": "Descargar recursos",
  "session.download.loading": "Preparando descarga…",
  "session.download.srt": "Subtítulos (.srt)",
  "session.download.txt": "Texto (.txt)",
  "session.download.vtt": "Subtítulos WebVTT (.vtt)",
  "session.end.confirmBody": "¿Confirmas el cierre definitivo de la sesión para todos?",
  "session.end.confirmCta": "Finalizar ahora",
  "session.end.confirmTitle": "Cierre de sesión",
  "session.end.pendingHost": "Esperando confirmación del anfitrión…",
  "session.end.pendingStudent": "El docente está finalizando la clase…",
  "session.end.undo": "Deshacer cierre",
  "session.end.undoFailed": "No se pudo deshacer el cierre.",
  "session.ended.byHost": "La sesión fue finalizada por el anfitrión.",
  "session.ended.forAll": "La clase ha concluido para todos.",
  "session.ended.redirecting": "Redirigiendo al aula…",
  "session.film.emptyHint": "Los videos de los participantes aparecerán aquí.",
  "session.film.emptyTitle": "Sin participantes con cámara",
  "session.film.regionLabel": "Cinta de videos de participantes",
  "session.fs.enterLabel": "Entrar a pantalla completa",
  "session.jitsi.loadFailed": "Error al cargar la sala de videollamada.",
  "session.jitsi.openNewTab": "Abrir en nueva pestaña",
  "session.participant": "Participante",
  "session.rec.durablePending": "Guardando copia de seguridad de la grabación…",
  "session.rec.durableServer": "Copia guardada en el servidor.",
  "session.rec.durableUnprotected": "Grabación no protegida.",
  "session.rec.recoveryAvailable": "Recuperación de grabación disponible.",
  "session.rec.recoveryOpen": "Abrir recuperación",
  "session.rec.retry": "Reintentar grabación",
  "session.rec.saveCta": "Guardar",
  "session.rec.saveFailed": "Error al guardar la grabación.",
  "session.rec.saveMeta": "Guardando metadatos…",
  "session.rec.saveTitle": "Guardar grabación",
  "session.rec.startFailed": "No se pudo iniciar la grabación.",
  "session.rec.unsupportedRecorder": "Grabador no compatible con tu navegador.",
  "session.rec.unsupportedScreen": "No se puede grabar la pantalla.",
  "session.rec.uploading": "Subiendo archivo de video…",
  "session.soniox.exportDate": "Fecha: {date}",
  "session.soniox.exportHead": "Transcripción de la sesión",
  "session.soniox.group": "Herramientas de voz",
  "session.soniox.langSep": " | ",
  "session.soniox.on": "Activado",
  "session.soniox.receiveOnly": "Solo recepción de subtítulos",
  "session.soniox.saveFallback": "Guardando respaldo de transcripción…",
  "session.soniox.stConnecting": "Conectando servicio de voz…",
  "session.soniox.stError": "Error en el servicio de voz.",
  "session.soniox.stMore": "Más opciones de transcripción",
  "session.soniox.stOn": "Voz activa",
  "session.soniox.stOnTargets": "Objetivos activos",
  "session.soniox.stPaused": "Voz pausada",
  "session.soniox.stReceiveOnly": "Modo escucha",
  "session.soniox.stReconnecting": "Reconectando voz…",
  "session.soniox.stTranscribeOnly": "Solo transcripción",
  "session.soniox.turnOn": "Activar servicio de voz",
  "session.soniox.unavailable": "Servicio de voz no disponible.",
  "session.stage.whiteboard": "Pizarra compartida en el escenario",
  "session.supervision.accept": "Aceptar supervisión",
  "session.supervision.conflict": "Conflicto en la solicitud de supervisión.",
  "session.supervision.returnFirst": "Volver a la vista inicial",
  "session.supervision.returnLobby": "Volver a la sala de espera",
  "session.tile.quality.connecting": "Conectando…",
  "session.tile.quality.fair": "Calidad regular",
  "session.tile.quality.good": "Calidad buena",
  "session.tile.quality.poor": "Calidad baja",
  "session.tile.quality.unknown": "Calidad desconocida",
  "session.toast.left": "Has salido de la clase",
  "session.toast.recStarted": "Grabación iniciada",
  "session.toast.recStopped": "Grabación detenida",
  "session.toolbar.endClass": "Finalizar clase para todos",
  "session.toolbar.endClassShort": "Finalizar clase",
  "session.toolbar.handShort": "Mano",
  "session.toolbar.langEn": "Inglés",
  "session.toolbar.langFa": "Persa",
  "session.toolbar.moreLabel": "Más herramientas",
  "session.toolbar.panel": "Abrir panel lateral",
  "session.toolbar.panelShort": "Panel",
  "session.toolbar.raiseHand": "Levantar mano",
  "session.toolbar.sendReaction": "Enviar reacción",
  "session.toolbar.shareShort": "Compartir",
  "session.topbar.recStart": "Iniciar grabación",
  "session.topbar.recStop": "Detener grabación",
  "tables.selection.close": "Cerrar selección de mesas",
  "tables.selection.open": "Abrir selección de mesas",
  "tables.select.selected": "Mesa seleccionada: {name}",
  "tables.select.title": "Seleccionar mesa de trabajo",
  "tables.startHint": "Asigna a los estudiantes a mesas y pulsa Iniciar.",
  "tables.timeUp": "El tiempo de trabajo en mesas ha terminado.",
  "tables.transcriptConsentAccept": "Aceptar transcripción en mesas",
  "tables.transcriptConsentProgress": "Procesando consentimiento…",
  "tables.transcriptConsentUnavailable": "Consentimiento no disponible.",
  "tables.transcriptConsentWithdraw": "Retirar consentimiento de transcripción",
  "tables.transcriptDurableEnabled": "Transcripción de mesas guardada.",
  "tables.transcriptQuarantined": "Transcripción en cuarentena temporal.",
  "tables.transcriptWithdrawalReason": "Motivo del retiro de consentimiento",
  "tables.visit.join": "Entrar a la mesa",
  "tables.visit.joined": "Has entrado a la mesa",
  "tables.visit.leave": "Salir de la mesa",
  "tables.visit.peek": "Observar mesa",
  "tables.visit.peeking": "Observando mesa…",
  "tables.you.assigned": "Asignado a: {name}",
  "tables.you.unassigned": "Aún no tienes mesa asignada.",
  "tables.you.waiting": "Esperando asignación de mesa…"
}
