# Simplified Chinese translations for modules: signals, reactions, pulse, hands, notes, sessionAnalysis, chat, assistant, wb, panel
MAP_ZH_1 = {
  "signals.aria.confused": "提示概念不明确",
  "signals.aria.slower": "请求教师放慢授课节奏",
  "signals.confused": "我没听懂",
  "signals.sent": "已记录",
  "signals.slower": "放慢节奏",
  "reactions.throttled": "请稍慢一点 — 您的回应互动暂时受到限制。",
  "pulse.confused": "{count, plural, other {# 人感到困惑}}",
  "pulse.slower": "{count, plural, other {# 人希望放慢节奏}}",
  "pulse.title": "课堂脉搏",
  "pulse.window": "在最近一分钟内",
  "hands.count": "{count, plural, other {# 人举手}}",
  "hands.lower": "放下手",
  "hands.lowerAll": "放下所有人的手",
  "hands.ordinal": "{count, number}",
  "hands.overflow": "{count, plural, other {还有 # 人在等待}}",
  "hands.position": "{count, plural, other {您的位次：#}}",
  "hands.title": "发言队列",
  "notes.ariaLabel": "课堂共享笔记",
  "notes.charCount": "{count, number} 个字符",
  "notes.empty": "暂未记录任何内容",
  "notes.exportLabel": "导出文本",
  "notes.exportTitle": "保存为文本文件 (.txt)",
  "notes.placeholder": "在此输入… 您的输入将实时对所有参与者可见。",
  "notes.synced": "已同步",
  "notes.syncing": "正在实时同步编辑内容",
  "notes.title": "共享笔记",
  "sessionAnalysis.confidence": "预估置信度：{value, number, ::percent}",
  "sessionAnalysis.failed": "无法完成课时分析",
  "sessionAnalysis.loading": "正在分析…",
  "sessionAnalysis.quiz": "推荐提问 ({count, number})",
  "sessionAnalysis.reviewRequired": "此结果为草稿，需要授课教师审核。",
  "sessionAnalysis.sources": "参考逐字稿摘录 ({count, number})",
  "sessionAnalysis.suggestedAnswer": "建议答案：{answer}",
  "sessionAnalysis.title": "课时分析",
  "sessionAnalysis.truncated": "此分析仅涵盖已存储的部分逐字稿；课时文本已超出处理上限。",
  "sessionAnalysis.unavailable": "实时课时分析不可用。未生成任何摘要或教学问题。",
  "chat.anonymousAuthor": "用户",
  "chat.channels.class": "全班",
  "chat.channels.staff": "教职员工",
  "chat.channels.table": "讨论桌",
  "chat.empty": "尚未发送任何消息。",
  "chat.note.class": "消息将通过全班频道实时向所有参与者公开。",
  "chat.note.locked": "聊天已被主持人锁定。仅主持人可以发送消息。",
  "chat.note.staff": "此频道仅对教师和助教可见；学生无法查看。",
  "chat.note.table": "此对话仅对同桌成员和教师可见。",
  "chat.placeholder": "输入消息…",
  "chat.placeholderLocked": "聊天已被锁定…",
  "chat.rejected.channel": "此频道不对您开放 — 您的消息未发送。",
  "chat.rejected.locked": "聊天已锁定 — 您的消息未发送。",
  "chat.send": "发送消息",
  "chat.tableTarget": "发送至讨论桌",
  "chat.unread": "{count, plural, other {#}}",
  "assistant.chip.example": "举个例子",
  "assistant.chip.practice": "生成练习题",
  "assistant.chip.quiz": "设计包含答案的简短测验",
  "assistant.chip.summarize": "总结本主题",
  "assistant.error.createSession": "创建智能助教对话失败。",
  "assistant.hostMode": "教师模式 — 提问与习题设计",
  "assistant.inputLabel": "向智能助教提问",
  "assistant.intro": "围绕课程主题提问 — 回答基于课程参考资料生成 (RAG)。",
  "assistant.introHost": " 作为授课教师，您还可以生成练习题和测验题。",
  "assistant.label": "智能助教",
  "assistant.noAnswer": "未收到回复。请再次提问。",
  "assistant.placeholder": "输入您的问题…",
  "assistant.questionCount": "{count, number} 个问题",
  "assistant.send": "发送问题",
  "assistant.sendShort": "发送",
  "assistant.sessionTitle": "在线直播课堂 — {name}",
  "assistant.source": "参考来源",
  "assistant.sources": "参考来源 ({count, number})",
  "assistant.title": "课堂智能助教",
  "assistant.typing": "正在撰写回复…",
  "wb.canvasLabel": "共享白板画布",
  "wb.clearAll": "清空全部",
  "wb.clearAllTitle": "清空全部（主持人）",
  "wb.clearConfirm": "确认清空全部",
  "wb.clearConfirmShort": "确认？",
  "wb.clearConfirmTitle": "再次点击以确认",
  "wb.colorGroup": "颜色",
  "wb.colorSwatch": "颜色 {color}",
  "wb.exportPng": "导出 PNG",
  "wb.exportPngTitle": "保存为 PNG 图片",
  "wb.hintEmpty": "白板当前为空。请选择工具并在画布上绘制。",
  "wb.hintText": "输入文字并按 Enter 放置在白板上。",
  "wb.itemCount": "{count, plural, other {白板上有 # 个元素}}",
  "wb.lock": "锁定白板",
  "wb.lockTitle": "为其他参与者锁定白板",
  "wb.lockedNotice": "白板已被主持人锁定；当前仅供查看。",
  "wb.lockedTitle": "白板已锁定 — 点击以解锁",
  "wb.redo": "重做",
  "wb.textLabel": "白板上的文字",
  "wb.textPlaceholder": "文字… (Enter 放置，Esc 取消)",
  "wb.toolbarLabel": "白板工具",
  "wb.tools.arrow": "箭头",
  "wb.tools.circle": "圆形",
  "wb.tools.eraser": "橡皮擦",
  "wb.tools.line": "直线",
  "wb.tools.pen": "画笔",
  "wb.tools.rect": "矩形",
  "wb.tools.select": "选择",
  "wb.tools.text": "文字",
  "wb.undo": "撤销",
  "wb.undoTitle": "撤销（您的最后一项操作）",
  "wb.unlock": "解锁白板",
  "wb.widthGroup": "线条粗细",
  "wb.widthOption": "粗细 {width, number}",
  "panel.close": "关闭",
  "panel.host.actionsFor": "对 {name} 的主持人操作",
  "panel.host.kick": "移除",
  "panel.host.lockChat": "锁定聊天",
  "panel.host.lowerHand": "放下手",
  "panel.host.makePresenter": "设为主讲人",
  "panel.host.mute": "静音",
  "panel.host.muteAll": "全员静音",
  "panel.host.unlockChat": "解锁聊天",
  "panel.people.note": "参与者名单实时更新。当媒体引擎连接成功后将显示视频画面。",
  "panel.tabCount": " ({count, number})",
  "panel.tabs.analytics": "分析",
  "panel.tabs.assistant": "助教",
  "panel.tabs.breakout": "分组",
  "panel.tabs.chat": "聊天",
  "panel.tabs.notes": "笔记",
  "panel.tabs.people": "参与者",
  "panel.tabs.polls": "投票",
  "panel.tabs.tables": "讨论桌",
  "panel.transcript.captionTag": "（语音）",
  "panel.transcript.download": "下载完整逐字稿 ⬇",
  "panel.transcript.fileHeader": "课堂逐字稿",
  "panel.transcript.fileSuffix": "-逐字稿.txt",
  "panel.transcript.preparing": "正在准备…",
  "panel.transcript.privateTag": "（私密）",
  "panel.transcript.regionLabel": "实时语音逐字稿"
}
