# Simplified Chinese translations for modules: analytics, breakout, guide, lobby, poll, preflight, review
MAP_ZH_2 = {
  "analytics.anonymous": "用户",
  "analytics.attendance.absentChip": "✗ 缺勤 {count, number}",
  "analytics.attendance.absentLabel": "缺勤",
  "analytics.attendance.avatarFallback": "？",
  "analytics.attendance.duration": "时长：{value}",
  "analytics.attendance.empty": "暂无考勤记录。随着参与者加入，将在此处显示。",
  "analytics.attendance.excusedChip": "请假 {count, number}",
  "analytics.attendance.excusedLabel": "请假",
  "analytics.attendance.finalized": "已定稿",
  "analytics.attendance.inClass": "在课",
  "analytics.attendance.joinedAt": "进入时间：{time}",
  "analytics.attendance.lateChip": "⏰ 迟到 {count, number}",
  "analytics.attendance.lateLabel": "迟到",
  "analytics.attendance.left": "已离开",
  "analytics.attendance.loading": "正在加载考勤…",
  "analytics.attendance.neverOpened": "本次课时未举行（未记录考勤）。",
  "analytics.attendance.presentChip": "✓ 出勤 {count, number}",
  "analytics.attendance.presentLabel": "出勤",
  "analytics.attendance.provisional": "临时（直到下课）",
  "analytics.attendance.refreshNote": "{count, number} 人 · 每 {seconds, number} 秒更新",
  "analytics.attendance.stillPresent": "（当前在课）",
  "analytics.attendance.title": "考勤名单",
  "analytics.duration.hours": "{count, number} 小时",
  "analytics.duration.hoursMinutes": "{hours, number} 小时 {minutes, number} 分钟",
  "analytics.duration.lessThanMinute": "不足 1 分钟",
  "analytics.duration.minutes": "{count, number} 分钟",
  "analytics.error.attendance": "无法获取考勤名单。此部分仅对主持人开放。",
  "analytics.participation.aria": "开启麦克风 {on, number} / {total, number}",
  "analytics.participation.empty": "教室中尚无人员。",
  "analytics.participation.muted": "静音：{count, number}",
  "analytics.participation.on": "已开启：{count, number} ({pct, number}%)",
  "analytics.participation.title": "语音参与度",
  "analytics.poll.active": "当前有进行中的投票",
  "analytics.poll.idle": "暂无活动投票",
  "analytics.stat.chat": "聊天消息",
  "analytics.stat.hands": "举手发言",
  "analytics.stat.micOn": "麦克风已开",
  "analytics.stat.present": "当前在课",
  "breakout.anonymous": "用户",
  "breakout.decrease": "减少讨论室",
  "breakout.duration": "讨论室时长",
  "breakout.durationLabel": "时长 ({minutes, number} 分钟)",
  "breakout.empty": "课堂中暂无参与者。",
  "breakout.endConfirm": "关闭所有讨论室并将所有人返回主课堂？",
  "breakout.endConfirmShort": "关闭讨论室？",
  "breakout.ended": "分组讨论已结束。",
  "breakout.extend": "延长 {count, number} 分钟",
  "breakout.increase": "增加讨论室",
  "breakout.join": "进入讨论室",
  "breakout.leave": "返回主课堂",
  "breakout.leaveConfirm": "确定要返回主课堂吗？",
  "breakout.memberCount": "{count, number} 人",
  "breakout.members": "讨论室成员",
  "breakout.noRooms": "尚未创建讨论室。",
  "breakout.notStarted": "分组讨论尚未开始。",
  "breakout.remaining": "剩余时间：{time}",
  "breakout.roomName": "讨论室 {number, number}",
  "breakout.roomsActive": "{count, plural, other {# 个活动讨论室}}",
  "breakout.running": "分组讨论进行中",
  "breakout.start": "开始分组讨论",
  "breakout.stop": "结束分组讨论",
  "breakout.title": "分组讨论室",
  "breakout.unassigned": "未分配 ({count, number})",
  "breakout.unassignedAria": "未分配的参与者",
  "guide.button": "课堂指南",
  "guide.lobby.step1": "进入前检查麦克风与摄像头。",
  "guide.lobby.step2": "在连接质量指示器上查看网络状态。",
  "guide.lobby.step3": "如有需要，在设置栏中选择您的设备。",
  "guide.lobby.step4": "准备就绪后点击“进入课堂”。",
  "guide.lobby.title": "进课步骤指南",
  "guide.roles.assistant": "助教协助管理聊天和提问互动。",
  "guide.roles.host": "主持人（教师）控制讨论室、投票及课堂权限。",
  "guide.roles.student": "学生参与互动、举手提问并参与投票。",
  "guide.roles.title": "在线课堂角色",
  "guide.title": "课堂快速指南",
  "guide.welcome": "欢迎进入在线直播课堂",
  "guide.youCan.chat": "在“聊天”标签页中发送文字消息或提问。",
  "guide.youCan.media": "通过底部控制栏开启或关闭摄像头与麦克风。",
  "guide.youCan.recordings": "课程结束后，若已录制，可在“录像”中观看回放。",
  "guide.youCan.share": "经主持人允许后，可共享您的屏幕。",
  "guide.youCan.title": "在课堂中您可以进行的操作",
  "lobby.back": "返回工作台",
  "lobby.cam.off": "关闭摄像头",
  "lobby.cam.on": "开启摄像头",
  "lobby.cam.stateOff": "摄像头已关闭",
  "lobby.cam.stateOn": "摄像头已开启",
  "lobby.camOffOverlay": "摄像头处于关闭状态",
  "lobby.conn.fair": "一般",
  "lobby.conn.good": "良好",
  "lobby.conn.poor": "较差",
  "lobby.conn.title": "连接质量",
  "lobby.conn.unknown": "未知",
  "lobby.cta.blocked": "要进入课堂，必须先解决上方标记的关键前提条件。",
  "lobby.cta.blockedTitle": "在解决关键前提条件前无法进入",
  "lobby.cta.enter": "进入课堂",
  "lobby.cta.ready": "请在进入前检查您的视频与音频。",
  "lobby.cta.waiting": "教师尚未进入；您可以提前进入并等候。",
  "lobby.device.camera": "摄像头",
  "lobby.device.cameraNone": "未找到摄像头",
  "lobby.device.fallback": "{device} {index, number}",
  "lobby.device.mic": "麦克风",
  "lobby.device.micNone": "未找到麦克风",
  "lobby.device.speaker": "扬声器",
  "lobby.device.speakerDefault": "系统默认扬声器",
  "lobby.fallbackTitle": "在线直播课堂",
  "lobby.guest": "访客",
  "lobby.help.body": "在进入直播课堂前，请在此测试摄像头、麦克风和扬声器。使用预览下方的按钮切换开关，并在设置栏中选择设备。全部就绪后，点击“进入课堂”。",
  "lobby.help.title": "进课指南",
  "lobby.joinMuted": "以麦克风静音状态进入",
  "lobby.loading": "正在加载课时详情…",
  "lobby.media.denied": "未授予摄像头或麦克风访问权限。",
  "lobby.media.deniedTitle": "摄像头/麦克风权限被拒绝",
  "lobby.media.notFound": "未找到摄像头或麦克风设备。",
  "lobby.meta.host": "授课教师：{name}",
  "lobby.meta.time": "时间：{time}",
  "lobby.meter.label": "麦克风音量",
  "lobby.meter.micOff": "麦克风已静音 — 取消静音以进行测试。",
  "lobby.mic.off": "静音麦克风",
  "lobby.mic.on": "开启麦克风",
  "lobby.mic.stateOff": "麦克风已静音",
  "lobby.mic.stateOn": "麦克风已激活",
  "lobby.perm.retry": "重试权限请求",
  "lobby.perm.step1": "点击浏览器地址栏旁的锁形图标。",
  "lobby.perm.step2": "将“摄像头”和“麦克风”权限设为“允许”。",
  "lobby.perm.step3": "然后点击下方按钮重试。",
  "lobby.perm.without": "您也可以在没有摄像头/麦克风的情况下进入课堂。",
  "lobby.removedByHost": "您已被移出本节课。仅在获得教师许可后方可重新加入。",
  "lobby.removedServiceDesk": "向服务台提交工单",
  "lobby.settings.name": "您在课堂中的显示名称",
  "lobby.settings.title": "音视频设置",
  "lobby.speaker.playing": "正在播放…",
  "lobby.speaker.test": "测试",
  "lobby.status.ended": "本节课已结束",
  "lobby.status.live": "正在直播",
  "lobby.status.prefix": "状态：{status}",
  "lobby.status.waiting": "教师尚未进入",
  "poll.addOption": "添加选项",
  "poll.cancel": "取消",
  "poll.changeHint": "若要修改投票，请选择其他选项。",
  "poll.emptyGuest": "当前没有正在进行的投票。当主持人发起投票时，将在此处显示。",
  "poll.emptyHost": "暂无活动投票。点击“新建投票”即可创建。",
  "poll.end": "结束投票",
  "poll.endedBadge": "已结束",
  "poll.finalTotal": "最终结果 · 共 {count, plural, other {# 票}}",
  "poll.minOptions": "至少需要 {min, number} 个非空选项方可发起。",
  "poll.multi": "多选",
  "poll.multiLabel": "允许选择多个选项（多选）",
  "poll.new": "新建投票",
  "poll.optionN": "选项 {n, number}",
  "poll.optionTally": "{pct, number}% · {count, number}",
  "poll.optionsLabel": "选项 ({used, number} / {max, number})",
  "poll.questionAria": "问题内容",
  "poll.questionLabel": "问题",
  "poll.questionPlaceholder": "例如：您倾向于讨论哪个主题？",
  "poll.removeOption": "移除选项",
  "poll.single": "单选",
  "poll.start": "发起投票",
  "poll.status.ended": "投票已结束 — 最终结果。",
  "poll.status.endingWait": "正在等待投票结束确认…",
  "poll.status.startFailed": "服务器未确认投票发起。请检查连接与主持人权限后重试。",
  "poll.status.started": "投票已发起 — 等待回应中…",
  "poll.status.starting": "正在发起投票…",
  "poll.status.voteFailed": "投票提交未被确认；请重试。",
  "poll.status.voteSent": "您的投票已提交 ✓",
  "poll.status.voting": "正在提交投票…",
  "poll.status.waitingAnswers": "等待回应中…",
  "poll.submitVote": "提交投票",
  "poll.title": "投票",
  "poll.updateVote": "修改投票",
  "poll.voteCount": "{count, plural, other {# 票}}",
  "preflight.bandwidth.detail": "检测到您的网络连接较弱；摄像头视频将以较低质量传输以避免中断。",
  "preflight.bandwidth.good": "良好",
  "preflight.bandwidth.label": "网络连接质量",
  "preflight.bandwidth.unknown": "未知",
  "preflight.bandwidth.weak": "较弱",
  "preflight.captions.available": "可用",
  "preflight.captions.detail": "基于浏览器语音识别的实时字幕与翻译仅在 Chrome/Edge 中可用。其他课堂功能依然完全可用。",
  "preflight.captions.label": "实时字幕（可选）",
  "preflight.captions.limited": "受限",
  "preflight.device.absentDetail": "未找到活动的 {device}。请检查设备连接；您仍可在没有 {device} 的情况下进入课堂。",
  "preflight.device.absentStatus": "未找到",
  "preflight.device.camera": "摄像头",
  "preflight.device.deniedDetail": "对 {device} 的访问被拒绝。点击地址栏旁的锁形图标并将“{device}”设为允许。",
  "preflight.device.deniedStatus": "访问被拒绝",
  "preflight.device.microphone": "麦克风",
  "preflight.device.promptDetail": "尚未授予 {device} 访问权限。浏览器提示时请选择允许。",
  "preflight.device.promptStatus": "等待授权",
  "preflight.device.readyStatus": "就绪",
  "preflight.panel.blocked": "在解决上方红色标记的问题之前，您无法进入课堂。解决后请点击“重新检查”。",
  "preflight.panel.checking": "正在检查…",
  "preflight.panel.regionLabel": "进课前设备就绪情况检查",
  "preflight.panel.retry": "重新检查",
  "preflight.panel.severity.fail": "问题",
  "preflight.panel.severity.pass": "就绪",
  "preflight.panel.severity.warn": "警告",
  "preflight.panel.title": "设备就绪检查",
  "preflight.screen.detail": "您的浏览器不支持屏幕共享。如需展示，请使用桌面版 Chrome、Edge 或 Firefox。",
  "preflight.screen.label": "屏幕共享",
  "preflight.secure.bad": "不安全",
  "preflight.secure.detail": "此页面未通过安全连接 (HTTPS) 打开；浏览器仅在 HTTPS 下允许访问摄像头和麦克风。",
  "preflight.secure.label": "安全连接 (HTTPS)",
  "preflight.secure.ok": "安全",
  "preflight.supported": "支持",
  "preflight.unsupported": "不支持",
  "preflight.webrtc.detail": "您的浏览器不支持实时音视频通话 (WebRTC)。请使用最新版本的 Chrome、Edge 或桌面版 Firefox。",
  "preflight.webrtc.label": "视频通话支持 (WebRTC)",
  "review.actionFailed": "无法执行此操作；请重试。",
  "review.approveMakeup": "批准补课时间",
  "review.confirmNotHeld": "确认未开课",
  "review.end": "建议结束时间",
  "review.fileReport": "提交报告",
  "review.makeup.approved": "补课申请已批准",
  "review.makeup.rejected": "补课申请已驳回",
  "review.makeupRequested": "申请的补课时间",
  "review.makeupScheduled": "补课已排定；实际开课尚待确认。",
  "review.notHeld.confirmed": "已确认未开课",
  "review.notHeld.rejected": "未开课报告已驳回",
  "review.pendingDecision": "缺勤证明已记录，案件正在等待裁决。",
  "review.reason": "情况描述与理由（至少 10 个字符）",
  "review.rejectMakeup": "驳回补课申请",
  "review.rejectNotHeld": "驳回未开课报告",
  "review.reportReceived": "报告已收到",
  "review.reviewerMissing": "院系尚未指派教务专员；案件保持开启状态。",
  "review.separateDecision": "收到报告并不代表最终确认未开课。决定权归院系教务处所有。",
  "review.start": "建议开始时间",
  "review.submitMakeup": "提交补课申请",
  "review.title": "教务复核案件"
}
