# Spanish translations for modules: atoms, classes, tables
MAP_ES_3 = {
  "atoms.captions.etaTradeoff": "Si η es demasiado grande, la función de coste diverge; si es muy pequeña, la convergencia es lenta.",
  "atoms.captions.fasterNoisier": "Esto hace que las actualizaciones sean más rápidas pero más oscilantes.",
  "atoms.captions.lrAnswer": "Buena pregunta. Normalmente se combina con un planificador de tasa de aprendizaje o con Adam.",
  "atoms.captions.lrQuestion": "¿Profesor, cómo se selecciona la tasa de aprendizaje óptima para SGD?",
  "atoms.captions.sgdStep": "El descenso de gradiente estocástico utiliza solo una muestra por paso para calcular el gradiente.",
  "atoms.chat.seed.answer": "Claro. Supongamos θ = 0.8, gradiente = 2.4 y η = 0.1. Entonces:",
  "atoms.chat.seed.answerTime": "14:25",
  "atoms.chat.seed.ask": "¿Podría dar un ejemplo numérico de actualización de pesos en SGD?",
  "atoms.chat.seed.askTime": "14:25",
  "atoms.chat.seed.greeting": "Hola 👋 Soy el asistente inteligente de esta sesión. Puedo resumir en tiempo real, aclarar conceptos o sugerir ejercicios prácticos.",
  "atoms.chat.seed.greetingTime": "14:23",
  "atoms.people.ali.init": "A",
  "atoms.people.ali.name": "Ali R.",
  "atoms.people.arman.init": "A",
  "atoms.people.arman.name": "Armán B.",
  "atoms.people.azimi.init": "DA",
  "atoms.people.azimi.name": "Dr. Azimi",
  "atoms.people.hanieh.init": "H",
  "atoms.people.hanieh.name": "Hanieh F.",
  "atoms.people.mohsen.init": "M",
  "atoms.people.mohsen.name": "Mohsen H.",
  "atoms.people.neda.init": "N",
  "atoms.people.neda.name": "Neda Kazemi",
  "atoms.people.nima.init": "N",
  "atoms.people.nima.name": "Nima J.",
  "atoms.people.sara.init": "S",
  "atoms.people.sara.name": "Sara M.",
  "atoms.people.zahra.init": "Z",
  "atoms.people.zahra.name": "Zahra K.",
  "atoms.poll.options.adamWeighted": "Adam con ponderación de clases",
  "atoms.poll.options.rmspropWarmup": "RMSprop con calentamiento (Warm-up)",
  "atoms.poll.options.sgdMomentum": "SGD estándar con momento (Momentum)",
  "atoms.poll.question": "¿Qué método de optimización es más adecuado para entrenar redes profundas con datos desbalanceados?",
  "atoms.qa.q1.text": "Si la función de coste no es convexa, ¿converge SGD a un mínimo global?",
  "atoms.qa.q1.time": "Hace 2 minutos",
  "atoms.qa.q2.text": "¿Cuál es la diferencia práctica entre Momentum y Adam?",
  "atoms.qa.q2.time": "Hace 5 minutos",
  "atoms.qa.q3.text": "¿Qué tamaño de mini-lote se recomienda para ResNet-50?",
  "atoms.qa.q3.time": "Hace 8 minutos",
  "atoms.qa.q4.text": "¿Qué ajustes deben aplicarse a SGD para conjuntos de datos desbalanceados?",
  "atoms.qa.q4.time": "Hace 12 minutos",
  "atoms.qa.tags.adaptive": "Adaptativo",
  "atoms.qa.tags.highlight": "Destacado",
  "atoms.qa.tags.practical": "Práctico",
  "atoms.slides.compare.body": "El mini-lote equilibra la estabilidad del lote completo y la velocidad de SGD. Tamaño habitual: 32 a 256.",
  "atoms.slides.noise.body": "Las fluctuaciones aleatorias permiten escapar de mínimos locales y rendir mejor en superficies no convexas.",
  "atoms.slides.noise.title": "Por qué es útil el ruido",
  "atoms.slides.sgd.body": "En cada paso, los pesos se actualizan con una sola muestra aleatoria. Más rápido pero con más oscilación.",
  "atoms.slides.sgd.title": "Descenso de gradiente estocástico",
  "atoms.suggestions.exercise": "Generar ejercicio similar",
  "atoms.suggestions.resources": "Recursos adicionales",
  "atoms.suggestions.simpler": "Explicar de forma más sencilla",
  "atoms.suggestions.summary": "Resumen de los últimos 2 minutos",
  "atoms.tabs.assistant": "Asistente",
  "atoms.tabs.captions": "Subtítulos",
  "atoms.tabs.poll": "Encuesta",
  "atoms.tabs.questions": "Preguntas",
  "atoms.timeline.r1.label": "Repaso de la sesión anterior",
  "atoms.timeline.r1.time": "14:02",
  "atoms.timeline.r2.label": "Concepto de descenso de gradiente",
  "atoms.timeline.r2.time": "14:08",
  "atoms.timeline.r3.label": "Versión por lotes (Batch)",
  "atoms.timeline.r3.time": "14:16",
  "atoms.timeline.r4.label": "Descenso de gradiente estocástico (SGD)",
  "atoms.timeline.r4.time": "14:22",
  "atoms.timeline.r5.label": "Momentum y Adam",
  "atoms.timeline.r5.time": "14:35",
  "atoms.timeline.r6.label": "Ejercicio interactivo y preguntas",
  "atoms.timeline.r6.time": "14:45",
  "atoms.transcript.live.momentum": "Si actualizamos el aprendizaje teniendo en cuenta valores previos, se denomina Momentum.",
  "atoms.transcript.live.nesterovAnswer": "Nesterov primero predice la posición siguiente y calcula el gradiente allí.",
  "atoms.transcript.live.nesterovQuestion": "¿En qué se diferencia esto de Nesterov?",
  "atoms.transcript.live.pytorchQuestion": "¿Se puede implementar esta idea en PyTorch?",
  "atoms.transcript.seed.r1.text": "En el descenso de gradiente estocástico, solo se usa una muestra para calcular el gradiente en cada paso.",
  "atoms.transcript.seed.r1.time": "14:20",
  "atoms.transcript.seed.r2.text": "Esto aumenta la velocidad de cálculo y reduce el uso de memoria.",
  "atoms.transcript.seed.r2.time": "14:21",
  "atoms.transcript.seed.r3.highlight": "Tasa de aprendizaje óptima",
  "atoms.transcript.seed.r3.text": "Profesor, ¿cómo se elige la tasa de aprendizaje óptima?",
  "atoms.transcript.seed.r3.time": "14:22",
  "atoms.transcript.seed.r4.text": "Normalmente lo combinamos con un programador de tasa de aprendizaje o algoritmos adaptativos como Adam.",
  "atoms.transcript.seed.r4.time": "14:22",
  "atoms.transcript.seed.r5.text": "¿Cuál es la diferencia clave exacta entre SGD y Mini-batch?",
  "atoms.transcript.seed.r5.time": "14:23",
  "atoms.transcript.seed.r6.text": "El tamaño del lote. En Mini-batch tomamos entre 32 y 256 muestras para un mejor equilibrio entre estabilidad y velocidad.",
  "atoms.transcript.seed.r6.time": "14:23",
  "classes.card.attendees": "{value, number} participantes",
  "classes.card.cancelled": "Esta sesión ha sido cancelada.",
  "classes.card.joinDirect": "Entrada directa",
  "classes.card.joinLobby": "Entrar a la sala de espera",
  "classes.card.newTab": "Abrir en nueva pestaña",
  "classes.card.report": "Informe de sesión",
  "classes.card.reportTitle": "Informe completo de esta sesión",
  "classes.emptyAll": "Ninguna sesión coincide con tu búsqueda.",
  "classes.emptyHint": "Tan pronto como el profesor la programe, aparecerá aquí.",
  "classes.emptySearch": "No se encontraron sesiones que coincidan con esta búsqueda o filtro.",
  "classes.errLoad": "Error al cargar las sesiones",
  "classes.eyebrow": "Clase en vivo · Centro de sesiones",
  "classes.filter.all": "Todas",
  "classes.filter.ended": "Finalizadas",
  "classes.filter.live": "En vivo ahora",
  "classes.filter.scheduled": "Programadas",
  "classes.filterAria": "Filtrar sesiones en vivo",
  "classes.form.applySlot": "Aplicar esta franja horaria",
  "classes.form.cancel": "Cancelar",
  "classes.form.close": "Cerrar",
  "classes.form.course": "Curso asociado",
  "classes.form.coursePick": "— Seleccionar curso —",
  "classes.form.courseSearch": "Buscar curso (código o nombre)…",
  "classes.form.courseSearchAria": "Buscar curso",
  "classes.form.coursesError": "La lista de cursos no está disponible; inténtalo de nuevo más tarde.",
  "classes.form.coursesLoading": "Cargando cursos…",
  "classes.form.date": "Fecha",
  "classes.form.dateAria": "Fecha de la sesión",
  "classes.form.datePlaceholder": "Seleccionar fecha de la sesión",
  "classes.form.desc": "Descripción (opcional)",
  "classes.form.descPlaceholder": "Temas o notas clave de esta sesión…",
  "classes.form.end": "Hora de finalización",
  "classes.form.errCourse": "Por favor, selecciona un curso asociado.",
  "classes.form.errCreate": "Error al crear la nueva sesión. Por favor, inténtalo de nuevo.",
  "classes.form.errDate": "Por favor, selecciona una fecha para la sesión.",
  "classes.form.errTime": "Por favor, introduce horas de inicio y fin válidas.",
  "classes.form.errTitle": "Por favor, introduce un título para la sesión.",
  "classes.form.policy": "Política de admisión",
  "classes.form.section": "Sección/Grupo (opcional)",
  "classes.form.sectionAll": "— Curso completo (sin grupo específico) —",
  "classes.form.sectionOption": "Grupo {group, number}",
  "classes.form.start": "Hora de inicio",
  "classes.form.submit": "Programar sesión",
  "classes.form.submitting": "Programando…",
  "classes.form.title": "Programar sesión de clase en vivo",
  "classes.form.titleLabel": "Título de la sesión",
  "classes.form.titlePlaceholder": "ej., Sesión 4: Algoritmos de optimización",
  "classes.heading": "Sesiones de clase en vivo",
  "classes.hostOnly": "Solo el docente o administrador puede programar sesiones.",
  "classes.myStatus.absent": "Ausente",
  "classes.myStatus.enrolled": "Inscrito",
  "classes.myStatus.excused": "Justificado",
  "classes.myStatus.present": "Presente",
  "classes.newSession": "Nueva sesión de clase",
  "classes.reload": "Recargar",
  "classes.status.cancelled": "Cancelada",
  "classes.status.ended": "Finalizada",
  "classes.status.live": "En curso",
  "classes.status.scheduled": "Programada",
  "tables.assign.balanced": "Automático (equilibrado)",
  "tables.assign.noStudents": "Aún no hay estudiantes en la clase.",
  "tables.assign.pickFor": "Mesa para {name}",
  "tables.assign.random": "Aleatorio",
  "tables.assign.title": "Asignar asientos",
  "tables.assign.unassigned": "Sin asignar",
  "tables.cancel": "Cancelar",
  "tables.capacity": "{used, number} de {total, number} personas",
  "tables.capacityLabel": "Capacidad por mesa",
  "tables.confirm": "Sí",
  "tables.countLabel": "Número de nuevas mesas",
  "tables.create": "Crear mesa",
  "tables.defaultName": "Mesa {index, number}",
  "tables.dissolve": "Disolver mesa",
  "tables.dissolveConfirm": "¿Disolver \"{name}\"? Sus miembros volverán a la clase principal.",
  "tables.duration.label": "Duración del trabajo en mesas",
  "tables.duration.option": "{count, number} minutos",
  "tables.empty": "Aún no se han creado mesas.",
  "tables.extend": "{count, number} minutos más",
  "tables.limit": "Máximo {count, number} mesas",
  "tables.mediaNote": "Durante el trabajo en mesas, solo tus compañeros de mesa te ven y te escuchan.",
  "tables.memberCount": "{count, number} personas",
  "tables.members": "Compañeros de mesa",
  "tables.nameLabel": "Nombre de la mesa",
  "tables.peekNotice": "El docente está supervisando las mesas",
  "tables.rejected.empty": "Ninguna mesa tiene miembros.",
  "tables.rejected.error": "Ocurrió un error; por favor inténtalo de nuevo.",
  "tables.rejected.forbidden": "No tienes permiso para esta acción.",
  "tables.rejected.full": "Esta mesa está llena.",
  "tables.rejected.invalid": "Solicitud no válida.",
  "tables.rejected.limit": "Has alcanzado el número máximo de mesas.",
  "tables.rejected.noRound": "El trabajo en mesas no ha comenzado.",
  "tables.rejected.notFound": "Esta mesa ya no existe.",
  "tables.rejected.roundActive": "Esta acción no se puede realizar mientras el trabajo en mesas esté activo.",
  "tables.rejected.selectionLocked": "La selección de mesa está bloqueada por el docente.",
  "tables.remaining": "Tiempo restante: {time}",
  "tables.rename": "Renombrar",
  "tables.returnAll": "Regresar a todos",
  "tables.returnAllConfirm": "¿Regresar a todos a la clase principal?",
  "tables.returned": "Todos regresaron a la clase principal.",
  "tables.running": "Trabajo en mesas en progreso",
  "tables.save": "Guardar",
  "tables.select.action": "Elegir mesa",
  "tables.select.full": "Llena",
  "tables.select.hint": "Elige una mesa libre; puedes cambiarte mientras las mesas estén abiertas.",
  "tables.start": "Iniciar mesas",
  "tables.stop": "Terminar mesas",
  "tables.title": "Mesas de trabajo colaborativo"
}
