# French translations for missing 91 session keys
MAP_FR_MISSING_91 = {
  "session.archive.btn": "Archive des transcriptions",
  "session.archive.download": "Télécharger l'archive",
  "session.archive.empty": "Aucune parole enregistrée dans l'archive pour l'instant.",
  "session.archive.error": "Échec de la récupération de l'archive.",
  "session.archive.loading": "Chargement de l'archive…",
  "session.archive.reload": "Recharger",
  "session.archive.retry": "Réessayer",
  "session.archive.short": "Archive",
  "session.archive.title": "Archive des transcriptions (Enregistrées)",
  "session.browserUnknown": "Inconnu",
  "session.capset.btn": "Paramètres des sous-titres",
  "session.capset.fontSize": "Taille de police",
  "session.capset.lg": "Grande",
  "session.capset.maxLines": "Lignes d'affichage maximales",
  "session.capset.md": "Moyenne",
  "session.capset.off": "Désactivé",
  "session.capset.on": "Activé",
  "session.capset.showNames": "Afficher les noms des intervenants",
  "session.capset.sm": "Petite",
  "session.capset.title": "Paramètres d'affichage des sous-titres",
  "session.captions.cpuSlow": "Le traitement vocal sur le processeur actuel du serveur est plus lent que le temps réel ; les sous-titres s'activeront après la mise à niveau du serveur",
  "session.captions.deviceUnsupported": "Sous-titres non pris en charge sur ce navigateur/appareil ; utilisez Safari sur iPhone ou un ordinateur",
  "session.captions.engineStuck": "Le moteur vocal du navigateur ne répond pas ; veuillez réessayer",
  "session.captions.fallbackServer": "Moteur vocal du navigateur non autorisé ; bascule vers le moteur serveur (peut être plus lent sur ce serveur)",
  "session.captions.micDenied": "Accès au microphone non accordé",
  "session.captions.micRequired": "Le microphone doit être actif pour les sous-titres",
  "session.captions.needMic": "Réactivez le micro pour activer les sous-titres",
  "session.captions.noNativeNoServer": "Votre navigateur ne dispose pas de sous-titres natifs et le service vocal serveur n'est pas actif",
  "session.captions.recordFailed": "L'enregistrement audio pour les sous-titres a échoué",
  "session.captions.unavailableHere": "Sous-titres non disponibles dans ce navigateur",
  "session.captions.unsupported": "Votre navigateur ne prend pas en charge la transcription en direct (Chrome/Edge)",
  "session.close": "Fermer",
  "session.cohost.manage": "Gérer le co-hôte temporaire",
  "session.cohost.revoke": "Révoquer le statut de co-hôte pour {name}",
  "session.cohost.revoked": "Votre accès de co-hôte a été révoqué.",
  "session.collabLoading": "Chargement…",
  "session.conn.fair": "Moyenne",
  "session.conn.good": "Bonne",
  "session.conn.poor": "Médiocre",
  "session.conn.unknown": "Inconnue",
  "session.connFoot": "Qualité de connexion : {quality} · {count, number} participants",
  "session.diag.available": "Disponible ✓",
  "session.diag.browser": "Navigateur",
  "session.diag.engine": "Moteur",
  "session.diag.engineNative": "Navigateur natif",
  "session.diag.engineNone": "❌ Aucun",
  "session.diag.engineServer": "Serveur",
  "session.diag.hint": "Si le « Niveau audio » ne bouge pas lorsque vous parlez, le navigateur ne transmet pas l'audio du microphone à la page.",
  "session.diag.lastError": "Dernière erreur",
  "session.diag.level": "Niveau audio",
  "session.diag.listening": "À l'écoute ✓",
  "session.diag.mic": "Microphone",
  "session.diag.micOff": "Désactivé ❌",
  "session.diag.micOn": "Activé ✓",
  "session.diag.off": "Désactivé",
  "session.diag.restarts": "Tentatives de démarrage",
  "session.diag.speech": "Reconnaissance vocale du navigateur",
  "session.diag.starting": "Démarrage…",
  "session.diag.status": "🛈 État des sous-titres :",
  "session.diag.unavailable": "Non disponible ❌",
  "session.download.chat": "Télécharger le chat",
  "session.download.formatMenu": "Format de téléchargement",
  "session.download.label": "Télécharger",
  "session.download.loading": "Téléchargement en cours…",
  "session.download.srt": "Sous-titres (.srt)",
  "session.download.txt": "Télécharger TXT",
  "session.download.vtt": "WebVTT (.vtt)",
  "session.end.cancel": "Annuler",
  "session.end.confirmBody": "Une fois confirmé, vous aurez 10 secondes pour annuler la fin du cours ; ensuite tous les participants seront déconnectés.",
  "session.end.confirmCta": "Terminer le cours pour tout le monde",
  "session.end.confirmTitle": "Terminer le cours pour tous les participants ?",
  "session.end.failed": "Impossible de terminer la session ; veuillez réessayer.",
  "session.end.pendingHost": "Le cours se terminera dans {seconds} secondes.",
  "session.end.pendingStudent": "L'enseignant met fin au cours.",
  "session.end.undo": "Annuler la fin du cours",
  "session.end.undoFailed": "Le délai d'annulation a expiré. Pour continuer, créez une nouvelle session.",
  "session.ended.byHost": "Cours terminé par l'enseignant",
  "session.ended.forAll": "Cours terminé pour tout le monde",
  "session.ended.redirecting": "Redirection vers la liste des cours…",
  "session.film.emptyHint": "À mesure que les participants rejoindront, leurs vignettes apparaîtront ici.",
  "session.film.emptyTitle": "Personne n'a encore rejoint le cours",
  "session.film.regionLabel": "Participants",
  "session.fs.enter": "Passer en plein écran",
  "session.fs.enterLabel": "Plein écran ⛶",
  "session.fs.exit": "Quitter le plein écran",
  "session.guest": "Invité",
  "session.jitsi.loadFailed": "Échec du chargement de la salle vidéo. Vérifiez votre connexion Internet ou le domaine Jitsi, ou utilisez le bouton ci-dessous pour ouvrir la session dans un nouvel onglet.",
  "session.kick.failed": "L'exclusion de l'étudiant est incomplète. La connexion média n'est pas encore fermée ; veuillez réessayer.",
  "session.kick.manage": "Étudiants exclus de cette session",
  "session.kick.restore": "Autoriser {name} à rejoindre à nouveau",
  "session.kick.restoreFailed": "Impossible d'enregistrer l'autorisation de retour. Veuillez réessayer."
}
