# French translations for Part 1 (146 keys)
# Modules: signals, reactions, pulse, hands, notes, chat, assistant, sessionAnalysis, review, breakout, panel

MAP_FR_1 = {
  "signals.aria.confused": "Signaler que le concept n'est pas clair",
  "signals.aria.slower": "Demander à l'enseignant de ralentir le rythme",
  "signals.confused": "Je n'ai pas compris",
  "signals.sent": "Enregistré",
  "signals.slower": "Ralentir le rythme",
  "reactions.throttled": "Ralentissez un peu — vos réactions sont temporairement limitées.",
  "pulse.confused": "{count, plural, one {# personne est perplexe} other {# personnes sont perplexes}}",
  "pulse.slower": "{count, plural, one {# personne souhaite un rythme plus lent} other {# personnes souhaitent un rythme plus lent}}",
  "pulse.title": "Pouls du cours",
  "pulse.window": "Au cours de la dernière minute",
  "hands.count": "{count, plural, one {# main levée} other {# mains levées}}",
  "hands.lower": "Baisser la main",
  "hands.lowerAll": "Baisser toutes les mains",
  "hands.ordinal": "{count, number}",
  "hands.overflow": "{count, plural, one {# autre personne attend} other {# autres personnes attendent}}",
  "hands.position": "{count, plural, one {Votre tour : #} other {Votre tour : #}}",
  "hands.title": "File d'attente des prises de parole",
  "notes.ariaLabel": "Notes partagées du cours",
  "notes.charCount": "{count, number} caractères",
  "notes.empty": "Rien n'a encore été écrit",
  "notes.exportLabel": "Exportation de texte",
  "notes.exportTitle": "Enregistrer sous forme de fichier texte (.txt)",
  "notes.placeholder": "Écrivez ici… Ce que vous écrivez est visible par tous les participants en temps réel.",
  "notes.synced": "Synchronisé",
  "notes.syncing": "Les modifications sont synchronisées en temps réel",
  "notes.title": "Notes partagées",
  "chat.anonymousAuthor": "Utilisateur",
  "chat.channels.class": "Cours",
  "chat.channels.staff": "Équipe pédagogique",
  "chat.channels.table": "Table",
  "chat.empty": "Aucun message envoyé pour le moment.",
  "chat.note.class": "Les messages sont partagés en direct avec tous les participants via le canal du cours.",
  "chat.note.locked": "Le chat a été verrouillé par l'hôte. Seul l'hôte peut envoyer des messages.",
  "chat.note.staff": "Ce canal est visible uniquement par l'enseignant et les assistants ; les étudiants ne peuvent pas le voir.",
  "chat.note.table": "Cette conversation n'est visible que par les personnes à votre table et les enseignants.",
  "chat.placeholder": "Écrivez un message…",
  "chat.placeholderLocked": "Le chat est verrouillé…",
  "chat.rejected.channel": "Ce canal ne vous est pas ouvert — votre message n'a pas été envoyé.",
  "chat.rejected.locked": "Le chat est verrouillé — votre message n'a pas été envoyé.",
  "chat.send": "Envoyer le message",
  "chat.tableTarget": "Envoyer à la table",
  "chat.unread": "{count, plural, one {#} other {#}}",
  "assistant.chip.example": "Donner un exemple",
  "assistant.chip.practice": "Créer une question d'entraînement",
  "assistant.chip.quiz": "Concevoir un court quiz avec réponses",
  "assistant.chip.summarize": "Résumer ce sujet",
  "assistant.error.createSession": "Échec de la création de la conversation avec l'assistant.",
  "assistant.hostMode": "Mode enseignant — Conception de questions et d'exercices",
  "assistant.inputLabel": "Poser une question à l'assistant intelligent",
  "assistant.intro": "Posez vos questions sur le sujet du cours — les réponses s'appuient sur les supports de cours (RAG).",
  "assistant.introHost": " En tant qu'enseignant, vous pouvez également générer des exercices et des quiz.",
  "assistant.label": "Assistant intelligent",
  "assistant.noAnswer": "Aucune réponse reçue. Veuillez poser votre question à nouveau.",
  "assistant.placeholder": "Saisissez votre question…",
  "assistant.questionCount": "{count, number} questions",
  "assistant.send": "Envoyer la question",
  "assistant.sendShort": "Envoyer",
  "assistant.sessionTitle": "Cours en direct — {name}",
  "assistant.source": "Source",
  "assistant.sources": "Sources ({count, number})",
  "assistant.title": "Assistant intelligent du cours",
  "assistant.typing": "Rédaction de la réponse…",
  "sessionAnalysis.title": "Analyse de la session",
  "sessionAnalysis.loading": "Analyse en cours…",
  "sessionAnalysis.failed": "L'analyse de la session n'a pas pu être effectuée",
  "sessionAnalysis.reviewRequired": "Cette sortie est un brouillon et nécessite la révision de l'enseignant.",
  "sessionAnalysis.confidence": "Confiance estimée : {value, number, ::percent}",
  "sessionAnalysis.unavailable": "L'analyse de la session en direct n'est pas disponible. Aucun résumé ni question pédagogique n'a été généré.",
  "sessionAnalysis.truncated": "Cette analyse ne couvre qu'une partie de la transcription enregistrée ; le texte de la session dépasse la limite de traitement.",
  "sessionAnalysis.quiz": "Questions suggérées ({count, number})",
  "sessionAnalysis.suggestedAnswer": "Réponse suggérée : {answer}",
  "sessionAnalysis.sources": "Extraits de transcription de référence ({count, number})",
  "review.title": "Dossier d'évaluation académique",
  "review.separateDecision": "La réception d'un signalement ne confirme pas que le cours n'a pas eu lieu. La décision incombe au responsable pédagogique.",
  "review.pendingDecision": "Les preuves d'absence ont été enregistrées et le dossier est en attente de décision.",
  "review.reportReceived": "Signalement reçu",
  "review.reviewerMissing": "Aucun responsable pédagogique assigné ; le dossier reste ouvert.",
  "review.reason": "Description et motif (au moins 10 caractères)",
  "review.fileReport": "Soumettre le signalement",
  "review.confirmNotHeld": "Confirmer le cours non tenu",
  "review.rejectNotHeld": "Rejeter le signalement de cours non tenu",
  "review.requestMakeup": "Demander une session de rattrapage",
  "review.start": "Début proposé",
  "review.end": "Fin proposée",
  "review.submitMakeup": "Soumettre la demande de rattrapage",
  "review.makeupRequested": "Créneau de rattrapage demandé",
  "review.approveMakeup": "Approuver le créneau de rattrapage",
  "review.rejectMakeup": "Rejeter la demande de rattrapage",
  "review.makeupScheduled": "La session de rattrapage a été planifiée ; sa tenue n'est pas encore confirmée.",
  "review.notHeld.confirmed": "Non-tenue confirmée",
  "review.notHeld.rejected": "Signalement de non-tenue rejeté",
  "review.makeup.approved": "Demande de rattrapage approuvée",
  "review.makeup.rejected": "Demande de rattrapage rejetée",
  "review.actionFailed": "Impossible d'effectuer cette action ; veuillez réessayer.",
  "breakout.anonymous": "Utilisateur",
  "breakout.decrease": "Réduire le nombre de salles",
  "breakout.duration": "Durée : {count, number} minutes",
  "breakout.durationLabel": "Durée (minutes)",
  "breakout.empty": "Vide",
  "breakout.end": "Terminer",
  "breakout.increase": "Ajouter une salle",
  "breakout.manualLabel": "Attribution manuelle",
  "breakout.maxRooms": "Maximum {count, number} salles",
  "breakout.memberCount": "{count, number} personnes",
  "breakout.mode.auto": "Automatique",
  "breakout.mode.manual": "Manuel",
  "breakout.mode.random": "Aléatoire",
  "breakout.modeLabel": "Méthode d'attribution",
  "breakout.moved": "Vous avez été déplacé dans cette salle",
  "breakout.noParticipants": "Aucun participant dans le cours pour l'instant. Vous pourrez les attribuer dès qu'ils rejoindront.",
  "breakout.noneOpen": "Aucune salle de sous-commission active. Lorsque l'hôte ouvrira des salles, la vôtre apparaîtra ici.",
  "breakout.open": "Ouvrir les salles",
  "breakout.phaseNote": "À cette étape, l'attribution des participants ainsi que le chat et les notes par salle sont actifs. L'audio et la vidéo séparés par salle nécessitent une infrastructure média (SFU, Étape 3) et sont actuellement en dehors de cette section.",
  "breakout.preview": "{people, number} participants seront répartis dans {rooms, number} salles (environ {per, number} personnes par salle).",
  "breakout.roomCountLabel": "Nombre de salles",
  "breakout.roomFor": "Salle pour {name}",
  "breakout.roomName": "Salle {index, number}",
  "breakout.title": "Salles de sous-commission",
  "breakout.unassigned": "Vous n'avez pas encore été assigné à une salle. Veuillez attendre l'hôte.",
  "breakout.you": "Vous",
  "panel.close": "Fermer",
  "panel.host.actionsFor": "Actions de l'hôte pour {name}",
  "panel.host.kick": "Exclure",
  "panel.host.lockChat": "Verrouiller le chat",
  "panel.host.lowerHand": "Baisser la main",
  "panel.host.makePresenter": "Nommer présentateur",
  "panel.host.mute": "Couper le micro",
  "panel.host.muteAll": "Couper tous les micros",
  "panel.host.unlockChat": "Déverrouiller le chat",
  "panel.people.note": "La liste des participants se met à jour en temps réel. Les flux vidéo apparaîtront dès que le moteur multimédia en direct sera connecté.",
  "panel.tabCount": " ({count, number})",
  "panel.tabs.analytics": "Analyses",
  "panel.tabs.assistant": "Assistant",
  "panel.tabs.breakout": "Salles de groupe",
  "panel.tabs.chat": "Chat",
  "panel.tabs.notes": "Notes",
  "panel.tabs.people": "Participants",
  "panel.tabs.polls": "Sondages",
  "panel.tabs.tables": "Tables",
  "panel.transcript.captionTag": " (Parole)",
  "panel.transcript.download": "Télécharger la transcription intégrale ⬇",
  "panel.transcript.fileHeader": "Transcription du cours",
  "panel.transcript.fileSuffix": "-transcription.txt",
  "panel.transcript.preparing": "Préparation…",
  "panel.transcript.privateTag": " (Privé)",
  "panel.transcript.regionLabel": "Transcription de la parole en direct"
}
