# Part 2B of en live.json: playback, report
PART2B = {
  "playback": {
    "back": "Back to session report",
    "chatTitle": "Public Replay Chat",
    "archivedChatTitle": "Archived Live Chat (Read-only)",
    "replayChatTitle": "New Replay Chat",
    "replayChatMessageLabel": "New replay message",
    "sendReplayChat": "Post message at current timestamp",
    "replayChatHidden": "This message has been hidden from others",
    "replayChatHide": "Hide message",
    "replayChatUnhide": "Unhide message",
    "replayChatReportReason": "Reason for reporting message",
    "replayChatReport": "Report message",
    "replayChatUnavailable": "Replay chat is not available or action is not permitted.",
    "loadMoreChat": "Load older messages",
    "makeupTitle": "Replay Make-up Attendance Credit",
    "makeupSeparateNotice": "This credit is recorded following instructor review and does not alter historical attendance or grades.",
    "makeupSessionLabel": "Make-up session ID",
    "makeupThresholdLabel": "Minimum verified watch time (percentage)",
    "makeupEnable": "Enable make-up",
    "makeupDisable": "Disable make-up",
    "makeupThreshold": "Required minimum watch time: {percent}%",
    "makeupOpenSession": "Go to make-up session replay",
    "makeupWatched": "Server-recorded watch time: {percent}%",
    "makeupReasonLabel": "Reason for make-up request",
    "makeupClaim": "Submit make-up review request",
    "makeupCreditStatus": "Credit status: {status}",
    "makeupStudentLabel": "Student",
    "makeupDecisionReasonLabel": "Instructor decision reason",
    "makeupConfirm": "Confirm make-up credit",
    "makeupReverse": "Manually reverse confirmed credit",
    "makeupUnavailable": "Make-up attendance action is not permitted or information is unavailable.",
    "makeupStatus": {
      "pending": "Pending approval",
      "confirmed": "Confirmed",
      "cancelled": "Cancelled",
      "reversed": "Reversed"
    },
    "artifactsTitle": "Post-class Persistent Shared Items",
    "artifactsAudienceNotice": "These items are only visible to users with current access to this course and recording; screen shares are not saved.",
    "artifactsEnableLearners": "Enable learner contributions",
    "artifactsDisableLearners": "Disable learner contributions",
    "artifactKindLabel": "Content type",
    "artifactTitleLabel": "Title",
    "artifactWhiteboardLabel": "Whiteboard textual snapshot",
    "artifactDocumentLabel": "Course document ID",
    "artifactCreate": "Save shared item",
    "artifactApprove": "Approve publication",
    "artifactHide": "Hide",
    "artifactUnavailable": "Saving or managing this shared item is not permitted.",
    "artifactKind": {
      "pdf": "PDF",
      "whiteboard": "Whiteboard",
      "file_pin": "Pinned file"
    },
    "artifactStatus": {
      "pending": "Awaiting instructor approval",
      "published": "Published",
      "hidden": "Hidden"
    },
    "notesTitle": "My Timestamped Notes",
    "noteLabel": "Note text",
    "addNote": "Add note at current time",
    "saveNote": "Save edit",
    "editNote": "Edit",
    "deleteNote": "Delete",
    "seekNote": "Jump to note timestamp",
    "questionsTitle": "Replay Questions",
    "questionLabel": "Timestamped question",
    "askQuestion": "Submit question",
    "questionPublished": "Published for class",
    "questionOptIn": "Consent to publish",
    "questionOptOut": "Withdraw publication consent",
    "questionApprove": "Approve publication",
    "questionUnpublish": "Unpublish",
    "answerLabel": "Official answer",
    "answerQuestion": "Submit answer",
    "roomTitle": "Group Watch Room",
    "createRoom": "Create private room",
    "roomIdLabel": "Room ID",
    "joinRoom": "Join room",
    "roomUserLabel": "User ID",
    "inviteRoom": "Invite",
    "offerHandover": "Offer control handover",
    "acceptHandover": "Accept handover",
    "removeMember": "Remove from room",
    "closeRoom": "Close room",
    "roomPlay": "Play for all",
    "roomPause": "Pause for all",
    "roomSeek": "Seek group playback to selected time",
    "roomUnavailable": "Room is unavailable or you lack required permissions.",
    "roomWaiting": "Waiting for room connection…",
    "questionUnavailable": "This action is not permitted or the question is no longer available.",
    "questionHide": "Hide question",
    "questionUnhide": "Unhide question",
    "questionHidden": "Hidden from class",
    "questionReportReason": "Reason for reporting question",
    "questionReport": "Report question",
    "eyebrow": "Interactive Replay",
    "loading": "Preparing replay…",
    "jump": "Jump to this event",
    "jumpToPoll": "Jump to poll {question}",
    "jumpToTableStart": "Jump to table activity start",
    "jumpToTranscript": "Jump to this transcript timestamp",
    "speedLabel": "Playback speed",
    "watchedProgress": "Playback watched on this device: {percent}%",
    "serverWatchEvidence": "Server-recorded progress: {percent}%.",
    "notAttendanceCredit": "This value alone does not constitute attendance credit.",
    "fullscreen": "Fullscreen",
    "captionsLabel": "Session captions",
    "showCaptions": "Show captions",
    "hideCaptions": "Hide captions",
    "me": "Me",
    "noMatches": "No text found matching your search.",
    "noRecording": "No playback recording is available for this session.",
    "open": "Interactive Replay",
    "pollsTitle": "Recorded Polls",
    "pollNotReached": "To answer, first reach this poll's timestamp in the replay.",
    "pollAnswerFailed": "Could not record replay answer; please try again.",
    "searchLabel": "Search transcript",
    "searchPlaceholder": "Search session speech…",
    "searchLoading": "Searching transcript…",
    "searchUnavailable": "Transcript search is not permitted or temporarily unavailable.",
    "loadMoreResults": "Show more results",
    "table": "Table {id}",
    "timelineLabel": "Replay event timeline",
    "transcriptTitle": "Searchable Transcript",
    "downloadTranscript": "Download transcript",
    "transcriptDownloadUnavailable": "Transcript download is not permitted or temporarily unavailable.",
    "unavailable": "Replay for this session is unavailable."
  },
  "report": {
    "playback": {
      "open": "Interactive Replay"
    },
    "att": {
      "ABSENT": "Absent",
      "EXCUSED": "Excused",
      "LATE": "Late",
      "NONE": "—",
      "PRESENT": "Present",
      "absent": "Absent: {value, number}",
      "excused": "Excused: {value, number}",
      "finalized": "Finalized",
      "late": "Late: {value, number}",
      "present": "Present: {value, number}",
      "provisional": "Provisional",
      "total": "Total: {value, number}",
      "unrecorded": "Unrecorded"
    },
    "attendance": {
      "noRoster": "No enrolled roster available for this session.",
      "noSection": "This session is not linked to a specific class/group; formal attendance is only recorded for section-based sessions. Actual participant list appears below.",
      "title": "Attendance"
    },
    "back": "Back to session hub",
    "captions": {
      "lines": "Caption lines",
      "linesValue": "{value, number} lines",
      "recording": "Recording",
      "soniox": "Stored live translation",
      "title": "Captions & Recording"
    },
    "chat": {
      "download": "Download transcript",
      "empty": "No messages were recorded in the public chat for this session.",
      "exportHead": "Session Chat Log: {title}",
      "showAll": "Show all {value, number} messages",
      "showLess": "Show less",
      "title": "Saved Chat",
      "truncated": "Showing first {shown, number} messages of {total, number} total (display limit)."
    },
    "conn": {
      "direct": "Direct",
      "nat": "Via NAT",
      "relay": "Via Relay",
      "unknown": "Unknown"
    },
    "counselor": {
      "adviseesTitle": "My Advised Students",
      "eyebrow": "Live Class · Consolidated Session Report",
      "helpBody": "Advisor view: Aggregate session attendance stats (without names) plus attendance status for students with scheduled advising with you. Class chat and transcripts are excluded from this view.",
      "helpTitle": "Advisor Report Guide",
      "kpiAdvisees": "Advised Students",
      "kpiTotal": "Total Students",
      "noAdvisees": "None of your advised students are associated with this session.",
      "statsTitle": "Session Attendance Stats"
    },
    "engagement": {
      "hands": "Hands raised:",
      "pollVotes": "Poll votes:",
      "reactions": "Reactions:",
      "title": "Engagement & Interaction"
    },
    "errLoad": "Failed to load session report.",
    "full": {
      "eyebrow": "Live Class · Session Report",
      "helpBody": "This report displays all persistent data of a live class session in one place: actual timing and duration, student attendance, participant list, saved chat, speaker-attributed speech transcript, live polls, reactions, and recording status. Interactive artifacts are only saved when closed by the host using \"End Session\".",
      "helpTitle": "Session Report Guide"
    },
    "hostSuffix": " (Host)",
    "kpi": {
      "attendanceRate": "Attendance Rate",
      "duration": "Actual Duration",
      "enrolled": "Enrolled Students",
      "present": "Total Attendees",
      "scheduled": "Scheduled Time"
    },
    "loading": "Loading session report…",
    "minutes": "{value, number} min",
    "neverOpened": "This session was not held (no host entry recorded).",
    "noCourse": "General Session",
    "noName": "Untitled",
    "parent": {
      "childrenTitle": "Child(ren) Attendance",
      "eyebrow": "Live Class · Child Attendance Report",
      "helpBody": "Per the access matrix, the session report only displays an attendance summary for your child(ren); class chat and speech transcripts are not visible to parents.",
      "helpTitle": "Parent Report Guide",
      "kpiChildren": "Child linked to this session",
      "noChildren": "None of your children are associated with this session."
    },
    "participants": {
      "empty": "No one joined this session.",
      "title": "Participants"
    },
    "poll": {
      "title": "Poll #{index, number}: {question}"
    },
    "polls": {
      "title": "Polls"
    },
    "recording": {
      "duration": " · {duration}",
      "none": "Not available",
      "play": "Play recording",
      "processing": "Processing…"
    },
    "self": {
      "attendanceTitle": "My Attendance",
      "eyebrow": "Live Class · Your Report for this Session",
      "firstJoin": "First joined:",
      "helpBody": "This is your personal session report: your own attendance, public chat, your recorded utterances, and public session content (polls and reactions). Other students' information is only shown to the instructor and authorized staff.",
      "helpTitle": "Personal Report Guide",
      "joinsLabel": "Join count:",
      "minutesLabel": "Attendance time:",
      "myTranscript": "My Utterances",
      "myTranscriptEmpty": "No speech recorded from you in this session (live captions/translation was not active or you did not speak).",
      "reactionsTitle": "Session Reactions",
      "reactionsTotal": "Total: {value, number}",
      "recordingTitle": "Session Recording"
    },
    "table": {
      "conn": "Connection Type",
      "firstJoin": "First Joined",
      "joins": "Join Count",
      "minutes": "Duration",
      "name": "Name",
      "status": "Status"
    },
    "timeline": {
      "breakoutClose": "Close breakout rooms",
      "breakoutOpen": "Open breakout rooms",
      "hand": "Hand raised",
      "pollEnd": "End poll",
      "pollStart": "Start poll"
    },
    "timing": {
      "actual": "Actual Session",
      "late": "Started {value, number} minutes late",
      "notHeld": "Not held",
      "onTime": "Started on time",
      "range": "{start} to {end}",
      "scheduled": "Scheduled",
      "title": "Timing"
    },
    "transcript": {
      "empty": "No speech recorded for this session (live captions or translation was not active during the session).",
      "title": "Speech Transcript by Speaker",
      "truncatedAll": "Part of the transcript was omitted due to loading limits (counters are exact).",
      "truncatedSpeaker": "Showing first {shown, number} utterances of {total, number} (display limit).",
      "utterances": "{value, number} utterances"
    },
    "unavailable": "Session report is currently unavailable."
  }
}
