# French translations for Part 3 (228 keys)
# Modules: atoms, classes, tables

MAP_FR_3 = {
  "atoms.captions.etaTradeoff": "Si η est trop grand, la fonction de coût diverge ; s'il est trop petit, la convergence est lente.",
  "atoms.captions.fasterNoisier": "Cela permet des mises à jour plus rapides mais avec davantage d'oscillations.",
  "atoms.captions.lrAnswer": "Bonne question. Nous l'associons généralement à un programmateur de taux d'apprentissage ou à Adam.",
  "atoms.captions.lrQuestion": "Professeur, comment choisit-on le taux d'apprentissage optimal pour la SGD ?",
  "atoms.captions.sgdStep": "La descente de gradient stochastique n'utilise qu'un seul échantillon par étape pour calculer le gradient.",
  "atoms.chat.seed.answer": "Bien sûr. Supposons θ = 0.8, gradient = 2.4 et η = 0.1. Alors :",
  "atoms.chat.seed.answerTime": "14:25",
  "atoms.chat.seed.ask": "Pouvez-vous donner un exemple numérique de mise à jour des poids en SGD ?",
  "atoms.chat.seed.askTime": "14:25",
  "atoms.chat.seed.greeting": "Bonjour 👋 Je suis l'assistant intelligent de cette session. Je peux fournir des résumés en temps réel, simplifier les concepts ou suggérer des exercices d'entraînement.",
  "atoms.chat.seed.greetingTime": "14:23",
  "atoms.people.ali.init": "A",
  "atoms.people.ali.name": "Ali R.",
  "atoms.people.arman.init": "A",
  "atoms.people.arman.name": "Arman B.",
  "atoms.people.azimi.init": "DA",
  "atoms.people.azimi.name": "Dr. Azimi",
  "atoms.people.hanieh.init": "H",
  "atoms.people.hanieh.name": "Hanieh F.",
  "atoms.people.mohsen.init": "M",
  "atoms.people.mohsen.name": "Mohsen H.",
  "atoms.people.neda.init": "N",
  "atoms.people.neda.name": "Neda Kazemi",
  "atoms.people.nima.init": "N",
  "atoms.people.nima.name": "Nima J.",
  "atoms.people.sara.init": "S",
  "atoms.people.sara.name": "Sara M.",
  "atoms.people.zahra.init": "Z",
  "atoms.people.zahra.name": "Zahra K.",
  "atoms.poll.options.adamWeighted = Adam with class weighting": "Adam avec pondération des classes",
  "atoms.poll.options.adamWeighted": "Adam avec pondération des classes",
  "atoms.poll.options.rmspropWarmup": "RMSprop avec phase d'échauffement (Warm-up)",
  "atoms.poll.options.sgdMomentum": "SGD standard avec Momentum",
  "atoms.poll.question": "Quelle méthode d'optimisation est la plus adaptée pour entraîner des réseaux profonds sur des données déséquilibrées ?",
  "atoms.qa.q1.text": "Si la fonction de coût n'est pas convexe, la SGD converge-t-elle vers un minimum global ?",
  "atoms.qa.q1.time": "Il y a 2 minutes",
  "atoms.qa.q2.text": "Quelle est la différence pratique entre Momentum et Adam ?",
  "atoms.qa.q2.time": "Il y a 5 minutes",
  "atoms.qa.q3.text": "Quelle taille de mini-lot est recommandée pour ResNet-50 ?",
  "atoms.qa.q3.time": "Il y a 8 minutes",
  "atoms.qa.q4.text": "Quels paramètres appliquer à la SGD pour les jeux de données déséquilibrés ?",
  "atoms.qa.q4.time": "Il y a 12 minutes",
  "atoms.qa.tags.adaptive": "Adaptatif",
  "atoms.qa.tags.highlight": "Point clé",
  "atoms.qa.tags.practical": "Pratique",
  "atoms.slides.compare.body": "Le mini-lot trouve un équilibre entre la stabilité du traitement par lot et la rapidité de la SGD. Taille typique : 32 à 256.",
  "atoms.slides.noise.body": "Les fluctuations aléatoires permettent à l'algorithme d'échapper aux minima locaux et d'obtenir de meilleurs résultats sur des surfaces non convexes.",
  "atoms.slides.noise.title": "Pourquoi le bruit est utile",
  "atoms.slides.sgd.body": "À chaque étape, les poids sont mis à jour à l'aide d'un seul échantillon aléatoire. Plus rapide que la descente par lot, mais avec davantage d'oscillations sur la trajectoire de convergence.",
  "atoms.slides.sgd.title": "Descente de gradient stochastique",
  "atoms.suggestions.exercise": "Générer un exercice similaire",
  "atoms.suggestions.resources": "Ressources complémentaires",
  "atoms.suggestions.simpler": "Expliquer plus simplement",
  "atoms.suggestions.summary": "Résumé des 2 dernières minutes",
  "atoms.tabs.assistant": "Assistant",
  "atoms.tabs.captions": "Sous-titres",
  "atoms.tabs.poll": "Sondage",
  "atoms.tabs.questions": "Questions",
  "atoms.timeline.r1.label": "Révision de la séance précédente",
  "atoms.timeline.r1.time": "14:02",
  "atoms.timeline.r2.label": "Concept de la descente de gradient",
  "atoms.timeline.r2.time": "14:08",
  "atoms.timeline.r3.label": "Version par lot (Batch)",
  "atoms.timeline.r3.time": "14:16",
  "atoms.timeline.r4.label": "Descente de gradient stochastique",
  "atoms.timeline.r4.time": "14:22",
  "atoms.timeline.r5.label": "Momentum et Adam",
  "atoms.timeline.r5.time": "14:35",
  "atoms.timeline.r6.label": "Exercice interactif et Q&R",
  "atoms.timeline.r6.time": "14:45",
  "atoms.transcript.live.momentum": "Si nous mettons à jour le taux d'apprentissage en tenant compte des valeurs précédentes, cela s'appelle le Momentum.",
  "atoms.transcript.live.nesterovAnswer": "Nesterov prédit d'abord la position suivante et y calcule le gradient.",
  "atoms.transcript.live.nesterovQuestion": "En quoi cela diffère-t-il de Nesterov ?",
  "atoms.transcript.live.pytorchQuestion": "Cette idée peut-elle être implémentée dans PyTorch ?",
  "atoms.transcript.seed.r1.text": "Dans la descente de gradient stochastique, un seul échantillon est utilisé à chaque étape pour calculer le gradient.",
  "atoms.transcript.seed.r1.time": "14:20",
  "atoms.transcript.seed.r2.text": "Cela accélère le calcul et réduit l'utilisation de la mémoire.",
  "atoms.transcript.seed.r2.time": "14:21",
  "atoms.transcript.seed.r3.highlight": "Taux d'apprentissage optimal",
  "atoms.transcript.seed.r3.text": "Professeur, comment choisit-on le taux d'apprentissage optimal ?",
  "atoms.transcript.seed.r3.time": "14:22",
  "atoms.transcript.seed.r4.text": "Nous l'associons généralement à un programmateur de taux d'apprentissage ou à des algorithmes adaptatifs comme Adam.",
  "atoms.transcript.seed.r4.time": "14:22",
  "atoms.transcript.seed.r5.text": "Quelle est la différence clé exacte entre SGD et Mini-batch ?",
  "atoms.transcript.seed.r5.time": "14:23",
  "atoms.transcript.seed.r6.text": "La taille du lot. Dans le mini-lot, nous prenons entre 32 et 256 échantillons pour un meilleur compromis entre stabilité et vitesse.",
  "atoms.transcript.seed.r6.time": "14:23",
  "classes.card.attendees": "{value, number} participants",
  "classes.card.cancelled": "Cette session a été annulée.",
  "classes.card.joinDirect": "Entrée directe",
  "classes.card.joinLobby": "Entrer dans l'antichambre",
  "classes.card.newTab": "Ouvrir dans un nouvel onglet",
  "classes.card.report": "Rapport de session",
  "classes.card.reportTitle": "Rapport complet de cette session",
  "classes.emptyAll": "Aucune session ne correspond à votre recherche.",
  "classes.emptyHint": "Dès qu'un cours est planifié par l'enseignant, il apparaîtra ici.",
  "classes.emptySearch": "Aucune session ne correspond à cette recherche ou à ce filtre.",
  "classes.errLoad": "Échec du chargement des sessions.",
  "classes.eyebrow": "Cours en direct · Centre des sessions",
  "classes.filter.all": "Toutes",
  "classes.filter.ended": "Terminées",
  "classes.filter.live": "En direct",
  "classes.filter.scheduled": "Planifiées",
  "classes.filterAria": "Filtrer les sessions en direct",
  "classes.form.applySlot": "Appliquer ce créneau",
  "classes.form.cancel": "Annuler",
  "classes.form.close": "Fermer",
  "classes.form.course": "Cours associé",
  "classes.form.coursePick": "— Sélectionner un cours —",
  "classes.form.courseSearch": "Rechercher un cours (code ou intitulé)…",
  "classes.form.courseSearchAria": "Rechercher un cours",
  "classes.form.coursesError": "La liste des cours est indisponible ; veuillez réessayer plus tard.",
  "classes.form.coursesLoading": "Chargement des cours…",
  "classes.form.date": "Date",
  "classes.form.dateAria": "Date de la session",
  "classes.form.datePlaceholder": "Sélectionner la date de la session",
  "classes.form.desc": "Description (optionnel)",
  "classes.form.descPlaceholder": "Sujets ou points clés de cette session…",
  "classes.form.end": "Heure de fin",
  "classes.form.errCourse": "Veuillez sélectionner un cours associé.",
  "classes.form.errCreate": "Échec de la création de la session. Veuillez réessayer.",
  "classes.form.errDate": "Veuillez sélectionner une date de session.",
  "classes.form.errTime": "Veuillez indiquer des heures de début et de fin valides.",
  "classes.form.errTitle": "Veuillez saisir un intitulé de session.",
  "classes.form.policy": "Politique d'admission",
  "classes.form.section": "Section / Classe (optionnel)",
  "classes.form.sectionAll": "— Tout le cours (sans section spécifique) —",
  "classes.form.sectionOption": "Section {group, number}",
  "classes.form.start": "Heure de début",
  "classes.form.submit": "Planifier la session",
  "classes.form.submitting": "Planification en cours…",
  "classes.form.title": "Planifier une session de cours en direct",
  "classes.form.titleLabel": "Titre de la session",
  "classes.form.titlePlaceholder": "ex. : Résolution de problèmes du chapitre 3",
  "classes.group.live": "En direct",
  "classes.group.liveEmpty": "Aucune session n'est actuellement en direct.",
  "classes.group.past": "Passées",
  "classes.group.pastEmpty": "Aucune session passée enregistrée.",
  "classes.group.upcoming": "À venir",
  "classes.group.upcomingEmpty": "Aucune session à venir planifiée.",
  "classes.help.body": "Sur cette page, vous pouvez consulter les cours en direct classés en « En direct », « À venir » et « Passées ». Cliquez sur « Entrer dans l'antichambre » pour tester votre caméra et votre microphone avant d'entrer ; si une session est en direct, cliquez sur « Entrée directe » pour la rejoindre immédiatement. Les enseignants et administrateurs peuvent planifier un nouveau cours avec « Nouvelle session ».",
  "classes.help.title": "Guide des cours en direct",
  "classes.kpi.live": "En direct",
  "classes.kpi.total": "Total des sessions",
  "classes.kpi.upcoming": "À venir",
  "classes.lead": "Consultez les sessions en direct, à venir et passées ; entrez dans l'antichambre pour tester vos périphériques ou rejoignez directement le cours s'il a débuté.",
  "classes.loading": "Chargement des sessions…",
  "classes.new": "Nouvelle session",
  "classes.noCourse": "Aucun cours associé",
  "classes.policy.enrolled": "Étudiants inscrits uniquement",
  "classes.policy.invite": "Sur invitation uniquement",
  "classes.policy.public": "Ouvert à tous (Public)",
  "classes.schedule.at": "{date} · {clock}",
  "classes.schedule.unknown": "Horaire non précisé",
  "classes.searchAria": "Rechercher des sessions",
  "classes.searchPlaceholder": "Rechercher par titre, cours ou enseignant…",
  "classes.status.cancelled": "Annulé",
  "classes.status.ended": "Terminé",
  "classes.status.live": "En direct",
  "classes.status.scheduled": "Planifié",
  "classes.title": "Cours en direct",
  "tables.assign.balanced": "Automatique (équilibré)",
  "tables.assign.noStudents": "Aucun étudiant dans le cours pour l'instant.",
  "tables.assign.pickFor": "Table pour {name}",
  "tables.assign.random": "Aléatoire",
  "tables.assign.title": "Placer les étudiants",
  "tables.assign.unassigned": "Non assigné",
  "tables.cancel": "Annuler",
  "tables.confirm": "Oui",
  "tables.countLabel": "Nombre de nouvelles tables",
  "tables.capacity": "{used, number} sur {total, number} personnes",
  "tables.capacityLabel": "Capacité par table",
  "tables.create": "Créer une table",
  "tables.defaultName": "Table {index, number}",
  "tables.dissolve": "Dissoudre la table",
  "tables.dissolveConfirm": "Dissoudre « {name} » ? Ses membres retourneront dans la classe principale.",
  "tables.duration.label": "Durée du travail en table",
  "tables.duration.option": "{count, number} minutes",
  "tables.empty": "Aucune table créée pour le moment.",
  "tables.extend": "{count, number} minutes supplémentaires",
  "tables.limit": "Maximum {count, number} tables",
  "tables.mediaNote": "Pendant le travail en table, seuls vos camarades de table vous voient et vous entendent.",
  "tables.memberCount": "{count, number} personnes",
  "tables.members": "Camarades de table",
  "tables.nameLabel": "Nom de la table",
  "tables.peekNotice": "L'enseignant supervise les tables",
  "tables.rejected.empty": "Aucune table n'a de membres.",
  "tables.rejected.full": "Cette table est complète.",
  "tables.rejected.error": "Une erreur est survenue ; veuillez réessayer.",
  "tables.rejected.forbidden": "Vous n'avez pas l'autorisation pour cette action.",
  "tables.rejected.invalid": "Demande invalide.",
  "tables.rejected.limit": "Vous avez atteint le nombre maximal de tables.",
  "tables.rejected.noRound": "Le travail en table n'a pas commencé.",
  "tables.rejected.notFound": "Cette table n'existe plus.",
  "tables.rejected.roundActive": "Cette action ne peut pas être effectuée pendant le travail en table.",
  "tables.rejected.selectionLocked": "La sélection de table est verrouillée par l'enseignant.",
  "tables.remaining": "Temps restant : {time}",
  "tables.rename": "Renommer",
  "tables.returnAll": "Rappeler tout le monde",
  "tables.returnAllConfirm": "Rappeler tout le monde dans la classe principale ?",
  "tables.returned": "Tout le monde est revenu dans la classe principale.",
  "tables.running": "Travail en table en cours",
  "tables.save": "Enregistrer",
  "tables.select.action": "Sélectionner la table",
  "tables.select.full": "Complète",
  "tables.select.hint": "Sélectionnez une table disponible ; vous pouvez la modifier tant que l'enseignant laisse la sélection ouverte.",
  "tables.select.selected": "Votre table",
  "tables.select.title": "Sélectionner une table",
  "tables.selection.close": "Fermer la sélection des étudiants",
  "tables.selection.open": "Ouvrir la sélection des étudiants",
  "tables.start": "Démarrer le travail en table",
  "tables.startHint": "Au moins une table avec des membres est requise.",
  "tables.timeUp": "Le temps de travail en table est écoulé ; tout le monde est retourné dans la classe principale.",
  "tables.title": "Tables de groupe",
  "tables.transcriptConsentProgress": "Consentement transcription vocale : {accepted} sur {total}",
  "tables.transcriptDurableEnabled": "L'enregistrement persistant n'est actif qu'avec le consentement de tous.",
  "tables.transcriptConsentAccept": "Accepter l'enregistrement audio de la table",
  "tables.transcriptConsentWithdraw": "Retirer le consentement",
  "tables.transcriptWithdrawalReason": "Motif du retrait du consentement",
  "tables.transcriptQuarantined": "La transcription de cette table est mise en quarantaine pour une recréation sécurisée.",
  "tables.transcriptConsentUnavailable": "L'état du consentement à la transcription n'est pas disponible.",
  "tables.visit.join": "Rejoindre",
  "tables.visit.joined": "Vous êtes à « {name} »",
  "tables.visit.leave": "Retourner à la classe principale",
  "tables.visit.peek": "Écouter discrètement",
  "tables.visit.peeking": "Écoute de « {name} »",
  "tables.you.assigned": "Vous êtes à « {name} »",
  "tables.you.unassigned": "Vous n'avez pas encore été assigné à une table.",
  "tables.you.waiting": "Le travail en table n'a pas encore commencé."
}
