# French translations for Part 2 (234 keys)
# Modules: wb, preflight, guide, analytics, lobby, poll

MAP_FR_2 = {
  "wb.canvasLabel": "Zone de dessin du tableau blanc partagé",
  "wb.clearAll": "Tout effacer",
  "wb.clearAllTitle": "Tout effacer (Hôte)",
  "wb.clearConfirm": "Confirmer l'effacement complet",
  "wb.clearConfirmShort": "Confirmer ?",
  "wb.clearConfirmTitle": "Cliquez à nouveau pour confirmer",
  "wb.colorGroup": "Couleur",
  "wb.colorSwatch": "Couleur {color}",
  "wb.exportPng": "Exporter en PNG",
  "wb.exportPngTitle": "Enregistrer sous forme d'image PNG",
  "wb.hintEmpty": "Le tableau blanc est vide. Sélectionnez un outil et dessinez sur la zone de travail.",
  "wb.hintText": "Saisissez du texte et appuyez sur Entrée pour le placer sur le tableau.",
  "wb.itemCount": "{count, plural, one {# élément sur le tableau blanc} other {# éléments sur le tableau blanc}}",
  "wb.lock": "Verrouiller le tableau blanc",
  "wb.lockTitle": "Verrouiller le tableau blanc pour les participants",
  "wb.lockedNotice": "Le tableau blanc a été verrouillé par l'hôte ; consultation uniquement pour le moment.",
  "wb.lockedTitle": "Le tableau blanc est verrouillé — cliquez pour déverrouiller",
  "wb.redo": "Rétablir",
  "wb.textLabel": "Texte sur le tableau blanc",
  "wb.textPlaceholder": "Texte… (Entrée pour placer, Échap pour annuler)",
  "wb.toolbarLabel": "Outils du tableau blanc",
  "wb.tools.arrow": "Flèche",
  "wb.tools.circle": "Cercle",
  "wb.tools.eraser": "Gomme",
  "wb.tools.line": "Ligne",
  "wb.tools.pen": "Stylo",
  "wb.tools.rect": "Rectangle",
  "wb.tools.select": "Sélectionner",
  "wb.tools.text": "Texte",
  "wb.undo": "Annuler",
  "wb.undoTitle": "Annuler (votre dernier élément)",
  "wb.unlock": "Déverrouiller le tableau blanc",
  "wb.widthGroup": "Épaisseur du trait",
  "wb.widthOption": "Épaisseur {width, number}",
  "preflight.bandwidth.detail": "Votre connexion Internet a été détectée comme faible ; la vidéo de la caméra sera transmise avec une qualité réduite pour éviter les interruptions.",
  "preflight.bandwidth.good": "Bonne",
  "preflight.bandwidth.label": "Qualité de la connexion Internet",
  "preflight.bandwidth.unknown": "Inconnue",
  "preflight.bandwidth.weak": "Faible",
  "preflight.captions.available": "Disponible",
  "preflight.captions.detail": "Le sous-titrage et la traduction en direct basés sur la reconnaissance vocale du navigateur fonctionnent uniquement sous Chrome/Edge. Les autres fonctionnalités du cours restent pleinement accessibles sans cela.",
  "preflight.captions.label": "Sous-titres en direct (optionnel)",
  "preflight.captions.limited": "Limité",
  "preflight.device.absentDetail": "Aucun périphérique {device} actif trouvé. Vérifiez le branchement ; vous pouvez toujours entrer dans le cours sans {device}.",
  "preflight.device.absentStatus": "Introuvable",
  "preflight.device.camera": "Caméra",
  "preflight.device.deniedDetail": "L'accès à {device} a été refusé. Cliquez sur l'icône de cadenas à côté de la barre d'adresse et autorisez « {device} ». Vous pouvez toujours entrer sans cela.",
  "preflight.device.deniedStatus": "Accès refusé",
  "preflight.device.microphone": "Microphone",
  "preflight.device.promptDetail": "L'autorisation d'accéder à {device} n'a pas encore été accordée. Sélectionnez Autoriser lorsque votre navigateur vous le demande.",
  "preflight.device.promptStatus": "En attente d'autorisation",
  "preflight.device.readyStatus": "Prêt",
  "preflight.panel.blocked": "Vous ne pouvez pas entrer dans le cours tant que les éléments en rouge ci-dessus ne sont pas résolus. Une fois corrigés, cliquez sur « Revérifier ».",
  "preflight.panel.checking": "Vérification en cours…",
  "preflight.panel.regionLabel": "Vérification des périphériques avant l'entrée",
  "preflight.panel.retry": "Revérifier",
  "preflight.panel.severity.fail": "Problème",
  "preflight.panel.severity.pass": "Prêt",
  "preflight.panel.severity.warn": "Avertissement",
  "preflight.panel.title": "Vérification de l'état des périphériques",
  "preflight.screen.detail": "Votre navigateur ne prend pas en charge le partage d'écran. Si vous prévoyez de faire une présentation, utilisez Chrome, Edge ou Firefox pour ordinateur. Ce n'est pas requis pour assister au cours.",
  "preflight.screen.label": "Partage d'écran",
  "preflight.secure.bad": "Non sécurisé",
  "preflight.secure.detail": "Cette page n'est pas ouverte via une connexion sécurisée (HTTPS) ; les navigateurs n'accordent l'accès à la caméra et au microphone que sous HTTPS. Veuillez ouvrir l'URL avec https.",
  "preflight.secure.label": "Connexion sécurisée (HTTPS)",
  "preflight.secure.ok": "Sécurisé",
  "preflight.supported": "Pris en charge",
  "preflight.unsupported": "Non pris en charge",
  "preflight.webrtc.detail": "Votre navigateur ne prend pas en charge l'accès à la caméra et au microphone (getUserMedia). Veuillez utiliser une version récente de Chrome, Edge ou Firefox pour ordinateur.",
  "preflight.webrtc.label": "Prise en charge des appels vidéo (WebRTC)",
  "guide.button": "Guide",
  "guide.lobby.chain.check": "Ici, vous testez votre nom, votre caméra et votre microphone et effectuez la vérification préalable.",
  "guide.lobby.chain.enter": "À l'heure du cours, accédez à cette antichambre depuis cet endroit.",
  "guide.lobby.chain.join": "En entrant dans le cours, vous êtes redirigé vers la salle en direct ; le guide s'y poursuit.",
  "guide.lobby.chain.schedule": "Le cours en direct est planifié dans le programme et apparaît dans « Mes cours ».",
  "guide.lobby.ifEmpty": "Si le cours n'a pas encore commencé, attendez l'hôte ; l'état de la connexion se met à jour sur cette même page.",
  "guide.lobby.intro": "Bienvenue dans l'antichambre du cours en direct. Vérifiez ici votre son, votre image et votre connexion avant d'entrer.",
  "guide.lobby.roles.host.does": "Entre dans la salle, accueille les étudiants et démarre le cours.",
  "guide.lobby.roles.host.label": "Hôte (Enseignant)",
  "guide.lobby.roles.student.does": "Teste la caméra et le microphone, vérifie l'état de préparation et entre dans le cours.",
  "guide.lobby.roles.student.label": "Vous (Étudiant)",
  "guide.lobby.roles.support.does": "Si les tests de périphériques échouent à répétition, le support technique utilise ce rapport d'état pour le dépannage.",
  "guide.lobby.roles.support.label": "Support technique",
  "guide.lobby.title": "Guide de l'antichambre",
  "guide.lobby.youCan.camera": "Affichez l'aperçu de la caméra et activez-la ou désactivez-la ; lorsqu'elle est coupée, votre avatar s'affiche.",
  "guide.lobby.youCan.join": "Dès que la liste de vérification passe au vert, rejoignez le cours à l'aide du bouton Entrer dans le cours.",
  "guide.lobby.youCan.mic": "Activez ou désactivez votre microphone à l'aide du bouton microphone.",
  "guide.lobby.youCan.name": "Modifiez votre nom d'affichage avant d'entrer dans le cours.",
  "guide.sections.chain": "Parcours complet, du début à la fin",
  "guide.sections.ifEmpty": "Si la page est vide",
  "guide.sections.roles": "Qui fait quoi",
  "guide.sections.youCan": "Que pouvez-vous faire ici ?",
  "guide.session.chain.participate": "Pendant le cours, vous participez via le microphone, la caméra et le chat ; l'hôte gère le déroulement.",
  "guide.session.chain.record": "Si l'hôte active l'enregistrement, celui-ci devient disponible une fois le cours terminé.",
  "guide.session.chain.review": "Vous revenez depuis « Enregistrements » pour revoir un cours manqué ou réviser.",
  "guide.session.chain.start": "L'hôte (enseignant) démarre le cours en direct ; vous rejoignez la salle.",
  "guide.session.ifEmpty": "Si le cours n'a pas encore commencé, attendez l'hôte ; l'état de la connexion se met à jour sur cette page.",
  "guide.session.intro": "Cette page est votre salle de cours en direct avec microphone/caméra, partage d'écran, chat et Q&R. L'hôte (enseignant) gère le cours et enregistre si nécessaire.",
  "guide.session.roles.host.does": "Démarre et contrôle le cours, et active l'enregistrement si besoin.",
  "guide.session.roles.host.label": "Hôte (Enseignant)",
  "guide.session.roles.student.does": "Rejoint le cours, participe et regarde les enregistrements plus tard si nécessaire.",
  "guide.session.roles.student.label": "Vous (Étudiant)",
  "guide.session.title": "Guide du cours en direct",
  "guide.session.youCan.chat": "Envoyez des messages ou posez des questions par écrit à l'aide du « Chat ».",
  "guide.session.youCan.media": "Activez ou désactivez votre microphone et votre caméra depuis la barre inférieure.",
  "guide.session.youCan.recordings": "Une fois le cours terminé, regardez l'enregistrement sous « Enregistrements » s'il a été enregistré.",
  "guide.session.youCan.share": "Partagez votre écran si l'hôte vous y autorise.",
  "analytics.anonymous": "Utilisateur",
  "analytics.attendance.absentChip": "✗ Absent {count, number}",
  "analytics.attendance.absentLabel": "Absent",
  "analytics.attendance.avatarFallback": "?",
  "analytics.attendance.duration": "Durée : {value}",
  "analytics.attendance.empty": "Aucune présence enregistrée pour l'instant. À mesure que les participants rejoindront, ils apparaîtront ici.",
  "analytics.attendance.excusedChip": "Excusé {count, number}",
  "analytics.attendance.excusedLabel": "Excusé",
  "analytics.attendance.finalized": "Finalisé",
  "analytics.attendance.inClass": "En cours",
  "analytics.attendance.joinedAt": "Arrivée : {time}",
  "analytics.attendance.lateChip": "⏰ En retard {count, number}",
  "analytics.attendance.lateLabel": "En retard",
  "analytics.attendance.left": "A quitté",
  "analytics.attendance.loading": "Chargement des présences…",
  "analytics.attendance.neverOpened": "Cette session n'a pas eu lieu (aucune présence enregistrée).",
  "analytics.attendance.presentChip": "✓ Présent {count, number}",
  "analytics.attendance.presentLabel": "Présent",
  "analytics.attendance.provisional": "Provisoire (jusqu'à la fin du cours)",
  "analytics.attendance.refreshNote": "{count, number} personnes · Mise à jour toutes les {seconds, number} secondes",
  "analytics.attendance.stillPresent": " (Actuellement présent)",
  "analytics.attendance.title": "Liste des présences",
  "analytics.duration.hours": "{count, plural, one {# heure} other {# heures}}",
  "analytics.duration.hoursMinutes": "{hours, number} heures et {minutes, number} minutes",
  "analytics.duration.lessThanMinute": "Moins d'une minute",
  "analytics.duration.minutes": "{count, plural, one {# minute} other {# minutes}}",
  "analytics.error.attendance": "Impossible de récupérer la liste des présences. Cette section est réservée à l'hôte.",
  "analytics.participation.aria": "Microphone ouvert {on, number} sur {total, number}",
  "analytics.participation.empty": "Personne n'est encore dans le cours.",
  "analytics.participation.muted": "Micro coupé : {count, number}",
  "analytics.participation.on": "Ouvert : {count, number} ({pct, number} %)",
  "analytics.participation.title": "Participation audio",
  "analytics.poll.active": "Un sondage est actuellement en cours",
  "analytics.poll.idle": "Aucun sondage actif",
  "analytics.stat.chat": "Messages de chat",
  "analytics.stat.hands": "Mains levées",
  "analytics.stat.micOn": "Micros ouverts",
  "analytics.stat.present": "Actuellement présents",
  "lobby.back": "Retour à l'espace de travail",
  "lobby.removedByHost": "Vous avez été exclu de ce cours. Vous ne pouvez le rejoindre qu'après autorisation de l'enseignant.",
  "lobby.removedServiceDesk": "Soumettre un ticket au Service Desk",
  "lobby.cam.off": "Désactiver la caméra",
  "lobby.cam.on": "Activer la caméra",
  "lobby.cam.stateOff": "Caméra désactivée",
  "lobby.cam.stateOn": "Caméra activée",
  "lobby.camOffOverlay": "La caméra est désactivée",
  "lobby.conn.fair": "Moyenne",
  "lobby.conn.good": "Bonne",
  "lobby.conn.poor": "Médiocre",
  "lobby.conn.title": "Qualité de la connexion",
  "lobby.conn.unknown": "Inconnue",
  "lobby.cta.blocked": "Pour entrer dans le cours, les prérequis critiques ci-dessus (connexion sécurisée et compatibilité du navigateur) doivent être résolus.",
  "lobby.cta.blockedTitle": "Impossible d'entrer tant que les prérequis critiques ne sont pas résolus",
  "lobby.cta.enter": "Entrer dans le cours",
  "lobby.cta.ready": "Vérifiez votre vidéo et votre audio avant d'entrer.",
  "lobby.cta.waiting": "L'enseignant n'est pas encore entré ; vous pouvez entrer et attendre.",
  "lobby.device.camera": "Caméra",
  "lobby.device.cameraNone": "Aucune caméra trouvée",
  "lobby.device.fallback": "{device} {index, number}",
  "lobby.device.mic": "Microphone",
  "lobby.device.micNone": "Aucun microphone trouvé",
  "lobby.device.speaker": "Haut-parleur",
  "lobby.device.speakerDefault": "Haut-parleur par défaut du système",
  "lobby.fallbackTitle": "Cours en direct",
  "lobby.guest": "Invité",
  "lobby.help.body": "Avant d'entrer dans le cours en direct, testez ici votre caméra, votre microphone et votre haut-parleur. Utilisez les boutons sous l'aperçu pour activer ou désactiver la caméra ou le microphone et modifiez les périphériques dans la colonne des paramètres. Lorsque tout est prêt, cliquez sur « Entrer dans le cours ».",
  "lobby.help.title": "Guide d'entrée dans le cours",
  "lobby.joinMuted": "Entrer avec le micro coupé",
  "lobby.loading": "Chargement des détails de la session…",
  "lobby.media.denied": "L'accès à la caméra ou au microphone n'a pas été accordé.",
  "lobby.media.deniedTitle": "Accès à la caméra / au microphone refusé",
  "lobby.media.notFound": "Périphérique de caméra ou de microphone introuvable.",
  "lobby.meta.host": "Enseignant : {name}",
  "lobby.meta.time": "Heure : {time}",
  "lobby.meter.label": "Niveau du microphone",
  "lobby.meter.micOff": "Le microphone est coupé — réactivez-le pour tester.",
  "lobby.mic.off": "Couper le microphone",
  "lobby.mic.on": "Réactiver le microphone",
  "lobby.mic.stateOff": "Microphone coupé",
  "lobby.mic.stateOn": "Microphone actif",
  "lobby.perm.retry": "Réessayer la demande d'autorisation",
  "lobby.perm.step1": "Cliquez sur l'icône de cadenas à côté de la barre d'adresse du navigateur.",
  "lobby.perm.step2": "Définissez les autorisations « Caméra » et « Microphone » sur « Autoriser ».",
  "lobby.perm.step3": "Cliquez ensuite sur le bouton ci-dessous pour réessayer.",
  "lobby.perm.without": "Vous pouvez également entrer dans le cours sans caméra ni microphone.",
  "lobby.settings.name": "Votre nom d'affichage dans le cours",
  "lobby.settings.title": "Paramètres audio et vidéo",
  "lobby.speaker.playing": "Lecture en cours…",
  "lobby.speaker.test": "Tester",
  "lobby.status.ended": "Cette session est terminée",
  "lobby.status.live": "En cours",
  "lobby.status.prefix": "État : {status}",
  "lobby.status.waiting": "L'enseignant n'est pas encore entré",
  "poll.addOption": "Ajouter une option",
  "poll.cancel": "Annuler",
  "poll.changeHint": "Pour modifier votre vote, sélectionnez une autre option.",
  "poll.emptyGuest": "Il n'y a actuellement aucun sondage actif. Lorsque l'hôte lancera un sondage, il apparaîtra ici.",
  "poll.emptyHost": "Aucun sondage actif. Cliquez sur « Nouveau sondage » pour en créer un.",
  "poll.end": "Terminer le sondage",
  "poll.endedBadge": "Terminé",
  "poll.finalTotal": "Résultats finaux · Total {count, plural, one {# vote} other {# votes}}",
  "poll.minOptions": "Au moins {min, number} options non vides sont requises pour démarrer.",
  "poll.multi": "Choix multiple",
  "poll.multiLabel": "Autoriser la sélection de plusieurs options (Choix multiple)",
  "poll.new": "Nouveau sondage",
  "poll.optionN": "Option {n, number}",
  "poll.optionTally": "{pct, number} % · {count, number}",
  "poll.optionsLabel": "Options ({used, number} sur {max, number})",
  "poll.questionAria": "Texte de la question",
  "poll.questionLabel": "Question",
  "poll.questionPlaceholder": "ex. : Quel sujet préférez-vous ?",
  "poll.removeOption": "Supprimer l'option",
  "poll.single": "Choix unique",
  "poll.start": "Démarrer le sondage",
  "poll.status.ended": "Le sondage est terminé — résultats définitifs.",
  "poll.status.endingWait": "En attente de la confirmation de fin de sondage…",
  "poll.status.startFailed": "Le serveur n'a pas confirmé le démarrage du sondage. Vérifiez votre connexion et vos droits d'hôte, puis réessayez.",
  "poll.status.started": "Sondage démarré — en attente des réponses…",
  "poll.status.starting": "Démarrage du sondage…",
  "poll.status.voteFailed": "L'envoi du vote n'a pas été confirmé ; veuillez réessayer.",
  "poll.status.voteSent": "Votre vote a été enregistré ✓",
  "poll.status.voting": "Envoi du vote…",
  "poll.status.waitingAnswers": "En attente de réponses…",
  "poll.submitVote": "Envoyer le vote",
  "poll.title": "Sondage",
  "poll.updateVote": "Modifier le vote",
  "poll.voteCount": "{count, plural, one {# vote} other {# votes}}"
}
