# French translations for Part 5 (239 keys)
# Module: session

MAP_FR_5 = {
  "session.absence.instructorDisconnected": "Connexion de l'enseignant perdue — le cours se poursuit en attendant son retour.",
  "session.absence.takeOver": "Prendre temporairement le contrôle des tables et de la file d'attente de parole",
  "session.supervision.waiting": "Le cours est temporairement sans supervision académique. En attente du retour de l'enseignant ou de la prise de relais par un assistant.",
  "session.supervision.paused": "La supervision académique n'a pas été reprise dans le délai imparti ; l'enregistrement est suspendu. Le cours et les contenus sont préservés.",
  "session.supervision.recordingDenied": "Pour enregistrer ce cours, la validation de la responsabilité académique et une présence effective sont requises.",
  "session.supervision.offer": "Transférer la responsabilité du cours à {name}",
  "session.supervision.offerPending": "Offre de responsabilité envoyée ; tant qu'elle n'est pas acceptée par l'assistant, elle demeure sous votre responsabilité.",
  "session.supervision.accept": "Accepter la responsabilité académique du cours",
  "session.supervision.conflict": "Vous êtes déjà responsable d'un autre cours en direct. Veuillez le terminer d'abord ou déléguer la responsabilité à un assistant habilité et présent.",
  "session.supervision.returnFirst": "Retourner au premier cours",
  "session.supervision.returnLobby": "Retourner à l'antichambre",
  "session.cohost.denied": "Impossible d'accorder le statut de co-hôte ; l'assistant doit être présent dans ce cours et assigné à cette section.",
  "session.cohost.grant": "Promouvoir temporairement {name}",
  "session.cohost.granted": "Vous êtes désormais co-hôte temporaire de ce cours.",
  "session.cohost.instructorPresent": "L'enseignant est de retour dans le cours ; la demande de délégation n'est pas autorisée.",
  "session.jitsi.failed": "Échec du chargement de la salle vidéo. Vérifiez votre connexion Internet ou le domaine Jitsi, ou ouvrez la session dans un nouvel onglet.",
  "session.jitsi.openNewTab": "Ouvrir la session dans un nouvel onglet",
  "session.lang.faShort": "FA",
  "session.langMenu.help": "Langue dans laquelle vous consultez les sous-titres",
  "session.langMenu.my": "Ma langue : {label}",
  "session.langMenu.notFound": "Aucune langue trouvée.",
  "session.langMenu.searchLabel": "Rechercher une langue",
  "session.langMenu.searchPlaceholder": "Rechercher une langue…",
  "session.layout.custom": "Personnalisé",
  "session.layout.focusPresentation": "Priorité à la présentation",
  "session.layout.focusVideo": "Priorité à la vidéo",
  "session.layout.smart": "Intelligent",
  "session.leave": "Quitter le cours",
  "session.leaveShort": "Quitter",
  "session.media.audioOnly": "La caméra est indisponible ; poursuite en mode audio uniquement.",
  "session.media.denied": "L'accès à la caméra ou au micro a été refusé. Cliquez sur l'icône de cadenas dans la barre d'adresse pour autoriser, puis cliquez sur « Réessayer ».",
  "session.media.errSuffix": " (Erreur : {name})",
  "session.media.generic": "Impossible d'accéder aux périphériques média. Vous pouvez rester dans le cours avec la caméra et le micro coupés.",
  "session.media.inUse": "La caméra est utilisée par une autre application ou un autre onglet — veuillez fermer les onglets de l'antichambre ou les applications en arrière-plan.",
  "session.media.notFound": "Aucune caméra ni aucun microphone trouvés. Branchez un appareil et cliquez sur « Réessayer », ou continuez sans son.",
  "session.media.retry": "Réessayer",
  "session.media.unsupported": "Votre navigateur ne prend pas en charge l'accès à la caméra/au micro ou la page n'est pas chargée via une connexion sécurisée (HTTPS).",
  "session.panel.chatTranslated": "Chat (Traduit)",
  "session.panel.empty": "Aucune parole enregistrée pour le moment.",
  "session.panel.regionLabel": "Paroles traduites en direct",
  "session.panel.title": "Chat en direct (Traduit)",
  "session.participant": "Participant",
  "session.rec.active": "Enregistrement en cours",
  "session.rec.armed": "Prêt à enregistrer",
  "session.rec.cancel": "Annuler",
  "session.rec.netFailed": "Échec de connexion au serveur. Veuillez réessayer.",
  "session.rec.paused": "Temporairement en pause",
  "session.rec.retry": "Réessayer",
  "session.rec.saveCta": "Enregistrer dans l'archive",
  "session.rec.saveFailed": "Échec de l'enregistrement (code {code, number}). Veuillez réessayer.",
  "session.rec.saveMeta": "Taille : {size} Mo · Durée : {clock}",
  "session.rec.saveTitle": "Enregistrer l'enregistrement dans l'archive ?",
  "session.rec.saved": "Enregistrement sauvegardé dans l'archive",
  "session.rec.durableServer": "Ce segment est enregistré sur le serveur.",
  "session.rec.durablePending": "Le segment est conservé dans ce navigateur en attente de validation par le serveur.",
  "session.rec.durableUnprotected": "Le segment actif n'est pas encore sécurisé ; une fermeture inattendue peut entraîner la perte des données non sauvegardées.",
  "session.rec.recoveryAvailable": "Un enregistrement sécurisé non validé est disponible pour récupération.",
  "session.rec.recoveryOpen": "Récupérer l'enregistrement",
  "session.rec.startFailed": "Échec du démarrage de l'enregistrement. Veuillez réessayer.",
  "session.rec.unsupportedRecorder": "Votre navigateur ne prend pas en charge l'enregistrement vidéo (MediaRecorder). Veuillez utiliser une version récente de Chrome, Edge ou Firefox pour ordinateur.",
  "session.rec.unsupportedScreen": "Votre navigateur ne prend pas en charge l'enregistrement de l'écran. Veuillez utiliser une version récente de Chrome, Edge ou Firefox pour ordinateur.",
  "session.rec.uploading": "Téléversement en cours… {pct, number} %",
  "session.reconnecting": "Reconnexion en cours…",
  "session.selfName": "{name} (Vous)",
  "session.share.failed": "Échec du partage d'écran. Veuillez réessayer.",
  "session.share.unsupported": "Votre navigateur ne prend pas en charge le partage d'écran. Veuillez utiliser une version récente de Chrome, Edge ou Firefox pour ordinateur.",
  "session.someone": "Un participant",
  "session.soniox.captionFailed": "Flux de sous-titres déconnecté ; la connexion n'a pas pu être rétablie après plusieurs tentatives. Le cours se poursuit normalement.",
  "session.soniox.connecting": "Traduction en direct : Connexion en cours…",
  "session.soniox.detectedLabel": "Détectée :",
  "session.soniox.detectedTitle": "Langue détectée de l'orateur",
  "session.soniox.error": "Traduction en direct : Erreur — Nouvel essai en cours",
  "session.soniox.exportDate": "Date d'exportation : {date}",
  "session.soniox.exportHead": "Transcription traduite en direct — Session {id}",
  "session.soniox.group": "Traduction en direct",
  "session.soniox.langSep": ", ",
  "session.soniox.on": "Traduction en direct : Activée",
  "session.soniox.receiveOnly": "Mode affichage des sous-titres : Voir les paroles des autres sans activer le micro",
  "session.soniox.saveFallback": "Échec de l'enregistrement sur le serveur — sauvegardé localement à la place",
  "session.soniox.stConnecting": "Connexion en cours…",
  "session.soniox.stError": "Erreur",
  "session.soniox.stMore": " +{value, number}",
  "session.soniox.stOn": "Activé",
  "session.soniox.stOnTargets": "Activé · → {langs}",
  "session.soniox.stPaused": "En pause (Micro coupé)",
  "session.soniox.stReceiveOnly": "Affichage uniquement (Sans micro)",
  "session.soniox.stReconnecting": "Reconnexion…",
  "session.soniox.stTranscribeOnly": "Activé · Transcription uniquement",
  "session.soniox.turnOn": "Activer la traduction en direct",
  "session.soniox.unavailable": "Traduction en direct indisponible",
  "session.stage.captionFeed": "Sous-titres traduits en direct",
  "session.stage.modeLabel": "Mode de présentation",
  "session.stage.noShare": "Aucune présentation partagée",
  "session.stage.noShareHint": "Pour présenter, cliquez sur « Partager l'écran » ou sélectionnez « Tableau blanc » pour dessiner ensemble.",
  "session.stage.share": "Partager l'écran",
  "session.stage.whiteboard": "Tableau blanc",
  "session.tile.handRaised": "Main levée",
  "session.tile.pin": "Épingler {name}",
  "session.tile.quality.connecting": "Reconnexion",
  "session.tile.quality.fair": "Qualité de connexion : Moyenne",
  "session.tile.quality.good": "Qualité de connexion : Bonne",
  "session.tile.quality.poor": "Qualité de connexion : Médiocre",
  "session.tile.quality.unknown": "Qualité de connexion : Inconnue",
  "session.titleFallback": "Cours en direct",
  "session.duplicate.replaced": "Vous vous êtes connecté depuis un autre appareil ; l'audio et la vidéo sur cet appareil ont été coupés.",
  "session.duplicate.continued": "Connexion de l'appareil précédent fermée ; vous êtes désormais connecté depuis cet appareil.",
  "session.duplicate.continueHere": "Continuer sur cet appareil",
  "session.toast.captionsOn": "Sous-titres activés — chaque orateur est identifié par son nom",
  "session.toast.chatLocked": "Chat verrouillé par l'hôte",
  "session.toast.chatUnlocked": "Chat déverrouillé",
  "session.toast.joined": "{name} a rejoint le cours",
  "session.toast.kicked": "Vous avez été exclu du cours par l'hôte.",
  "session.toast.left": "{name} a quitté le cours",
  "session.toast.recStarted": "Enregistrement démarré",
  "session.toast.recStopped": "Enregistrement arrêté",
  "session.toolbar.cam": "Caméra",
  "session.toolbar.captionsGroup": "Sous-titres et traduction",
  "session.toolbar.ccOff": "Sous-titres (CC)",
  "session.toolbar.ccOn": "Sous-titres ✓ ({lang})",
  "session.toolbar.ccStarting": "Sous-titres… ({lang})",
  "session.toolbar.endClass": "Terminer le cours",
  "session.toolbar.endClassShort": "Terminer",
  "session.toolbar.handShort": "Main",
  "session.toolbar.langEn": "Langue : Anglais",
  "session.toolbar.langFa": "Langue : Persan",
  "session.toolbar.layout": "Disposition",
  "session.toolbar.mic": "Microphone",
  "session.toolbar.more": "Plus",
  "session.toolbar.moreLabel": "Plus de commandes",
  "session.toolbar.panel": "Chat et participants",
  "session.toolbar.panelShort": "Chat",
  "session.toolbar.raiseHand": "Lever la main",
  "session.toolbar.reactions": "Réactions",
  "session.toolbar.sendReaction": "Envoyer la réaction {emoji}",
  "session.toolbar.share": "Partager l'écran",
  "session.toolbar.shareShort": "Partager",
  "session.topbar.elapsedLabel": "Durée du cours",
  "session.topbar.hostPrefix": "Hôte : {name}",
  "session.topbar.loadingTitle": "Chargement…",
  "session.topbar.recOffTitle": "L'enregistrement s'effectue dans le navigateur de l'hôte et est sauvegardé dans l'archive une fois terminé",
  "session.topbar.recOnTitle": "Cette session est actuellement enregistrée (enregistrement dans le navigateur de l'hôte)",
  "session.topbar.recStart": "Démarrer l'enregistrement",
  "session.topbar.recStop": "Arrêter l'enregistrement",
  "session.unpin": "Désépingler",
  "session.unpinLabel": "Quitter l'épinglage ✕",
  "session.view.gallery": "Mosaïque",
  "session.view.modeLabel": "Mode d'affichage",
  "session.view.podium": "Tribune",
  "session.you": "Vous"
}
