# French translations for Part 4 (244 keys)
# Modules: report, playback

MAP_FR_4 = {
  "report.playback.open": "Relecture interactive",
  "report.att.ABSENT": "Absent",
  "report.att.EXCUSED": "Excusé",
  "report.att.LATE": "En retard",
  "report.att.NONE": "—",
  "report.att.PRESENT": "Présent",
  "report.att.absent": "Absents : {value, number}",
  "report.att.excused": "Excusés : {value, number}",
  "report.att.finalized": "Finalisé",
  "report.att.late": "En retard : {value, number}",
  "report.att.present": "Présents : {value, number}",
  "report.att.provisional": "Provisoire",
  "report.att.total": "Total : {value, number}",
  "report.att.unrecorded": "Non enregistré",
  "report.attendance.noRoster": "Aucune liste d'inscrits disponible pour cette session.",
  "report.attendance.noSection": "Cette session n'est pas liée à une section spécifique ; la présence officielle n'est enregistrée que pour les cours rattachés à une section. La liste des participants réels apparaît ci-dessous.",
  "report.attendance.title": "Présence",
  "report.back": "Retour au centre des sessions",
  "report.captions.lines": "Lignes de sous-titres",
  "report.captions.linesValue": "{value, number} lignes",
  "report.captions.recording": "Enregistrement",
  "report.captions.soniox": "Traduction en direct enregistrée",
  "report.captions.title": "Sous-titres et enregistrement",
  "report.chat.download": "Télécharger la transcription",
  "report.chat.empty": "Aucun message n'a été enregistré dans le chat public pour cette session.",
  "report.chat.exportHead": "Journal du chat de la session : {title}",
  "report.chat.showAll": "Afficher les {value, number} messages",
  "report.chat.showLess": "Afficher moins",
  "report.chat.title": "Chat enregistré",
  "report.chat.truncated": "Affichage des {shown, number} premiers messages sur {total, number} au total (limite d'affichage).",
  "report.conn.direct": "Directe",
  "report.conn.nat": "Via NAT",
  "report.conn.relay": "Via Relais",
  "report.conn.unknown": "Inconnue",
  "report.counselor.adviseesTitle": "Mes étudiants suivis",
  "report.counselor.eyebrow": "Cours en direct · Rapport consolidé de session",
  "report.counselor.helpBody": "Vue conseiller : statistiques globales de présence (anonymisées) et état de présence des étudiants que vous suivez. Le chat et les transcriptions du cours sont exclus de cette vue.",
  "report.counselor.helpTitle": "Guide du rapport conseiller",
  "report.counselor.kpiAdvisees": "Étudiants suivis",
  "report.counselor.kpiTotal": "Total des étudiants",
  "report.counselor.noAdvisees": "Aucun de vos étudiants suivis n'est associé à cette session.",
  "report.counselor.statsTitle": "Statistiques de présence à la session",
  "report.engagement.hands": "Mains levées :",
  "report.engagement.handsTitle": "Mains levées",
  "report.engagement.notCaptured": "Les éléments interactifs n'ont pas été enregistrés pour cette session (fermeture sans « Terminer la session » ou aucune interaction en direct).",
  "report.engagement.polls": "Sondages :",
  "report.engagement.reactions": "Réactions :",
  "report.engagement.timelineTitle": "Chronologie",
  "report.engagement.title": "Engagement et interaction",
  "report.errLoad": "Échec du chargement du rapport de session.",
  "report.full.eyebrow": "Cours en direct · Rapport de session",
  "report.full.helpBody": "Ce rapport regroupe toutes les données enregistrées d'une session de cours : horaires réels, présences des étudiants, liste des participants, chat sauvegardé, transcription de la parole par intervenant, sondages, réactions et statut de l'enregistrement.",
  "report.full.helpTitle": "Guide du rapport de session",
  "report.hostSuffix": " (Hôte)",
  "report.kpi.absent": "Absents",
  "report.kpi.actualMinutes": "Durée réelle de la session",
  "report.kpi.chatCount": "Messages de chat",
  "report.kpi.joins": "Nombre de connexions",
  "report.kpi.myMinutes": "Ma durée de présence",
  "report.kpi.myStatus": "Mon statut de présence",
  "report.kpi.participants": "Participants",
  "report.kpi.presentIncLate": "Présents (retards inclus)",
  "report.kpi.scheduledMinutes": "Durée planifiée",
  "report.kpi.totalMinutes": "Total des minutes de présence",
  "report.loading": "Chargement du rapport de session…",
  "report.minutes": "{value, number} min",
  "report.neverOpened": "Cette session n'a pas eu lieu (aucune connexion de l'hôte enregistrée).",
  "report.noCourse": "Session générale",
  "report.noName": "Sans titre",
  "report.parent.childrenTitle": "Présence de l'enfant / des enfants",
  "report.parent.eyebrow": "Cours en direct · Rapport de présence enfant",
  "report.parent.helpBody": "Conformément à la politique d'accès, le rapport n'affiche que le récapitulatif de présence de votre enfant ; le chat et les transcriptions du cours ne sont pas visibles par les parents.",
  "report.parent.helpTitle": "Guide du rapport parent",
  "report.parent.kpiChildren": "Enfant associé à cette session",
  "report.parent.noChildren": "Aucun de vos enfants n'est associé à cette session.",
  "report.participants.empty": "Personne n'a rejoint cette session.",
  "report.participants.title": "Participants",
  "report.poll.ended": "Terminé",
  "report.poll.multi": " · Choix multiple",
  "report.poll.open": "Ouvert",
  "report.poll.total": "Total des votes : {value, number}",
  "report.polls.title": "Sondages",
  "report.recording.duration": " · {duration}",
  "report.recording.none": "Non disponible",
  "report.recording.play": "Lire l'enregistrement",
  "report.recording.processing": "Traitement en cours…",
  "report.self.attendanceTitle": "Ma présence",
  "report.self.eyebrow": "Cours en direct · Votre rapport pour cette session",
  "report.self.firstJoin": "Première connexion :",
  "report.self.helpBody": "Ceci est votre rapport personnel : votre présence, le chat public, vos interventions enregistrées et les contenus publics de la session (sondages et réactions).",
  "report.self.helpTitle": "Guide du rapport personnel",
  "report.self.joinsLabel": "Nombre de connexions :",
  "report.self.minutesLabel": "Temps de présence :",
  "report.self.myTranscript": "Mes interventions",
  "report.self.myTranscriptEmpty": "Aucune prise de parole enregistrée pour vous lors de cette session.",
  "report.self.reactionsTitle": "Réactions de la session",
  "report.self.reactionsTotal": "Total : {value, number}",
  "report.self.recordingTitle": "Enregistrement de la session",
  "report.table.conn": "Type de connexion",
  "report.table.firstJoin": "Première connexion",
  "report.table.joins": "Connexions",
  "report.table.minutes": "Durée",
  "report.table.name": "Nom",
  "report.table.status": "Statut",
  "report.timeline.breakoutClose": "Fermeture des salles de sous-commission",
  "report.timeline.breakoutOpen": "Ouverture des salles de sous-commission",
  "report.timeline.hand": "Main levée",
  "report.timeline.pollEnd": "Fin du sondage",
  "report.timeline.pollStart": "Début du sondage",
  "report.timing.actual": "Session réelle",
  "report.timing.late": "Démarrée avec {value, number} minutes de retard",
  "report.timing.notHeld": "Non tenue",
  "report.timing.onTime": "Démarrée à l'heure",
  "report.timing.range": "{start} à {end}",
  "report.timing.scheduled": "Planifiée",
  "report.timing.title": "Horaires",
  "report.transcript.empty": "Aucune parole enregistrée pour cette session (les sous-titres en direct ou la traduction n'étaient pas actifs).",
  "report.transcript.title": "Transcription de la parole par intervenant",
  "report.transcript.truncatedAll": "Une partie de la transcription a été omise en raison des limites de chargement.",
  "report.transcript.truncatedSpeaker": "Affichage des {shown, number} premières interventions sur {total, number} (limite d'affichage).",
  "report.transcript.utterances": "{value, number} interventions",
  "report.unavailable": "Le rapport de session est actuellement indisponible.",
  "playback.back": "Retour au rapport de session",
  "playback.chatTitle": "Chat public du replay",
  "playback.archivedChatTitle": "Chat archivé du direct (Lecture seule)",
  "playback.replayChatTitle": "Nouveau chat du replay",
  "playback.replayChatMessageLabel": "Nouveau message de replay",
  "playback.sendReplayChat": "Publier le message au repère temporel actuel",
  "playback.replayChatHidden": "Ce message a été masqué pour les autres",
  "playback.replayChatHide": "Masquer le message",
  "playback.replayChatUnhide": "Afficher le message",
  "playback.replayChatReportReason": "Motif du signalement du message",
  "playback.replayChatReport": "Signaler le message",
  "playback.replayChatUnavailable": "Le chat du replay n'est pas disponible ou l'action n'est pas autorisée.",
  "playback.loadMoreChat": "Charger les messages précédents",
  "playback.makeupTitle": "Crédit de présence par rattrapage en replay",
  "playback.makeupSeparateNotice": "Ce crédit est attribué après validation de l'enseignant et ne modifie pas les présences historiques.",
  "playback.makeupSessionLabel": "Identifiant de la session de rattrapage",
  "playback.makeupThresholdLabel": "Temps de visionnage minimum validé (pourcentage)",
  "playback.makeupEnable": "Activer le rattrapage",
  "playback.makeupDisable": "Désactiver le rattrapage",
  "playback.makeupThreshold": "Temps de visionnage minimum requis : {percent}%",
  "playback.makeupOpenSession": "Accéder au replay de la session de rattrapage",
  "playback.makeupWatched": "Temps de visionnage enregistré par le serveur : {percent}%",
  "playback.makeupReasonLabel": "Motif de la demande de rattrapage",
  "playback.makeupClaim": "Soumettre la demande de validation de rattrapage",
  "playback.makeupCreditStatus": "Statut du crédit : {status}",
  "playback.makeupStudentLabel": "Étudiant",
  "playback.makeupDecisionReasonLabel": "Motif de la décision de l'enseignant",
  "playback.makeupConfirm": "Valider le crédit de rattrapage",
  "playback.makeupReverse": "Annuler manuellement le crédit validé",
  "playback.makeupUnavailable": "L'action de présence par rattrapage n'est pas autorisée ou les informations sont indisponibles.",
  "playback.makeupStatus.pending": "En attente d'approbation",
  "playback.makeupStatus.confirmed": "Confirmé",
  "playback.makeupStatus.cancelled": "Annulé",
  "playback.makeupStatus.reversed": "Annulé a posteriori",
  "playback.artifactsTitle": "Éléments partagés persistants d'après-cours",
  "playback.artifactsAudienceNotice": "Ces éléments ne sont visibles que par les utilisateurs ayant accès à ce cours et à cet enregistrement ; les partages d'écran ne sont pas enregistrés.",
  "playback.artifactsEnableLearners": "Autoriser les contributions des apprenants",
  "playback.artifactsDisableLearners": "Désactiver les contributions des apprenants",
  "playback.artifactKindLabel": "Type de contenu",
  "playback.artifactTitleLabel": "Titre",
  "playback.artifactWhiteboardLabel": "Capture textuelle du tableau blanc",
  "playback.artifactDocumentLabel": "Identifiant du document de cours",
  "playback.artifactCreate": "Enregistrer l'élément partagé",
  "playback.artifactApprove": "Approuver la publication",
  "playback.artifactHide": "Masquer",
  "playback.artifactUnavailable": "L'enregistrement ou la gestion de cet élément n'est pas autorisé.",
  "playback.artifactKind.pdf": "PDF",
  "playback.artifactKind.whiteboard": "Tableau blanc",
  "playback.artifactKind.file_pin": "Fichier épinglé",
  "playback.artifactStatus.pending": "En attente d'approbation par l'enseignant",
  "playback.artifactStatus.published": "Publié",
  "playback.artifactStatus.hidden": "Masqué",
  "playback.notesTitle": "Mes notes horodatées",
  "playback.noteLabel": "Texte de la note",
  "playback.addNote": "Ajouter une note au repère actuel",
  "playback.saveNote": "Enregistrer la modification",
  "playback.editNote": "Modifier",
  "playback.deleteNote": "Supprimer",
  "playback.seekNote": "Aller au repère de la note",
  "playback.questionsTitle": "Questions du replay",
  "playback.questionLabel": "Question horodatée",
  "playback.askQuestion": "Poser une question",
  "playback.questionPublished": "Publiée pour la classe",
  "playback.questionOptIn": "Consentir à la publication",
  "playback.questionOptOut": "Retirer le consentement de publication",
  "playback.questionApprove": "Approuver la publication",
  "playback.questionUnpublish": "Dépublier",
  "playback.answerLabel": "Réponse officielle",
  "playback.answerQuestion": "Soumettre la réponse",
  "playback.roomTitle": "Salon de visionnage en groupe",
  "playback.createRoom": "Créer un salon privé",
  "playback.roomIdLabel": "Identifiant du salon",
  "playback.joinRoom": "Rejoindre le salon",
  "playback.roomUserLabel": "Identifiant utilisateur",
  "playback.inviteRoom": "Inviter",
  "playback.offerHandover": "Proposer le transfert de contrôle",
  "playback.acceptHandover": "Accepter le transfert",
  "playback.removeMember": "Retirer du salon",
  "playback.closeRoom": "Fermer le salon",
  "playback.roomPlay": "Lecture pour tous",
  "playback.roomPause": "Pause pour tous",
  "playback.roomSeek": "Déplacer la lecture de groupe au moment sélectionné",
  "playback.roomUnavailable": "Le salon est indisponible ou vous ne disposez pas des autorisations nécessaires.",
  "playback.roomWaiting": "En attente de connexion au salon…",
  "playback.questionUnavailable": "Cette action n'est pas autorisée ou la question n'est plus disponible.",
  "playback.questionHide": "Masquer la question",
  "playback.questionUnhide": "Afficher la question",
  "playback.questionHidden": "Masquée pour la classe",
  "playback.questionReportReason": "Motif du signalement de la question",
  "playback.questionReport": "Signaler la question",
  "playback.eyebrow": "Relecture interactive",
  "playback.loading": "Préparation du replay…",
  "playback.jump": "Aller à cet événement",
  "playback.jumpToPoll": "Aller au sondage {question}",
  "playback.jumpToTableStart": "Aller au début de l'activité en table",
  "playback.jumpToTranscript": "Aller à ce repère de transcription",
  "playback.speedLabel": "Vitesse de lecture",
  "playback.watchedProgress": "Replay visionné sur cet appareil : {percent}%",
  "playback.serverWatchEvidence": "Progression enregistrée sur le serveur : {percent}%.",
  "playback.notAttendanceCredit": "Cette valeur seule ne constitue pas un crédit de présence.",
  "playback.fullscreen": "Plein écran",
  "playback.captionsLabel": "Sous-titres de la session",
  "playback.showCaptions": "Afficher les sous-titres",
  "playback.hideCaptions": "Masquer les sous-titres",
  "playback.me": "Moi",
  "playback.noMatches": "Aucun texte correspondant à votre recherche.",
  "playback.noRecording": "Aucun enregistrement de replay n'est disponible pour cette session.",
  "playback.open": "Relecture interactive",
  "playback.pollsTitle": "Sondages enregistrés",
  "playback.pollNotReached": "Pour répondre, atteignez d'abord le repère de ce sondage dans le replay.",
  "playback.pollAnswerFailed": "Impossible d'enregistrer la réponse au replay ; veuillez réessayer.",
  "playback.searchLabel": "Rechercher dans la transcription",
  "playback.searchPlaceholder": "Rechercher dans les paroles de la session…",
  "playback.searchLoading": "Recherche dans la transcription en cours…",
  "playback.searchUnavailable": "La recherche dans la transcription n'est pas autorisée ou temporairement indisponible.",
  "playback.loadMoreResults": "Afficher plus de résultats",
  "playback.table": "Table {id}",
  "playback.timelineLabel": "Chronologie des événements du replay",
  "playback.transcriptTitle": "Transcription avec recherche",
  "playback.downloadTranscript": "Télécharger la transcription",
  "playback.transcriptDownloadUnavailable": "Le téléchargement de la transcription n'est pas autorisé ou temporairement indisponible.",
  "playback.unavailable": "Le replay de cette session n'est pas disponible."
}
