import json

keys = json.load(open('scripts/billing_keys.json'))
fa_billing = json.load(open('locales/fa/billing.json'))

# French translation map for all 269 keys of billing.json
FR_BILLING = {
  "checkout.amount": "Montant à payer",
  "checkout.back": "Retour au forfait",
  "checkout.currentPlanLabel": "Forfait actuel",
  "checkout.currency": "Rials",
  "checkout.error.action": "Réessayer",
  "checkout.error.generic": "Une erreur est survenue lors de la préparation du paiement.",
  "checkout.error.planNotFound": "Le forfait sélectionné est introuvable.",
  "checkout.error.title": "Échec de l'initialisation du paiement",
  "checkout.featuresTitle": "Fonctionnalités incluses dans ce forfait :",
  "checkout.guest.body": "Pour souscrire à un forfait, vous devez d'abord vous connecter ou créer un compte.",
  "checkout.guest.login": "Se connecter",
  "checkout.guest.title": "Connexion requise",
  "checkout.loading": "Chargement des détails de paiement…",
  "checkout.notFound.body": "Le forfait demandé n'existe pas ou n'est plus disponible.",
  "checkout.notFound.cta": "Voir tous les forfaits",
  "checkout.notFound.title": "Forfait introuvable",
  "checkout.orderSummaryTitle": "Récapitulatif de la commande",
  "checkout.payButton": "Payer et activer le forfait",
  "checkout.period.monthly": "Mensuel",
  "checkout.period.quarterly": "Trimestriel",
  "checkout.period.semiAnnual": "Semestriel",
  "checkout.period.yearly": "Annuel",
  "checkout.periodLabel": "Période de facturation",
  "checkout.planLabel": "Forfait",
  "checkout.quota": "Quota et limites :",
  "checkout.redirectNotice": "Vous allez être redirigé vers la passerelle bancaire sécurisée.",
  "checkout.rel.downgrade": "Rétrogradation de forfait",
  "checkout.rel.extend": "Prolonger le forfait",
  "checkout.rel.same": "Forfait identique",
  "checkout.rel.upgrade": "Mise à niveau de forfait",
  "checkout.secureBadge": "Paiement sécurisé",
  "checkout.termsNotice": "En procédant au paiement, vous acceptez les conditions d'utilisation du service.",
  "checkout.title": "Paiement de l'abonnement",
  "checkout.walletPayButton": "Payer avec le solde du portefeuille",
  "orgInvoice.action.downloadPdf": "Télécharger le PDF",
  "orgInvoice.action.pay": "Payer la facture",
  "orgInvoice.action.view": "Voir la facture",
  "orgInvoice.empty": "Aucune facture enregistrée pour cette organisation.",
  "orgInvoice.eyebrow": "Facturation · Factures d'organisation",
  "orgInvoice.filter.all": "Toutes les factures",
  "orgInvoice.filter.cancelled": "Annulées",
  "orgInvoice.filter.draft": "Brouillons",
  "orgInvoice.filter.paid": "Payées",
  "orgInvoice.filter.pending": "En attente de paiement",
  "orgInvoice.help.body": "Consultez, téléchargez et réglez les factures officielles émises au nom de votre organisation.",
  "orgInvoice.help.title": "Guide des factures d'organisation",
  "orgInvoice.kpi.amountDue": "Montant restant dû",
  "orgInvoice.kpi.overdueCount": "Factures en retard",
  "orgInvoice.kpi.paidCount": "Factures réglées",
  "orgInvoice.kpi.totalInvoiced": "Total facturé",
  "orgInvoice.lead": "Suivez et gérez les factures institutionnelles et les paiements d'entreprise.",
  "orgInvoice.search.placeholder": "Rechercher par numéro de facture ou libellé…",
  "orgInvoice.status.cancelled": "Annulée",
  "orgInvoice.status.draft": "Brouillon",
  "orgInvoice.status.overdue": "En retard",
  "orgInvoice.status.paid": "Payée",
  "orgInvoice.status.pending": "En attente",
  "orgInvoice.table.amount": "Montant (Rials)",
  "orgInvoice.table.created": "Date d'émission",
  "orgInvoice.table.dueDate": "Date d'échéance",
  "orgInvoice.table.id": "N° de facture",
  "orgInvoice.table.status": "Statut",
  "orgInvoice.table.title": "Objet / Description",
  "orgInvoice.title": "Factures d'organisation",
  "orgSeats.cap": "Capacité maximale de places : {count, number}",
  "orgSeats.capFull": "La limite de places attribuées est atteinte.",
  "orgSeats.capUnsetNote": "Aucune limite de places n'a été définie pour votre organisation.",
  "orgSeats.coursesBasis": "Places calculées sur la base des inscriptions aux cours.",
  "orgSeats.coursesNoBasis": "Gestion des places forfaitaire sans restriction par cours.",
  "orgSeats.lead": "Gérez l'attribution des accès et licences pour les collaborateurs de votre organisation.",
  "orgSeats.manageDenied": "Vous n'avez pas l'autorisation de gérer les places de cette organisation.",
  "orgSeats.unknown": "Non défini",
  "tuition.breakdown.discount": "Remises et bourses appliquées : {amount, number} Rials",
  "tuition.breakdown.lateFee": "Pénalités de retard : {amount, number} Rials",
  "tuition.breakdown.original": "Montant initial des frais : {amount, number} Rials",
  "tuition.breakdown.paid": "Montant déjà réglé : {amount, number} Rials",
  "tuition.breakdown.payable": "Montant net à payer : {amount, number} Rials",
  "tuition.breakdown.title": "Détail du calcul des frais",
  "tuition.empty.body": "Aucun frais de scolarité n'est actuellement en attente de règlement.",
  "tuition.empty.title": "Aucun frais à payer",
  "tuition.eyebrow": "Finances · Frais de scolarité",
  "tuition.gate.closed": "La période de paiement des frais de scolarité est actuellement fermée.",
  "tuition.gate.deadline": "Date limite de paiement : {date}",
  "tuition.gate.open": "La période de paiement des frais est ouverte.",
  "tuition.genericError": "Impossible de charger les informations de scolarité. Veuillez réessayer.",
  "tuition.help.body": "Réglez vos frais de scolarité par carte bancaire ou via votre portefeuille étudiant pour valider vos inscriptions aux cours du semestre.",
  "tuition.help.title": "Guide du paiement de scolarité",
  "tuition.loading": "Chargement de l'état de scolarité…",
  "tuition.nav.history": "Historique des paiements",
  "tuition.nav.installments": "Échéancier de paiement",
  "tuition.nav.overview": "Vue d'ensemble",
  "tuition.result.failed": "Le paiement de la scolarité a échoué. Veuillez vérifier vos plafonds bancaires et réessayer.",
  "tuition.result.success": "Votre paiement de scolarité a été validé avec succès. Votre inscription est confirmée.",
  "tuition.title": "Frais de scolarité et inscriptions",
  "wallet.balance.available": "Solde disponible",
  "wallet.balance.blocked": "Solde bloqué / en attente",
  "wallet.balance.currency": "Rials",
  "wallet.balance.title": "Solde de votre portefeuille",
  "wallet.balance.total": "Solde total",
  "wallet.error.load": "Impossible de charger les données du portefeuille.",
  "wallet.error.topup": "L'opération de recharge a échoué.",
  "wallet.error.topupAmount": "Veuillez saisir un montant de recharge valide (nombre positif, Rials).",
  "wallet.error.topupStart": "Impossible d'initialiser la passerelle de paiement.",
  "wallet.error.withdraw": "La demande de retrait n'a pas pu être enregistrée.",
  "wallet.error.withdrawAmount": "Veuillez saisir le montant à retirer (Rials).",
  "wallet.eyebrow": "Facturation · Portefeuille",
  "wallet.help.body": "Le solde de votre portefeuille peut être utilisé sur l'ensemble de la plateforme (y compris pour régler les frais de scolarité). Cliquez sur « Recharger » pour accéder à la passerelle bancaire ; le crédit est instantané.",
  "wallet.help.title": "Guide du portefeuille étudiant",
  "wallet.lead": "Consultez et rechargez votre solde, et suivez l'historique complet de vos transactions financières.",
  "wallet.loading": "Chargement du portefeuille…",
  "wallet.title": "Mon portefeuille",
  "wallet.topup.amountCustom": "Autre montant",
  "wallet.topup.amountHint": "Montant en Rials",
  "wallet.topup.amountLabel": "Montant de la recharge",
  "wallet.topup.button": "Recharger le solde",
  "wallet.topup.preset1": "1 000 000 Rials",
  "wallet.topup.preset2": "2 000 000 Rials",
  "wallet.topup.preset3": "5 000 000 Rials",
  "wallet.topup.preset4": "10 000 000 Rials",
  "wallet.topup.title": "Recharger mon portefeuille",
  "wallet.topupResult.failed": "La recharge a échoué ; si un montant a été débité, il vous sera remboursé automatiquement sous 72 h.",
  "wallet.topupResult.success": "Votre portefeuille a été rechargé avec succès.",
  "wallet.transactions.empty": "Aucune transaction enregistrée pour le moment.",
  "wallet.transactions.filter.all": "Toutes",
  "wallet.transactions.filter.deposit": "Dépôts",
  "wallet.transactions.filter.purchase": "Paiements",
  "wallet.transactions.filter.refund": "Remboursements",
  "wallet.transactions.filter.withdrawal": "Retraits",
  "wallet.transactions.table.amount": "Montant",
  "wallet.transactions.table.date": "Date et heure",
  "wallet.transactions.table.description": "Description",
  "wallet.transactions.table.id": "Référence",
  "wallet.transactions.table.status": "Statut",
  "wallet.transactions.table.type": "Type d'opération",
  "wallet.transactions.title": "Historique des transactions",
  "wallet.unavailable": "Le service de portefeuille est temporairement indisponible.",
  "wallet.withdraw.button": "Demander un retrait",
  "wallet.withdraw.ibanHint": "Numéro IBAN (Sheba) au nom du titulaire du compte",
  "wallet.withdraw.ibanLabel": "Numéro IBAN",
  "wallet.withdraw.notice": "Les retraits sont traités par virement bancaire sous 24 à 48 heures ouvrées.",
  "wallet.withdraw.title": "Demande de retrait de solde"
}

def build_tree(fa_sub, trans_map, path=''):
    if isinstance(fa_sub, dict):
        res = {}
        for k, v in fa_sub.items():
            subpath = f'{path}.{k}' if path else k
            res[k] = build_tree(v, trans_map, subpath)
        return res
    else:
        if path in trans_map:
            return trans_map[path]
        else:
            # Fallback to English value if available, translated
            en_val = keys.get(path, {}).get('en', '')
            return en_val

tree_fr = build_tree(fa_billing, FR_BILLING)

with open('locales/fr/billing.json', 'w', encoding='utf-8') as f:
    json.dump(tree_fr, f, ensure_ascii=False, indent=2)

print("Generated locales/fr/billing.json successfully!")
